export const TRANSLATION_STATUS = "draft" as const;

export const AR_QUESTIONS_ES: Record<number, { text: string; options: [string, string, string, string] }> = {
  1:  { text: "¿Qué sigue en la secuencia? 2, 6, 18, 54, ___", options: ["108", "162", "216", "324"] },
  2:  { text: "¿Qué sigue en la secuencia de letras? A, C, F, J, O, ___", options: ["T", "U", "V", "W"] },
  3:  { text: "Una secuencia repetitiva: Triángulo, Círculo, Cuadrado, Triángulo, Círculo, ___", options: ["Triángulo", "Círculo", "Cuadrado", "Pentágono"] },
  4:  { text: "En una cuadrícula 3×3, cada fila contiene ●, ■ y ▲ exactamente una vez. Fila 1: ●, ■, ▲. Fila 2: ■, ▲, ●. Fila 3: ▲, ●, ___.", options: ["●", "■", "▲", "Ninguno de estos"] },
  5:  { text: "¿Qué sigue? 1, 1, 2, 3, 5, 8, ___", options: ["11", "12", "13", "14"] },
  6:  { text: "¿Qué número completa la secuencia? 4, 9, 16, 25, 36, ___", options: ["42", "46", "49", "54"] },
  7:  { text: "¿Cuál es el intruso? Cuadrado · Rectángulo · Triángulo · Círculo · Pentágono", options: ["Cuadrado", "Rectángulo", "Círculo", "Pentágono"] },
  8:  { text: "Un patrón de puntos crece: 1, 4, 9, 16, ___", options: ["20", "25", "24", "30"] },
  9:  { text: "¿Qué sigue? Z, X, V, T, R, ___", options: ["O", "P", "Q", "N"] },
  10: { text: "Las formas alternan llenas/vacías: cuadrado lleno, cuadrado vacío, círculo lleno, círculo vacío, triángulo lleno. ¿Qué sigue?", options: ["Cuadrado lleno", "Triángulo lleno", "Triángulo vacío", "Círculo vacío"] },
  11: { text: "¿Qué sigue? 3, 7, 15, 31, 63, ___", options: ["95", "111", "127", "120"] },
  12: { text: "¿Qué número NO pertenece? 16, 25, 36, 42, 49, 64", options: ["25", "36", "42", "49"] },
  13: { text: "Cada fila suma 15. Fila 1: 8, 4, 3. Fila 2: 9, 2, 4. Fila 3: 6, 5, ___.", options: ["3", "4", "5", "6"] },
  14: { text: "¿Qué sigue en esta secuencia de números primos? 2, 3, 5, 7, 11, 13, ___", options: ["15", "17", "19", "14"] },
  15: { text: "Una flecha apuntando hacia arriba gira 90° en el sentido de las agujas del reloj en cada paso. En el paso 5 (después de 4 rotaciones), la flecha apunta:", options: ["Arriba", "A la derecha", "Abajo", "A la izquierda"] },
  16: { text: "¿Qué sigue? AB, DE, GH, JK, ___", options: ["MN", "LM", "NO", "NP"] },
  17: { text: "Una cuadrícula: Columna 1 = círculos, Columna 2 = cuadrados, Columna 3 = triángulos. Filas 1/2/3 = grande/mediano/pequeño. ¿Qué hay en fila 3, columna 2?", options: ["Círculo grande", "Triángulo pequeño", "Cuadrado pequeño", "Cuadrado mediano"] },
  18: { text: "¿Qué sigue? 100, 50, 25, 12.5, ___", options: ["5", "6.25", "10", "6"] },
  19: { text: "¿Cuál figura es el intruso si todas las demás tienen exactamente 4 lados? Cuadrado · Rectángulo · Rombo · Trapecio · Pentágono", options: ["Cuadrado", "Rectángulo", "Rombo", "Pentágono"] },
  20: { text: "¿Qué sigue? 1, 4, 13, 40, ___", options: ["100", "121", "80", "130"] },
  21: { text: "Una cuadrícula 3×3 contiene los dígitos 1, 2 y 3 una vez por fila y columna. Fila 1: 1,2,3. Fila 2: 3,1,2. Fila 3: 2,_,1.", options: ["1", "2", "3", "4"] },
  22: { text: "¿Qué sigue? A1, B4, C9, D16, ___", options: ["E20", "E25", "F25", "E24"] },
  23: { text: "Patrón de colores: Rojo, Azul, Verde, Rojo, Azul, Verde, Rojo, Azul, ___", options: ["Rojo", "Azul", "Verde", "Amarillo"] },
  24: { text: "Regla de cuadrícula numérica: cada número se duplica a lo largo de la fila. Fila 1: 2, 4, 8. Fila 2: 3, 6, 12. Fila 3: 5, 10, ___.", options: ["15", "18", "20", "25"] },
  25: { text: "¿Qué sigue? 1, 2, 4, 7, 11, 16, ___", options: ["20", "21", "22", "23"] },
};
