export const TRANSLATION_STATUS = "reviewed" as const;

export const AQ_QUESTIONS_ES: Record<number, { text: string }> = {
  1:  { text: "Cuando me enfrento a una situación difícil en el trabajo, creo que puedo influir en el resultado." },
  2:  { text: "Cuando algo sale mal, me pregunto qué podría haber hecho diferente, incluso si no fue mi culpa." },
  3:  { text: "Cuando enfrento un contratiempo en el trabajo, suele afectar negativamente mi vida personal también." },
  4:  { text: "Cuando enfrento un gran contratiempo, siento sus efectos negativos durante mucho tiempo después." },
  5:  { text: "Siento que tengo un poder real para determinar cómo resultan los desafíos en mi vida." },
  6:  { text: "Asumo responsabilidad personal para mejorar situaciones, incluso cuando otros crearon el problema." },
  7:  { text: "Los problemas en un área de mi vida tienden a extenderse a otras áreas." },
  8:  { text: "Me toma una cantidad significativa de tiempo recuperarme después de una adversidad." },
  9:  { text: "Incluso en situaciones caóticas, puedo encontrar algo dentro de mi control." },
  10: { text: "Me hago responsable de los resultados en mi vida." },
  11: { text: "Un solo fracaso a menudo me hace cuestionar mis habilidades en áreas que no guardan ninguna relación." },
  12: { text: "El impacto de los problemas en mi vida tiende a persistir mucho más allá del evento inicial." },
  13: { text: "Cuando las cosas salen mal, me enfoco en lo que puedo hacer de otra manera en lugar de sentirme impotente." },
  14: { text: "Cuando mi equipo falla, examino mi propia contribución independientemente del rol de los demás." },
  15: { text: "Cuando algo sale mal, tiende a afectar el resto de mi día en otras áreas también." },
  16: { text: "A menudo me preocupa que las dificultades actuales me persigan durante mucho tiempo." },
  17: { text: "Confío en mi capacidad para navegar por circunstancias difíciles." },
  18: { text: "Rara vez busco excusas cuando las cosas no salen como estaba planeado." },
  19: { text: "Las dificultades en mi vida profesional afectan significativamente cómo me relaciono con amigos y familia." },
  20: { text: "Cuando ocurre algo malo, tiendo a creer que me afectará durante mucho tiempo." },
  21: { text: "Rara vez me siento completamente impotente cuando enfrento un obstáculo importante." },
  22: { text: "Tomo medidas activas para abordar los problemas en lugar de esperar que otros los resuelvan." },
  23: { text: "Cuando me enfrento a la adversidad, socava mi confianza en muchas áreas diferentes." },
  24: { text: "Me cuesta imaginar un futuro donde los desafíos actuales estén resueltos." },
  25: { text: "Creo que mis acciones hacen una diferencia significativa ante la adversidad." },
  26: { text: "Me siento personalmente responsable de mejorar las situaciones difíciles que encuentro." },
  27: { text: "Encuentro que un problema tiende a crear una reacción en cadena de otros problemas en mi vida." },
  28: { text: "Después de un fracaso, me toma un tiempo considerable antes de sentirme como de costumbre." },
  29: { text: "Cuando las circunstancias son abrumadoras, aún identifico cosas en las que puedo actuar." },
  30: { text: "Reconozco mi parte en los contratiempos, incluso cuando los factores externos jugaron un papel importante." },
  31: { text: "Un contratiempo en una relación a menudo afecta cómo interactúo con otras personas." },
  32: { text: "A menudo siento que los efectos de la adversidad en mi vida son permanentes o casi permanentes." },
  33: { text: "Me siento capaz de manejar la mayoría de los desafíos que se me presentan." },
  34: { text: "Cuando me enfrento a la adversidad, mi primer instinto es preguntarme qué puedo hacer para mejorar la situación." },
  35: { text: "Cuando las cosas salen mal, tiendo a sentir que todo en mi vida se derrumba." },
  36: { text: "Cuando me enfrento a una situación difícil, tiendo a creer que persistirá durante mucho tiempo." },
  37: { text: "Me enfoco en lo que puedo cambiar en lugar de quedarme pensando en lo que no puedo." },
  38: { text: "Me exijo altos estándares en la forma en que respondo a los desafíos." },
  39: { text: "La adversidad en una parte de mi vida me dificulta funcionar bien en otras partes." },
  40: { text: "Las dificultades que enfrento parecen tener impactos duraderos y permanentes en mi vida." },
};
