export const TRANSLATION_STATUS = "draft" as const;

export const CS_QUESTIONS_ES: Record<number, { text: string }> = {
  1:  { text: "Organizo mis comunicaciones escritas con una estructura clara antes de escribir." },
  2:  { text: "Reviso cuidadosamente mi trabajo escrito antes de enviarlo." },
  3:  { text: "Adapto el tono y la formalidad de mi escritura según el destinatario." },
  4:  { text: "Mi escritura suele ser poco clara o difícil de entender para otros." },
  5:  { text: "Uso un lenguaje preciso al escribir para evitar malentendidos." },
  6:  { text: "Mantengo los mensajes escritos concisos sin omitir información importante." },
  7:  { text: "Me cuesta expresar ideas complejas con claridad por escrito." },
  8:  { text: "Elijo el formato escrito más adecuado (correo, informe, memorando) para cada situación." },
  9:  { text: "Me aseguro de que el mensaje clave esté claramente establecido al inicio de mis comunicaciones escritas." },
  10: { text: "Hablo con claridad y a un ritmo adecuado para mi audiencia." },
  11: { text: "Organizo mis puntos verbalmente de forma lógica antes de hablar." },
  12: { text: "Me siento cómodo/a contribuyendo a debates en reuniones." },
  13: { text: "Tiendo a divagar o perder el hilo cuando hablo." },
  14: { text: "Adapto mi estilo de comunicación verbal según con quién esté hablando." },
  15: { text: "Expreso desacuerdos o ideas alternativas de manera respetuosa y clara." },
  16: { text: "Suelo evitar hablar en entornos grupales incluso cuando tengo algo relevante que aportar." },
  17: { text: "Puedo resumir un tema complejo en términos simples y accesibles cuando es necesario." },
  18: { text: "Uso ejemplos relevantes para que las explicaciones verbales sean más claras." },
  19: { text: "Presto toda mi atención al orador y evito distracciones." },
  20: { text: "Hago preguntas aclaratorias cuando no estoy seguro/a de haber entendido correctamente." },
  21: { text: "Puedo recordar con precisión los puntos clave de una conversación después de que ocurre." },
  22: { text: "Suelo distraerme cuando otra persona está hablando." },
  23: { text: "Escucho para entender, no solo para formular mi respuesta." },
  24: { text: "Noto las señales emocionales en la voz de alguien además de sus palabras." },
  25: { text: "Interrumpo a otros antes de que hayan terminado de hablar." },
  26: { text: "Parafraseo lo que he escuchado para confirmar mi comprensión." },
  27: { text: "Puedo seguir instrucciones verbales detalladas sin necesitar que se repitan." },
  28: { text: "Soy consciente de cómo mi lenguaje corporal puede afectar el mensaje que comunico." },
  29: { text: "Mantengo un contacto visual apropiado al hablar o escuchar." },
  30: { text: "Noto señales no verbales que indican cómo se siente alguien." },
  31: { text: "Me cuesta interpretar con precisión las expresiones faciales o el lenguaje corporal." },
  32: { text: "Uso gestos y expresiones faciales de forma natural para reforzar mi mensaje oral." },
  33: { text: "Mi lenguaje corporal es coherente con lo que estoy diciendo." },
  34: { text: "Generalmente no soy consciente de cómo me veo físicamente en una conversación." },
  35: { text: "Puedo identificar cuando las señales no verbales de alguien contradicen lo que está diciendo." },
};
