export const TRANSLATION_STATUS = "draft" as const;

export const CT_QUESTIONS_ES: Record<number, { text: string; options: [string, string, string, string] }> = {
  1:  { text: "Todos los mamíferos son de sangre caliente. Un delfín es un mamífero. ¿Qué debe ser verdad?", options: ["Todos los animales de sangre caliente son mamíferos", "Los delfines son de sangre caliente", "Los delfines no pueden sobrevivir en agua fría", "Ningún animal de sangre fría vive en el agua"] },
  2:  { text: "Si todos los Blems son Trams, y ningún Tram es Spod, ¿cuál afirmación debe ser verdad?", options: ["Algunos Blems son Spods", "Ningún Blem es Spod", "Todos los Trams son Blems", "Algunos Spods son Blems"] },
  3:  { text: "Alex corre más rápido que Ben. Carol corre más lento que Anna. Ben corre más rápido que Carol. ¿Quién llegó último en una carrera?", options: ["Alex", "Ben", "Carol", "No se puede determinar"] },
  4:  { text: "Enunciado: 'Si estudias mucho, aprobarás.' Jana no aprobó. ¿Qué debe ser verdad?", options: ["Jana no estudió mucho", "Jana estudió pero no lo suficiente", "Estudiar no está relacionado con aprobar", "Jana estaba enferma durante el examen"] },
  5:  { text: "¿Qué sigue en la serie: 2, 6, 18, 54, ___?", options: ["108", "162", "216", "90"] },
  6:  { text: "Tres cajas están etiquetadas 'Manzanas', 'Naranjas' y 'Mixta'. Las tres etiquetas son incorrectas. Saca una manzana de la caja 'Mixta'. ¿Qué contiene la caja 'Naranjas'?", options: ["Manzanas", "Mixta (ambas frutas)", "Naranjas", "No se puede determinar"] },
  7:  { text: "Un estudio encuentra que las personas con más libros obtienen mejores puntajes en pruebas de lectura. Un investigador concluye que tener libros mejora la lectura. ¿Cuál es el error principal?", options: ["El tamaño de la muestra es desconocido", "La correlación no implica causalidad", "Las pruebas de lectura no son confiables", "Se necesitan más datos"] },
  8:  { text: "En una clase, todos los estudiantes que aprobaron entregaron sus tareas. Tom no entregó su tarea. ¿Qué podemos concluir?", options: ["Tom aprobó la clase", "Tom no aprobó", "Tom estuvo ausente", "Entregar garantiza aprobar"] },
  9:  { text: "¿Qué sigue: 1, 1, 2, 3, 5, 8, 13, ___?", options: ["18", "20", "21", "26"] },
  10: { text: "Dos ciclistas parten del mismo punto en direcciones opuestas a 15 km/h y 20 km/h. ¿Cuántas horas tardan en estar a 105 km de distancia?", options: ["2 horas", "3 horas", "4 horas", "5 horas"] },
  11: { text: "¿Qué sigue: 3, 8, 15, 24, 35, ___?", options: ["42", "46", "48", "50"] },
  12: { text: "Si 6 trabajadores completan una tarea en 10 días, ¿cuántos días tardarían 4 trabajadores?", options: ["12 días", "15 días", "18 días", "20 días"] },
  13: { text: "Un precio aumenta 20% y luego disminuye 20%. ¿Cuál es el cambio neto respecto al precio original?", options: ["0% (sin cambio)", "4% de disminución", "4% de aumento", "2% de disminución"] },
  14: { text: "¿Qué sigue: 1, 4, 9, 16, 25, ___?", options: ["30", "34", "36", "42"] },
  15: { text: "Un tanque se llena en 12 minutos con la tubería A abierta. Se vacía en 20 minutos con la tubería B abierta. ¿Cuánto tarda en llenarse desde vacío con ambas tuberías abiertas?", options: ["24 min", "28 min", "30 min", "32 min"] },
  16: { text: "¿Cuál es el número faltante: 7, 14, ___, 56, 112?", options: ["21", "24", "28", "35"] },
  17: { text: "Una encuesta muestra que el 75% de la gente prefiere la Marca A. La encuesta se realizó entre los propios empleados de la Marca A. ¿Cuál es el problema principal?", options: ["75% no es una mayoría", "La muestra está muy sesgada", "La Marca B necesita mejor marketing", "Se necesitan más encuestados"] },
  18: { text: "¿Qué sigue: 5, 10, 20, 40, ___?", options: ["60", "70", "80", "100"] },
  19: { text: "MÉDICO es a PACIENTE como MAESTRO es a ___?", options: ["Escuela", "Estudiante", "Aula", "Lección"] },
  20: { text: "¿Cuál elemento NO pertenece al grupo: Cobre, Oro, Mercurio, Hierro?", options: ["Cobre", "Oro", "Mercurio", "Hierro"] },
  21: { text: "Si toda investigación publicada es revisada por pares, y este artículo no fue revisado, ¿qué podemos concluir?", options: ["El artículo no es creíble", "El artículo no fue publicado", "La revisión por pares es innecesaria", "El artículo puede haber sido publicado de todas formas"] },
  22: { text: "¿Qué sigue en esta secuencia de números primos: 2, 3, 5, 7, 11, 13, ___?", options: ["15", "17", "19", "21"] },
  23: { text: "OSCURO es a CLARO como FRÍO es a ___?", options: ["Hielo", "Cálido", "Caliente", "Temperatura"] },
  24: { text: "Anna, Ben y Carol tienen una mascota cada uno: gato, perro o pez. Ben no tiene gato. Anna tiene perro. ¿Qué mascota tiene Carol?", options: ["Gato", "Perro", "Pez", "No se puede determinar"] },
  25: { text: "¿Cuál es el ángulo entre las manecillas del reloj a las 9:00?", options: ["270°", "180°", "90°", "45°"] },
  26: { text: "¿Cuál es un ejemplo de razonamiento circular?", options: ["'La Biblia es verdad porque así lo dice la Biblia.'", "'Todos los cisnes son blancos porque la mayoría que he visto son blancos.'", "'El suelo está mojado, por lo tanto debe haber llovido.'", "'Juan siempre llega tarde, así que llegará tarde hoy.'"] },
  27: { text: "Un caracol sube 3 m por una pared cada día, pero retrocede 2 m cada noche. La pared mide 10 m. ¿En qué día llega el caracol a la cima?", options: ["Día 7", "Día 8", "Día 9", "Día 10"] },
  28: { text: "¿Qué argumento contiene un falso dilema?", options: ["'Estás con nosotros o contra nosotros.'", "'Los estudios muestran que el ejercicio reduce el riesgo cardíaco.'", "'La mayoría de los expertos coincide en que las vacunas son seguras.'", "'La evidencia sugiere que la economía mejora.'"] },
  29: { text: "CHEF es a COCINA como CIRUJANO es a ___?", options: ["Hospital", "Doctor", "Quirófano", "Medicina"] },
  30: { text: "Lanzas una moneda justa tres veces y obtienes cara cada vez. ¿Cuál es la probabilidad de que el siguiente lanzamiento también sea cara?", options: ["Menos de 50% — es improbable", "Exactamente 50%", "Más de 50% — está pendiente", "25%"] },
  31: { text: "¿Qué sigue: ZA, YB, XC, WD, ___?", options: ["VE", "VF", "UE", "UF"] },
  32: { text: "Una tienda vende artículos con un margen de ganancia del 25%. Si el costo es $80, ¿cuál es el precio de venta?", options: ["$95", "$100", "$105", "$110"] },
  33: { text: "Tienes una jarra de 3 litros y una de 5 litros con agua ilimitada. ¿Cómo mides exactamente 4 litros?", options: ["Llena la de 5L, vierte en la de 3L hasta llenarla (quedan 2L). Vacía la de 3L. Pon los 2L en la de 3L. Rellena la de 5L, vierte 1L en la de 3L. Quedan 4L en la de 5L.", "Llena ambas y combínalas", "Es imposible con estas dos jarras", "Llena la de 3L dos veces, luego quita 2L"] },
  34: { text: "Los ingresos de una empresa crecieron de $200,000 a $250,000. ¿Cuál fue el aumento porcentual?", options: ["20%", "25%", "50%", "15%"] },
  35: { text: "¿Cuál es un ejemplo de falacia ad hominem?", options: ["'No confíes en sus consejos de dieta — claramente tiene sobrepeso.'", "'Los estudios muestran que el ejercicio es beneficioso para la salud cardíaca.'", "'Si baja el desempleo, la confianza del consumidor suele aumentar.'", "'Como la mayoría de la gente cree en X, X es probablemente verdad.'"] },
  36: { text: "¿Cuál es el siguiente número: 0, 1, 3, 6, 10, 15, ___?", options: ["18", "20", "21", "24"] },
  37: { text: "Un investigador da un nuevo medicamento solo a voluntarios que lo solicitaron específicamente e informa una reducción del 40% en síntomas. ¿Cuál es la PRINCIPAL debilidad del estudio?", options: ["Una reducción del 40% es estadísticamente insignificante", "Los voluntarios pueden no representar a todos los pacientes", "No se mencionan los efectos secundarios", "La empresa farmacéutica puede haber financiado el estudio"] },
  38: { text: "GUANTES son a MANOS como ZAPATOS son a ___?", options: ["Calcetines", "Pies", "Piernas", "Caminar"] },
  39: { text: "Si HAPPY se codifica como IBQQZ (cada letra +1), ¿cómo se codifica THINK?", options: ["UIJOL", "THHNK", "UIIOL", "VJKOL"] },
  40: { text: "Una bolsa contiene 5 bolas rojas y 3 azules. Se sacan dos sin reemplazo. ¿Cuál es la probabilidad de que ambas sean rojas?", options: ["25/64", "5/14", "10/64", "1/2"] },
};
