export const TRANSLATION_STATUS = "draft" as const;

export const CSERV_QUESTIONS_ES: Record<number, { text: string; options: [string, string, string, string] }> = {
  // Empathy (9)
  1:  { text: "Un cliente llama extremadamente molesto por un pedido retrasado. ¿Cuál es su primera acción?", options: ["Explica de inmediato las razones operativas del retraso", "Reconoce lo frustrante que debe ser y se disculpa sinceramente antes de pedir cualquier detalle", "Transfiere la llamada a un gerente que se ocupe de las quejas", "Pide el número de pedido para poder verificar el estado de inmediato"] },
  2:  { text: "Un cliente dice: 'Nadie en su empresa me escucha.' ¿Cuál es la mejor respuesta?", options: ["'Lamento que se sienta así — déjeme verificar su cuenta.'", "'Quiero asegurarme de que hoy sea diferente. Por favor cuénteme qué está pasando y le prestaré toda mi atención.'", "Defiende el historial de servicio de su empresa con datos", "Se disculpa y escala inmediatamente a un agente sénior sin involucrarse más"] },
  3:  { text: "¿Cuál respuesta demuestra mejor empatía genuina ante un cliente frustrado?", options: ["'Entiendo.'", "'Eso no debería haber ocurrido — tiene todo el sentido que esté frustrado/a, y quiero solucionar esto para usted.'", "'Todos cometemos errores — nuestro equipo es humano.'", "'No es el primer cliente al que le pasa esto, así que tenemos un proceso para ello.'"] },
  4:  { text: "Un cliente está molesto porque un producto en el que confiaba falló durante un evento importante. ¿Cuál es la mejor respuesta?", options: ["Pasa directamente a la resolución de problemas — eso es lo que necesita", "Ofrece un reembolso o reemplazo de inmediato", "Reconoce primero el impacto emocional: 'Lo lamento mucho, sé que esto ocurrió en un momento tan importante para usted'", "Explica las limitaciones declaradas del producto y los términos de garantía"] },
  5:  { text: "Un cliente dice que se siente avergonzado porque no pudo entender cómo usar su producto. ¿Cuál es la mejor respuesta?", options: ["Le tranquiliza diciéndole que el producto es sencillo para la mayoría de los usuarios", "Le dice que muchos clientes encuentran exactamente este paso confuso y se ofrece a guiarle por él ahora mismo", "Envía un enlace a la guía del usuario para que la lea", "Transfiere a soporte técnico"] },
  6:  { text: "¿Cómo puede demostrar mejor empatía en una respuesta escrita de atención al cliente?", options: ["Comienza con 'Estimado/a Cliente' y pasa directamente a la resolución", "Comienza reconociendo específicamente la experiencia del cliente, luego aborda el problema", "Usa un lenguaje formal y profesional en todo momento para transmitir competencia", "Enumera todos los pasos que el cliente debe seguir para resolver su problema de forma clara y eficiente"] },
  7:  { text: "Un cliente está enojado por un error de facturación en su cuenta. Antes de solicitar cualquier dato de la cuenta, ¿qué debe hacer?", options: ["Explica el proceso de facturación para que entienda cómo funciona", "Reconoce el error claramente y afirma que lo va a corregir", "Le dice que estos errores son ocasionalmente inevitables en sistemas de facturación grandes", "Transfiere al departamento de facturación de inmediato"] },
  8:  { text: "¿Qué enfoque construye mejor la confianza a largo plazo con el cliente?", options: ["Ofrecer siempre descuentos cuando un cliente presenta una queja", "Responder rápidamente con respuestas educadas pero genéricas", "Cumplir sistemáticamente lo que dice que hará y verificar proactivamente después de que se resuelvan los problemas", "Escalar cada queja a un miembro sénior del equipo para mostrar que se toma en serio"] },
  9:  { text: "Una llamada termina con una resolución implementada, pero el cliente aún no parece satisfecho. ¿Cuál es el mejor siguiente paso?", options: ["Cierra el caso — el problema fue resuelto técnicamente", "Hace un seguimiento 24–48 horas después para confirmar que la resolución funcionó y verificar que ahora se siente escuchado/a", "Aplica automáticamente un descuento en su próxima factura", "Activa de inmediato una encuesta de satisfacción mientras la interacción está fresca"] },
  // Problem Resolution (9)
  10: { text: "Un cliente reporta un producto defectuoso. ¿Cuál es el primer paso más efectivo?", options: ["Se disculpa y ofrece un reembolso completo o reemplazo de inmediato", "Recopila los detalles del defecto — qué ocurrió, cuándo, cómo les afectó y qué resultado necesitan", "Le dice al cliente que devuelva el producto a través del proceso estándar", "Transfiere a un equipo especializado sin recopilar ninguna información primero"] },
  11: { text: "Un cliente solicita un reembolso que su política normalmente no cubre. ¿Cuál es el mejor enfoque?", options: ["Se niega de inmediato y cita su política textualmente", "Reconoce completamente la situación, verifica si aplica alguna excepción y explica claramente todas las opciones disponibles", "Ofrece crédito en la tienda sin explorar la situación completa", "Escala sin recopilar todos los hechos relevantes primero"] },
  12: { text: "Ha resuelto el problema de un cliente pero no está completamente seguro/a de que la solución se mantendrá. ¿Qué hace?", options: ["Le dice al cliente que el problema está definitiva y permanentemente resuelto", "Es transparente: explica lo que ha hecho y establece un período de tiempo para confirmar que el problema se ha resuelto", "Cierra el ticket y espera a ver si vuelven a contactarle", "Entrega el ticket a un equipo técnico y cierra su participación"] },
  13: { text: "Un cliente le contacta con un problema complejo que requiere la participación de múltiples equipos internos. ¿Cuál es el mejor enfoque?", options: ["Transfiere al primer equipo disponible y deja que coordinen", "Se hace dueño personal del problema, coordina internamente y mantiene al cliente actualizado en cada etapa hasta que esté completamente resuelto", "Pide al cliente que contacte directamente a cada equipo relevante", "Pide al cliente que presente su problema por escrito antes de tomar cualquier acción"] },
  14: { text: "Un cliente le ha contactado sobre el mismo problema recurrente por tercera vez. ¿Qué debe hacer de forma diferente?", options: ["Resuelve el problema de la misma manera que antes — el proceso ha funcionado en el pasado", "Resuelve el problema inmediato Y escala internamente para investigar y abordar la causa raíz para que no vuelva a ocurrir", "Ofrece un descuento por las molestias y cierra el ticket rápidamente", "Pide al cliente que cambie su comportamiento para evitar desencadenar el problema"] },
  15: { text: "Después de resolver el problema de un cliente, ¿qué acción añade más valor?", options: ["Cierra el caso de inmediato — su tiempo es necesario para otros clientes", "Confirma que la resolución cumplió con las expectativas del cliente y pregunta si necesita algo más antes de cerrar", "Pide al cliente que deje una reseña de la interacción", "Envía una oferta promocional como gesto de buena voluntad"] },
  16: { text: "Un cliente quiere una resolución que sus sistemas actualmente no pueden proporcionar. ¿Cuál es la mejor respuesta?", options: ["Le dice que es técnicamente imposible y cierra el caso", "Reconoce la limitación claramente, explica lo que puede hacer ahora y establece expectativas realistas sobre qué es posible y para cuándo", "Promete lo que está pidiendo para satisfacerle en ese momento", "Culpa a un departamento diferente por la limitación"] },
  17: { text: "Dos clientes le contactan simultáneamente con problemas urgentes. ¿Cómo gestiona esto?", options: ["Intenta atender a ambos en tiempo real simultáneamente a través de dos canales", "Reconoce ambos de inmediato, establece un cronograma de respuesta realista para cada uno y prioriza según la gravedad", "Pide al cliente menos urgente que vuelva a llamar cuando esté libre", "Escala ambos a un gerente de inmediato"] },
  18: { text: "Un cliente está enojado por la velocidad de resolución y exige acción inmediata. ¿Cuál es la mejor respuesta?", options: ["Le dice que tenga paciencia — las buenas resoluciones llevan tiempo", "Explica claramente qué acción está tomando en este momento y da un período de tiempo realista y específico para la próxima actualización", "Escala de inmediato para sacarle de su cola", "Ofrece compensación económica sin discutir más la situación"] },
  // Communication (9)
  19: { text: "Un cliente hace una pregunta cuya respuesta no sabe. ¿Cuál es la mejor respuesta?", options: ["Proporciona su mejor conjetura con confianza para que se sienta ayudado de inmediato", "Dice 'No sé' y termina la interacción", "'Buena pregunta — déjeme encontrar la respuesta correcta y le contactaré en [plazo realista específico].'", "Transfiere a otro agente sin proporcionar contexto a ninguna de las partes"] },
  20: { text: "Un cliente usa terminología técnica con la que no está familiarizado/a. ¿Cuál es la mejor acción?", options: ["Finge que entiende y continúa la interacción", "Hace una pregunta aclaratoria: '¿Podría ayudarme a entender qué quiere decir con [término] para poder darle la ayuda más precisa?'", "Transfiere de inmediato a un especialista técnico", "Pide al cliente que simplifique su lenguaje antes de continuar"] },
  21: { text: "¿Cuál respuesta escrita cierra mejor una interacción de atención al cliente?", options: ["'Por favor háganos saber si hay algo más.'", "'Su problema ha sido registrado en nuestro sistema.'", "'He resuelto [el problema específico]. Si tiene alguna pregunta sobre la solución o surge algo más, no dude en contactarnos.'", "'Gracias por contactarnos hoy.'"] },
  22: { text: "Un cliente responde con enojo a una resolución que ofreció. ¿Cuál es el mejor enfoque de comunicación?", options: ["Iguala su energía para demostrar que lo toma en serio", "Usa un tono calmado y empático y pregunta qué resultado le haría sentir que el problema está completamente resuelto", "Repite su resolución original de manera más firme y clara", "Escala sin ninguna comunicación adicional de su parte"] },
  23: { text: "Necesita dar una mala noticia a un cliente — su pedido ha sido cancelado. ¿Cuál es el mejor enfoque?", options: ["Comienza con la mala noticia de inmediato para respetar su tiempo", "Entierra la noticia en un mensaje largo para suavizar el impacto", "Reconoce su experiencia, entrega la noticia honesta y claramente, luego se centra de inmediato en lo que puede hacer para ayudar", "Retrasa decírselo y ve si la situación se resuelve por sí sola primero"] },
  24: { text: "¿Cuándo es apropiado usar jerga técnica con un cliente?", options: ["Siempre — establece credibilidad y experiencia", "Nunca — siempre es desagradable para los clientes", "Solo cuando el cliente ha usado lenguaje técnico él mismo, indicando comodidad con él", "Solo cuando necesita terminar la interacción rápidamente"] },
  25: { text: "Está gestionando un chat en vivo con múltiples clientes y uno tarda varios minutos en responder. ¿Cuál es la mejor acción?", options: ["Cierra el chat después de dos minutos de inactividad", "Se centra completamente en los clientes que responden y vuelve cuando el silencioso envíe un mensaje", "Envía un breve mensaje verificando que siguen ahí y confirmando que está listo/a cuando lo estén", "Escala después de un minuto de silencio"] },
  26: { text: "Un cliente llama con una queja sobre la que ya envió un correo electrónico. ¿Qué debe hacer primero?", options: ["Pide que repita la historia completa desde el principio", "Consulta su correo electrónico antes de que terminen de explicar para poder hacer referencia a su contacto previo y evitar que se repitan", "Transfiere a quien gestionó el correo electrónico original", "Pregunta por qué está llamando cuando ya envió un correo electrónico"] },
  27: { text: "Explicó una resolución, pero el cliente no la entendió y volvió a hacer la misma pregunta. ¿Cuál es la mejor respuesta?", options: ["Copia y pega su respuesta anterior palabra por palabra", "Se disculpa e intenta una explicación diferente o un formato diferente que pueda funcionar mejor para ellos", "Pregunta por qué no está entendiendo su respuesta", "Transfiere a un agente sénior que pueda explicarlo mejor"] },
  // Patience (8)
  28: { text: "Un cliente está explicando su problema muy lentamente y con detalle excesivo. ¿Cuál es el mejor enfoque?", options: ["Le interrumpe cortésmente y le pide que vaya al grano rápidamente", "Deja que termine — puede estar compartiendo contexto que resulte ser importante — y luego resume lo que entendió", "Realiza varias tareas mientras hablan para usar su tiempo de forma eficiente", "Le pide que envíe un correo electrónico para que pueda estructurar sus ideas primero"] },
  29: { text: "Un cliente le contacta por tercera vez sobre un problema recurrente. Está visiblemente frustrado. ¿Cómo aborda esto de manera diferente?", options: ["Sigue el proceso de resolución estándar — es el procedimiento correcto", "Reconoce explícitamente el patrón: 'Puedo ver que esto ha ocurrido antes y eso es inaceptable. Voy a asegurarme personalmente de que esto quede resuelto hoy.'", "Ofrece un reembolso de inmediato para romper el ciclo sin investigación más profunda", "Pide al cliente que tenga paciencia mientras el sistema subyacente se pone al día"] },
  30: { text: "Un cliente usa lenguaje grosero o profano. ¿Cuál es la mejor respuesta?", options: ["Usa un lenguaje igualmente asertivo para que sepa que no se deja intimidar", "Termina la interacción de inmediato", "Se mantiene tranquilo/a, reconoce su frustración, trabaja para resolver el problema subyacente y, si el lenguaje continúa, explica claramente lo que necesita para continuar la conversación de manera productiva", "Ignora el lenguaje por completo y continúa como si no hubiera ocurrido"] },
  31: { text: "Un cliente hace una pregunta que parece simple pero tiene una respuesta compleja y matizada. ¿Qué hace?", options: ["Da la respuesta rápida y simplificada para ahorrar tiempo a ambas partes", "Se toma el tiempo necesario para dar una respuesta completa y precisa, aunque lleve más tiempo", "Les dirige a las FAQ o base de conocimiento", "Transfiere a un especialista para evitar dar una respuesta incompleta"] },
  32: { text: "Hay muchos clientes esperando, pero el cliente actual todavía está hablando y su problema aún no está resuelto. ¿Cuál es la acción más apropiada?", options: ["Apresura al cliente actual hacia una conclusión", "Da al cliente actual el tiempo que necesita para sentirse resuelto — luego busca formas de atender la cola de manera más eficiente después", "Pone al cliente en espera sin avisarle", "Lo transfiere a un colega a mitad de la interacción"] },
  33: { text: "Un cliente hace la misma pregunta aclaratoria varias veces porque no está entendiendo sus respuestas. ¿Cuál es la mejor acción?", options: ["Copia y pega su respuesta anterior — necesita leerla con más atención", "Se disculpa e intenta un formato o enfoque de explicación diferente que pueda adaptarse mejor a ellos", "Pregunta por qué sigue haciendo la misma pregunta", "Transfiere a un agente sénior para manejar el malentendido"] },
  34: { text: "Un cliente está desahogándose extensamente antes de llegar a su solicitud real. ¿Cuál es el mejor enfoque?", options: ["Le interrumpe cortésmente después de 30 segundos para redirigir al problema práctico", "Deja que termine, luego responde al contenido emocional antes de pasar a la pregunta práctica", "Le pregunta repetidamente que se centre en el problema específico", "Lo pone en espera hasta que se haya calmado"] },
  35: { text: "Después de una interacción larga y difícil, el cliente le agradece sinceramente y dice que ha restaurado su confianza en su empresa. ¿Cuál es la respuesta más efectiva?", options: ["Dice 'No hay problema' y da por concluida la interacción", "Reconoce que se alegra de haber podido ayudar, confirma brevemente los próximos pasos y les desea lo mejor genuinamente", "Pregunta si estarían dispuestos a dejar una reseña positiva", "Les ofrece un descuento en su próxima compra como recompensa por su paciencia"] },
};
