export const TRANSLATION_STATUS = "draft" as const;

export const EI_QUESTIONS_ES: Record<number, { text: string }> = {
  1:  { text: "Normalmente puedo nombrar la emoción que estoy experimentando mientras ocurre." },
  2:  { text: "Noto cómo mi estado de ánimo afecta la forma en que me comunico con los demás." },
  3:  { text: "Entiendo los desencadenantes personales que pueden ponerme a la defensiva." },
  4:  { text: "A menudo actúo sin notar cómo me siento hasta después." },
  5:  { text: "Puedo reconocer cuando el estrés está afectando mi juicio." },
  6:  { text: "Busco retroalimentación para entender cómo me perciben los demás." },
  7:  { text: "Puedo separar los hechos de mi interpretación emocional de una situación." },
  8:  { text: "Rara vez entiendo por qué ciertas situaciones me molestan." },
  9:  { text: "Puedo mantenerme suficientemente tranquilo/a para responder con calma durante una situación de tensión." },
  10: { text: "Cuando me siento frustrado/a, hago una pausa antes de hablar o actuar." },
  11: { text: "Me recupero rápidamente después de una interacción difícil." },
  12: { text: "Digo cosas de las que luego me arrepiento cuando la presión es alta." },
  13: { text: "Puedo ajustar mi comportamiento cuando mi primera reacción sería contraproducente." },
  14: { text: "Manejo los cambios inesperados sin perder el enfoque." },
  15: { text: "Gestiono los conflictos sin escalarlos innecesariamente." },
  16: { text: "Los pequeños contratiempos suelen alterar mi estado de ánimo por el resto del día." },
  17: { text: "Me mantengo comprometido/a con los objetivos importantes incluso cuando el progreso es lento." },
  18: { text: "Puedo encontrar significado en el trabajo que es desafiante o repetitivo." },
  19: { text: "Establezco estándares personales que me impulsan a mejorar." },
  20: { text: "Pierdo energía rápidamente cuando el reconocimiento no es inmediato." },
  21: { text: "Busco lecciones cuando algo no sale como se planeó." },
  22: { text: "Me mantengo optimista mientras soy realista sobre los obstáculos." },
  23: { text: "Tomo la iniciativa sin esperar que me digan cada próximo paso." },
  24: { text: "Evito objetivos difíciles si el éxito es incierto." },
  25: { text: "Normalmente puedo percibir cuando alguien se siente incómodo aunque no lo diga." },
  26: { text: "Escucho lo que las personas sienten además de lo que dicen." },
  27: { text: "Considero cómo las decisiones pueden afectar a personas con diferentes necesidades." },
  28: { text: "Me resulta difícil entender por qué las personas reaccionan de manera diferente a como yo lo hago." },
  29: { text: "Hago preguntas antes de asumir que entiendo la perspectiva de otra persona." },
  30: { text: "Noto cuando alguien necesita apoyo, espacio o ánimo." },
  31: { text: "Puedo estar en desacuerdo con alguien y aun así respetar su experiencia." },
  32: { text: "Cuando las personas están emotivas, tiendo a desestimar sus preocupaciones." },
  33: { text: "Genero confianza comunicándome de manera clara y coherente." },
  34: { text: "Puedo adaptar mi estilo de comunicación a diferentes personas." },
  35: { text: "Ayudo a los grupos a avanzar hacia un acuerdo durante los desacuerdos." },
  36: { text: "Evito conversaciones importantes cuando pueden volverse incómodas." },
  37: { text: "Creo un entorno donde las personas se sienten seguras para compartir ideas y preocupaciones." },
  38: { text: "Me cuesta mantener relaciones cuando el trabajo se pone difícil." },
  39: { text: "Reconozco y aprovecho los puntos fuertes de los demás en la colaboración." },
  40: { text: "Cuando noto que alguien está pasando por un momento difícil, hago un esfuerzo por verificar cómo está." },
};
