export const TRANSLATION_STATUS = "draft" as const;

export const IE_QUESTIONS_ES: Record<number, { text: string; options: [string, string, string, string] }> = {
  // Honesty (8)
  1:  { text: "Cometió un error en un informe que ya fue compartido con la alta dirección. ¿Qué hace?", options: ["Espera que nadie lo note y lo corrige silenciosamente en la próxima versión", "Informa a las partes relevantes de inmediato, corrige el error y explica lo que ocurrió", "Espera a ver si alguien lo señala antes de tomar cualquier acción", "Pide a un colega de confianza que lo señale anónimamente en su nombre"] },
  2:  { text: "Su gerente solicita una actualización del estado de un proyecto, pero el proyecto está retrasado. ¿Qué dice?", options: ["Informa que las cosas están 'en términos generales en camino' para evitar mayor escrutinio", "Da una actualización honesta sobre el estado real, las razones del retraso y su plan para abordarlo", "Proporciona una actualización vaga que no se compromete a nada específico", "Dice que enviará una actualización escrita más tarde y aplaza la conversación"] },
  3:  { text: "Durante una presentación de ventas, un cliente pregunta sobre una función del producto que aún no existe. ¿Qué hace?", options: ["Confirma que la función existe — probablemente estará lista antes de que la necesiten", "Dice que está 'en desarrollo' sin aclarar cuándo o si estará disponible", "Es honesto/a: la función aún no existe, comparte lo que está en la hoja de ruta y deja que decidan con información precisa", "Cambia de tema hábilmente antes de que hagan un seguimiento"] },
  4:  { text: "Está en fuerte desacuerdo con una conclusión clave en el informe de un colega del que claramente está orgulloso. ¿Qué hace?", options: ["Le dice que el informe es excelente para preservar la relación", "Plantea su preocupación en privado y de forma constructiva, con evidencia clara para respaldar su punto de vista", "No dice nada a menos que alguien más plantee el problema primero", "Plantea su preocupación públicamente en una reunión del equipo para asegurarse de que sea escuchada"] },
  5:  { text: "Le piden que estime el tiempo de finalización de un proyecto y genuinamente no está seguro/a. ¿Qué dice?", options: ["Da una estimación específica y confiada aunque sin una base sólida para ello", "Proporciona un rango realista basado en lo que sabe y señala claramente las incertidumbres clave", "Dice que no puede estimarse sin más información y se niega a comprometerse", "Da el plazo que cree que su gerente quiere escuchar"] },
  6:  { text: "Un cliente pide su opinión honesta sobre el producto de un competidor. Sabe que en realidad es bastante bueno. ¿Qué dice?", options: ["Descarta el producto del competidor sin ningún análisis justo", "Da una evaluación honesta y equilibrada — reconoce dónde el competidor rinde bien y aclara dónde su solución agrega más valor para sus necesidades específicas", "Dice que la política de la empresa le impide comentar sobre los competidores", "Comparte una historia negativa engañosa sobre el competidor sin evidencia"] },
  7:  { text: "Está completando su hoja de horas y nota que facturó más horas a un proyecto del cliente de las que realmente trabajó. ¿Qué hace?", options: ["Lo deja así — la diferencia es menor y se compensará con el tiempo", "Corrige la hoja de horas para reflejar las horas trabajadas con precisión", "Registra las horas planificadas como se tenía previsto originalmente y lo compensa en el próximo proyecto", "Pregunta informalmente a un gerente si es aceptable dejarlo como está"] },
  8:  { text: "Un colega comparte algo personal con usted en confidencia. Luego alguien más le pregunta si sabe algo al respecto. ¿Qué hace?", options: ["Comparte la información — su colega debería haber tenido más cuidado sobre con quién lo compartía", "Mantiene la confidencia: le dice a la otra persona que no sabe nada que pueda compartir", "Comparte una versión de la información que considera menos sensible", "Pide permiso a su colega antes de responder a la otra persona"] },
  // Accountability (8)
  9:  { text: "Un proyecto que lideró no alcanzó sus objetivos. Su equipo pregunta qué ocurrió. ¿Qué hace?", options: ["Atribuye el fracaso principalmente a factores externos y circunstancias fuera de su control", "Asume la responsabilidad honesta de lo que fue responsable, reconoce lo que no funcionó y comparte lo que aprendió", "Identifica qué miembro del equipo contribuyó más al fracaso", "Dice que preparará un informe detallado pero lo aplaza indefinidamente"] },
  10: { text: "Dio a un colega un consejo incorrecto que directamente le causó cometer un error significativo. ¿Cuál es la respuesta más apropiada?", options: ["Permitir que el colega asuma la responsabilidad — en última instancia él/ella tomó la decisión final", "Reconocer claramente que su consejo fue incorrecto y tomar medidas activas para ayudar a corregir la situación", "Ofrecer asesoramiento para solucionar el error sin mencionar su papel en causarlo", "Revisar su propio proceso de asesoramiento en silencio sin decirle al colega lo que ocurrió"] },
  11: { text: "Se comprometió a asistir a una reunión importante pero se olvidó y no asistió en absoluto. ¿Qué hace?", options: ["Espera a ver si alguien le contacta al respecto", "Se disculpa con las personas relevantes, averigua qué se perdió y asume la responsabilidad de las acciones de seguimiento necesarias", "Dice a las personas que estaba ocupado con un asunto urgente de un cliente", "Se disculpa solo si alguien le confronta directamente por su ausencia"] },
  12: { text: "Descubre que un proceso que gestiona ha estado produciendo errores durante varias semanas. ¿Cómo responde?", options: ["Corrige los errores silenciosamente sin informar a su gerente o a los interesados", "Informa a su gerente, cuantifica el alcance del problema, corrige el proceso e implementa una verificación para prevenir la recurrencia", "Continúa con el proceso existente y revisa los errores en el próximo informe mensual programado", "Investiga quién configuró el proceso original y les asigna la responsabilidad"] },
  13: { text: "Le piden que asuma una tarea que está significativamente fuera de su área de experiencia. ¿Qué hace?", options: ["Acepta sin decirle a nadie sobre sus limitaciones y espera poder solucionarlo", "Declina — no es su área y no debería arriesgar su reputación", "Acepta siendo honesto/a sobre sus limitaciones e identifica proactivamente dónde necesitará apoyo o orientación", "Acepta la tarea pero externaliza las partes desconocidas sin informar a su gerente"] },
  14: { text: "Su gerente elogia un trabajo en el que un colega colaboró significativamente. ¿Qué hace?", options: ["Acepta el elogio — aun así hizo una contribución real", "Reconoce la contribución de su colega de manera clara y precisa ante su gerente", "No dice nada a su colega pero agradece a su gerente en privado", "Pide a su gerente que reconozca a ambos públicamente la próxima vez"] },
  15: { text: "Está quedando atrás en un compromiso y está quedando claro que no cumplirá con el plazo. ¿Cuál es la respuesta correcta?", options: ["Continúa trabajando y trata de ponerse al día antes de que alguien lo note", "Informa al interesado relevante de inmediato, explica lo que ocurrió y acuerda un plan revisado realista", "Entrega lo que haya completado para la fecha límite aunque sea sustancialmente incompleto", "Pide a un colega que entregue algo en su nombre"] },
  16: { text: "Una decisión del equipo de la que fue parte resultó ser una decisión equivocada. Tenía reservas pero no las planteó en ese momento. ¿Cuál es su responsabilidad?", options: ["Ninguna — no tomó la decisión final", "Comparte algo de responsabilidad y debe reconocer que podría haber planteado sus preocupaciones en ese momento", "La responsabilidad total recae en quien tomó la decisión final", "Ahora debe centrarse en identificar quién debería haber señalado el problema antes de que se tomara la decisión"] },
  // Ethics (7)
  17: { text: "Descubre que un colega ha estado presentando informes de gastos inflados. ¿Qué hace?", options: ["Lo ignora — no es su responsabilidad y no quiere crear conflictos", "Lo encubre — es un amigo y los montos no son grandes", "Lo plantea a través del canal interno apropiado, como su gerente o recursos humanos", "Lo confronta públicamente frente al equipo para desalentar comportamientos similares"] },
  18: { text: "Su gerente le presiona para que tergiverse datos en un informe del cliente para que los resultados parezcan mejores de lo que son. ¿Qué hace?", options: ["Sigue las instrucciones de su gerente — tiene autoridad y responsabilidad sobre el informe", "Plantea su preocupación directamente con su gerente y explica por qué no puede tergiversar los datos", "Altera los datos pero añade una advertencia sutil en el apéndice", "Lo hace esta vez y plantea el problema a través de otro canal después"] },
  19: { text: "Un cliente le ofrece un regalo personal valorado en diez veces el límite aceptado de regalos de su empresa. ¿Qué hace?", options: ["Lo acepta — refleja una relación con el cliente sólida y valiosa", "Lo acepta pero no lo divulga a nadie en su empresa", "Lo declina cortésmente, hace referencia a la política de regalos de su empresa y le agradece genuinamente el gesto", "Lo acepta y lo dona a una organización benéfica para no beneficiarse personalmente"] },
  20: { text: "Se le ofrece acceso al documento de precios confidencial de un competidor por parte de alguien que afirma que le fue compartido de manera no oficial. ¿Qué hace?", options: ["Lo usa — proporciona una ventaja competitiva legítima para su empresa", "Declina usarlo e informa la situación a su gerente", "Lo usa confidencialmente solo dentro de su equipo inmediato", "Pregunta a su gerente si es permisible usarlo antes de tomar una decisión"] },
  21: { text: "Le piden que escriba una referencia profesional para un colega que sabe que ha tenido un bajo rendimiento. ¿Qué hace?", options: ["Escribe una referencia positiva sólida — la lealtad y la colegialidad son lo primero", "Declina escribir la referencia o escribe una que refleje honesta y justamente su experiencia profesional con ellos", "Escribe una referencia deliberadamente vaga que ni confirma ni niega su desempeño", "Escribe exactamente lo que le han pedido que incluya"] },
  22: { text: "Nota que los datos de un segmento minoritario están siendo excluidos de un análisis de una manera que cambia materialmente las conclusiones. ¿Qué hace?", options: ["Asume que fue un descuido accidental y no dice nada", "Plantea el problema directamente con la persona responsable del análisis", "Incluye los datos usted mismo en un documento separado sin decírselo a nadie", "Añade una breve nota al respecto en el apéndice, alejada de los hallazgos principales"] },
  23: { text: "Está bajo presión de tiempo y se da cuenta de que saltarse una verificación de seguridad o cumplimiento le ahorraría varias horas. ¿Qué hace?", options: ["Se salta el paso — es poco probable que una sola instancia cause daño real", "Completa la verificación completa independientemente de la presión de tiempo", "Se la salta esta vez pero lo señala en sus notas como algo que retomar más tarde", "Pide a un colega junior que complete la verificación para ahorrar su tiempo"] },
  // Trustworthiness (7)
  24: { text: "Acepta completar una tarea para el jueves, pero para el miércoles sabe que no estará lista hasta el viernes. ¿Qué hace?", options: ["Trabaja toda la noche y espera entregar para el jueves sin decírselo a nadie", "Informa a la parte relevante el miércoles, explica la razón del retraso y acuerda un nuevo plazo", "Entrega el trabajo incompleto el jueves para cumplir técnicamente con el plazo", "Pide a un colega que lo cubra sin informar al interesado"] },
  25: { text: "Un colega comparte un borrador confidencial con usted y le pide que no lo distribuya. Accidentalmente lo reenvía a la persona equivocada. ¿Qué hace?", options: ["Finge que no ocurrió y espera que la otra persona no lo mencione", "Informa inmediatamente a su colega y al destinatario no deseado y toma medidas para minimizar el impacto", "Pide al destinatario no deseado que lo elimine y no le dice nada a su colega", "Espera a ver si alguna de las partes lo plantea antes de tomar cualquier acción"] },
  26: { text: "Acordó ser mentor de un nuevo miembro del equipo, pero su carga de trabajo se ha vuelto abrumadora. ¿Cuál es la acción más confiable?", options: ["Continúa como se planeó pero se salta las sesiones siempre que surjan otras prioridades", "Es honesto/a sobre su disponibilidad, renegocia el compromiso a algo realista o encuentra un mentor alternativo adecuado", "Envía recursos y materiales de lectura por correo electrónico como sustituto de las reuniones", "Detiene el programa de mentoría sin ninguna explicación"] },
  27: { text: "Recibe información no confirmada de que un proyecto probablemente será cancelado. Un colega que ha estado trabajando duro en él le pregunta directamente si ha oído algo. ¿Qué hace?", options: ["Comparte todo lo que escuchó íntegramente, aunque no esté confirmado", "Miente y dice que no ha oído nada para protegerlo de ansiedad innecesaria", "Le dice honestamente que ha escuchado algo, pero que no está confirmado, y le sugiere que hable directamente con la persona relevante", "Cambia de tema y evita responder la pregunta"] },
  28: { text: "Un equipo depende de su análisis semanal para tomar decisiones clave. Sabe que la metodología tiene un defecto pero corregirlo requeriría un tiempo considerable. ¿Qué hace?", options: ["Continúa usando la metodología defectuosa — el análisis es suficientemente bueno para propósitos prácticos", "Señala el defecto de inmediato, anota el impacto potencial en resultados anteriores y lo corrige lo más rápidamente posible", "Lo corrige silenciosamente sin informar a nadie de que la metodología tenía un defecto", "Planea abordarlo en la próxima versión sin señalar el problema actual"] },
  29: { text: "Le piden que se comprometa con un plazo de entrega del que genuinamente no está seguro/a de poder cumplir. ¿Cuál es la respuesta más confiable?", options: ["Se compromete con el plazo solicitado para demostrar voluntad e intención positiva", "Proporciona una evaluación honesta de lo que puede entregar de forma realista y para cuándo, con los riesgos o advertencias establecidos claramente", "Se compromete con el plazo y escala si no lo cumple", "Dice que 'hará lo mejor que pueda' sin comprometerse a nada específico"] },
  30: { text: "Se da cuenta de que ha estado tomando involuntariamente el crédito por una idea que se originó con un colega durante una discusión. ¿Qué hace?", options: ["Continúa porque la situación ya se ha desarrollado y la atribución ahora no está clara", "Aclara proactivamente a los interesados relevantes que la idea se originó con su colega", "Le dice a su colega en privado pero no corrige el registro públicamente", "Ofrece a su colega un papel más importante en el proyecto como compensación indirecta"] },
};
