export const TRANSLATION_STATUS = "draft" as const;

export const LEADERSHIP_QUESTIONS_ES: Record<number, {
  text: string;
  options: [string, string, string, string, string, string];
}> = {
  1:  { text: "El equipo no está seguro sobre la dirección de una nueva iniciativa. ¿Qué hace primero?", options: ["Explica una dirección futura clara y por qué es importante.", "Se reúne con cada persona para entender sus necesidades de desarrollo.", "Crea tranquilidad y reduce la tensión en todo el grupo.", "Invita al equipo a dar forma al plan juntos.", "Establece un punto de referencia ambicioso y modela el ritmo.", "Define roles, plazos y acciones requeridas de inmediato."] },
  2:  { text: "Un miembro del equipo capaz está teniendo bajo rendimiento. Su primera respuesta es:", options: ["Reconectar su trabajo con la misión más amplia.", "Guiarle a través de sus objetivos, obstáculos y habilidades.", "Verificar si la fricción personal o del equipo le está afectando.", "Pedir su opinión y acordar los próximos pasos juntos.", "Mostrar cómo se ve una ejecución sólida y elevar el listón.", "Dar expectativas directas y un cronograma firme para la mejora."] },
  3:  { text: "Dos departamentos no están de acuerdo en las prioridades. Lo más probable es que usted:", options: ["Aclare el destino compartido que ambos grupos deben apoyar.", "Ayude a las personas clave a entender qué pueden aprender del conflicto.", "Repare la confianza antes de presionar por una decisión.", "Facilite una conversación de toma de decisiones con ambas partes.", "Centre a todos en el resultado medible y la velocidad.", "Tome la decisión y exija alineación."] },
  4:  { text: "Al lanzar un proyecto difícil, prefiere:", options: ["Describir el destino y dejar que las personas encuentren los caminos.", "Asignar roles de estiramiento que ayuden a las personas a desarrollarse.", "Construir confianza y conexión antes de que aumente la presión.", "Co-crear el ritmo operativo con el equipo.", "Establecer estándares exigentes y trabajar al frente.", "Crear un plan ajustado con elementos no negociables claros."] },
  5:  { text: "Un plazo está en riesgo. ¿Qué estilo le resulta más natural?", options: ["Reenfoca al equipo en el resultado importante.", "Ayuda a quienes están bloqueados a aprender cómo resolver problemas similares más rápido.", "Mantiene la moral estable para que las personas no se cierren.", "Pregunta al equipo el plan de recuperación más rápido y realista.", "Aumenta el tempo y demuestra urgencia personalmente.", "Toma decisiones rápidas y dirige la ejecución."] },
  6:  { text: "Un nuevo empleado se une a su equipo. Lo más probable es que usted:", options: ["Muestre cómo su rol encaja en el futuro de la organización.", "Construya un plan de desarrollo con ellos.", "Les ayude a sentirse bienvenidos y conectados.", "Les invite a las discusiones del equipo de manera temprana.", "Dé ejemplos del trabajo excelente que deben alcanzar.", "Proporcione expectativas y reglas precisas."] },
  7:  { text: "Su equipo necesita mejorar la calidad. Comienza por:", options: ["Explicar el estándar de calidad como parte de una ambición más grande.", "Desarrollar las habilidades de las que depende la calidad.", "Crear seguridad para discutir los errores abiertamente.", "Pedir al equipo que diagnostique las causas raíz.", "Elevar el estándar y revisar el trabajo de cerca.", "Exigir un proceso de calidad más estricto."] },
  8:  { text: "En las reuniones, su contribución más fuerte suele ser:", options: ["Ayudar a las personas a ver el panorama general.", "Sacar oportunidades de aprendizaje y desarrollo.", "Mantener el tono constructivo y respetuoso.", "Asegurarse de que todas las voces relevantes sean escuchadas.", "Impulsar un resultado claro y altos estándares.", "Dirigir las decisiones y asignar elementos de acción."] },
  9:  { text: "Un equipo se ha vuelto demasiado cómodo. Responde:", options: ["Pintando un próximo capítulo convincente.", "Ayudando a las personas a identificar objetivos de crecimiento.", "Fortaleciendo las relaciones para que el cambio se sienta más seguro.", "Preguntando al grupo cómo debería verse la mejora.", "Estableciendo un ritmo más exigente.", "Cambiando las expectativas y exigiendo cumplimiento."] },
  10: { text: "Una crisis ocurre con poco aviso. Su primer instinto es:", options: ["Recordar a las personas el objetivo principal.", "Orientar a las personas clave en las demandas desconocidas.", "Mantener al grupo tranquilo y conectado.", "Recopilar rápidamente aportaciones de quienes están más cerca del problema.", "Moverse rápidamente y modelar un enfoque intenso.", "Tomar el mando y dar instrucciones claras."] },
  11: { text: "Recibe una idea audaz de un miembro junior del equipo. Usted:", options: ["La conecta con la dirección estratégica.", "Le ayuda a refinarla y presentarla.", "Le anima y protege la seguridad psicológica.", "Invita al equipo a evaluarla abiertamente.", "La pone a prueba contra un estándar de alto rendimiento.", "Decide rápidamente si debería continuar."] },
  12: { text: "Al dar retroalimentación, tiende a enfatizar:", options: ["Cómo el trabajo apoya la dirección futura.", "Cómo la persona puede crecer a partir de él.", "Cómo preservar la confianza y la seguridad.", "Cómo la retroalimentación puede convertirse en una conversación bidireccional.", "Cómo el trabajo se compara con la excelencia.", "Qué debe cambiar de inmediato."] },
  13: { text: "Un interesado sénior pide un plan que usted no apoya completamente. Usted:", options: ["Reencuadra en torno a la dirección a largo plazo.", "Lo usa como un momento de orientación para el equipo.", "Gestiona las relaciones cuidadosamente para reducir la fricción.", "Involucra a las personas clave en el proceso de decisión.", "Se centra en ejecutar la versión más sólida posible.", "Alinea al equipo y actúa rápidamente."] },
  14: { text: "Su equipo está dividido después de un cambio difícil. Usted:", options: ["Explica adónde lleva el cambio a la organización.", "Ayuda a las personas a procesar y adaptarse.", "Prioriza reconstruir la confianza y el sentido de pertenencia.", "Crea foros para que las personas participen en las soluciones.", "Establece rápidamente nuevas expectativas de rendimiento.", "Aclara las nuevas reglas y las hace cumplir."] },
  15: { text: "Al delegar, es más probable que:", options: ["Describa el resultado y el propósito estratégico.", "Haga coincidir la tarea con las necesidades de desarrollo de alguien.", "Considere el equilibrio de relaciones y carga de trabajo.", "Deje al grupo decidir la propiedad cuando sea posible.", "Se la dé al mejor ejecutante para mayor velocidad.", "La asigne directamente con requisitos exactos."] },
  16: { text: "El equipo no alcanza un objetivo importante. Se centra en:", options: ["Reconectar a todos con el objetivo más amplio.", "Convertir el fracaso en un plan de aprendizaje.", "Mantener la moral intacta antes del próximo esfuerzo.", "Revisar causas y soluciones como grupo.", "Elevar la disciplina y la intensidad del rendimiento.", "Acción correctiva y responsabilidad."] },
  17: { text: "Un compañero de equipo quiere más responsabilidad. Usted responde:", options: ["Mostrando cómo una mayor propiedad apoya la misión.", "Creando un camino de crecimiento paso a paso.", "Animándole y verificando sus necesidades de apoyo.", "Discutiendo las opciones con el equipo si les afecta.", "Dándole una asignación de estiramiento difícil.", "Asignando responsabilidad con reglas claras."] },
  18: { text: "Necesita innovación del grupo. Usted:", options: ["Establece una visión audaz que abre nuevas posibilidades.", "Orienta a las personas para que desarrollen confianza en nuevas habilidades.", "Hace que el entorno sea seguro para la experimentación.", "Dirige la ideación colaborativa y la votación.", "Impulsa prototipos rápidos y altos estándares.", "Define el problema y exige propuestas rápidas."] },
  19: { text: "Cuando el rendimiento es sólido, por lo general:", options: ["Señala el próximo horizonte estratégico.", "Pregunta qué quieren aprender a continuación.", "Celebra al equipo y fortalece los vínculos.", "Invita a reflexionar sobre lo que funcionó.", "Eleva el listón de nuevo.", "Fija el proceso que produjo los resultados."] },
  20: { text: "Si las personas resisten su decisión, tiende a:", options: ["Explicar el propósito y el valor futuro.", "Explorar qué revela la resistencia sobre las necesidades de desarrollo.", "Escuchar las preocupaciones y proteger las relaciones.", "Reabrir la discusión si la participación mejoraría el compromiso.", "Refocalizarse en los resultados y las expectativas.", "Mantener la posición y exigir compromiso."] },
  21: { text: "Una decisión compleja no tiene una respuesta obvia. Usted:", options: ["Elige el camino más alineado con la dirección futura.", "Usa la decisión para desarrollar el juicio del equipo.", "Reduce la ansiedad y ayuda a las personas a mantenerse conectadas.", "Facilita la aportación de las personas adecuadas.", "Usa datos de rendimiento y referencias de mejores prácticas.", "Toma la decisión y la comunica claramente."] },
  22: { text: "Su equipo tiene poca confianza. Usted:", options: ["Muestra un camino convincente a seguir.", "Orienta a las personas a través de pasos de progreso alcanzables.", "Se centra en el estímulo y el apoyo emocional.", "Pregunta al grupo qué reconstruiría la confianza.", "Establece un estándar visible y demuestra el éxito.", "Crea estructura para que las personas sepan exactamente qué hacer."] },
  23: { text: "Un proceso es ineficiente. Usted:", options: ["Vincula las mejoras a un estado futuro más sólido.", "Desarrolla a las personas que pueden mejorar el proceso.", "Se asegura de que los cambios no dañen la confianza.", "Pide a los usuarios del proceso que lo rediseñen.", "Reemplaza los pasos débiles con un estándar de alto rendimiento.", "Exige el nuevo proceso."] },
  24: { text: "Durante las reuniones individuales, generalmente dedica más tiempo a:", options: ["Propósito, dirección y prioridades.", "Objetivos, retroalimentación y desarrollo.", "Bienestar, confianza y relaciones.", "Ideas, preocupaciones y decisiones compartidas.", "Resultado, estándares y ritmo.", "Expectativas, responsabilidad y obstáculos."] },
  25: { text: "Cuando un compañero de equipo comete un error visible, usted:", options: ["Le reconecta con el aspecto del éxito.", "Orienta la lección y el próximo comportamiento.", "Protege la dignidad y reduce la vergüenza.", "Invita al equipo a mejorar el sistema.", "Espera una corrección rápida y un estándar más alto.", "Lo aborda directamente y establece consecuencias si es necesario."] },
  26: { text: "Prefiere que los equipos le experimenten como:", options: ["Claro sobre la dirección y el significado.", "Invertido en su crecimiento.", "Solidario y centrado en las relaciones.", "Colaborativo e inclusivo.", "Exigente e impulsado por la excelencia.", "Decisivo y directivo."] },
  27: { text: "Cuando las prioridades compiten, usted:", options: ["Elige en función de la visión a largo plazo.", "Considera qué elección desarrolla la capacidad.", "Considera el impacto en la cohesión del equipo.", "Reúne a los interesados para evaluar las compensaciones.", "Elige el camino con el mayor rendimiento medible.", "Establece la prioridad y detiene el debate."] },
  28: { text: "Un miembro del equipo está listo para un ascenso. Usted:", options: ["Conecta el ascenso con las necesidades organizativas futuras.", "Le prepara a través de la orientación y la retroalimentación de estiramiento.", "Construye un amplio apoyo en torno a su transición.", "Recopila aportaciones de personas que trabajan con ellos.", "Evalúa frente a un listón de rendimiento muy alto.", "Aclara las expectativas exactas para el siguiente nivel."] },
  29: { text: "Su forma predeterminada de crear responsabilidad es:", options: ["Alinear a todos con un destino significativo.", "Ayudar a las personas a tener sus propios objetivos de desarrollo.", "Construir confianza para que las personas no oculten problemas.", "Hacer los compromisos visibles para el grupo.", "Hacer un seguimiento estricto del rendimiento frente a los estándares.", "Establecer reglas y consecuencias explícitas."] },
  30: { text: "Al liderar el cambio, se siente más cómodo/a:", options: ["Creando una historia convincente sobre adónde lleva el cambio.", "Ayudando a las personas a desarrollar las capacidades que requiere el cambio.", "Manteniendo el sentido de pertenencia y la estabilidad emocional.", "Dejando que las personas ayuden a dar forma al cambio.", "Moviéndose rápidamente y demostrando el aspecto de la excelencia.", "Dirigiendo el cambio con claridad y autoridad."] },
};
