export const TRANSLATION_STATUS = "draft" as const;

export const MR_QUESTIONS_ES: Record<number, { text: string; options: [string, string, string, string] }> = {
  1:  { text: "El Engranaje A tiene 20 dientes y engrana con el Engranaje B que tiene 60 dientes. Si el Engranaje A gira a 180 RPM, ¿a qué velocidad gira el Engranaje B?", options: ["60 RPM", "90 RPM", "120 RPM", "540 RPM"] },
  2:  { text: "Una palanca tiene su fulcro a 1 m de una carga de 300 N. El brazo de esfuerzo mide 3 m. ¿Qué esfuerzo se necesita para equilibrar la palanca?", options: ["50 N", "75 N", "100 N", "150 N"] },
  3:  { text: "Se usa una polea fija para levantar una carga de 200 N. ¿Qué fuerza debe aplicarse a la cuerda?", options: ["100 N", "200 N", "400 N", "50 N"] },
  4:  { text: "Se usa una polea móvil para levantar una carga de 200 N. ¿Aproximadamente qué fuerza de esfuerzo se requiere?", options: ["200 N", "100 N", "50 N", "400 N"] },
  5:  { text: "El agua fluye por una tubería de radio 4 cm que se estrecha a radio 2 cm. La velocidad en la sección ancha es 1 m/s. ¿Cuál es la velocidad en la sección estrecha?", options: ["2 m/s", "4 m/s", "8 m/s", "0.5 m/s"] },
  6:  { text: "Una viga está apoyada en ambos extremos. Un peso de 600 N cuelga del centro. ¿Cuál es la fuerza de reacción en cada apoyo?", options: ["600 N", "300 N", "200 N", "150 N"] },
  7:  { text: "Se duplica la presión sobre un volumen fijo de gas a temperatura constante. El volumen:", options: ["Se duplica", "Permanece igual", "Se reduce a la mitad", "Se cuadruplica"] },
  8:  { text: "El Engranaje A tiene 15 dientes y engrana con el Engranaje B que tiene 45 dientes. Si el Engranaje A gira en sentido horario, el Engranaje B gira:", options: ["En sentido horario", "En sentido antihorario", "En cualquier dirección", "No gira"] },
  9:  { text: "Un bloque de 50 kg en una superficie sin fricción tiene una fuerza horizontal de 150 N. ¿Cuál es su aceleración?", options: ["2 m/s²", "3 m/s²", "6 m/s²", "7,500 m/s²"] },
  10: { text: "Una rampa mide 5 m de largo y sube 1 m. ¿Qué esfuerzo se necesita para deslizar una carga de 200 N por la rampa (ignorando la fricción)?", options: ["20 N", "40 N", "100 N", "200 N"] },
  11: { text: "Un circuito eléctrico tiene una batería de 12 V y una resistencia de 4 Ω. ¿Cuánta corriente circula?", options: ["48 A", "3 A", "0.33 A", "8 A"] },
  12: { text: "Dos resistencias de 6 Ω cada una están conectadas en paralelo. ¿Cuál es la resistencia total?", options: ["12 Ω", "6 Ω", "3 Ω", "1 Ω"] },
  13: { text: "Un resorte se comprime 0.1 m con una fuerza de 50 N. ¿Cuál es la constante del resorte?", options: ["5 N/m", "50 N/m", "500 N/m", "5,000 N/m"] },
  14: { text: "¿Qué clase de palanca tiene el fulcro entre el esfuerzo y la carga?", options: ["Clase 1", "Clase 2", "Clase 3", "Clase 4"] },
  15: { text: "Una varilla metálica de 2 m de largo se expande 0.02 m al calentarse. ¿Cuál es el aumento porcentual en longitud?", options: ["0.1%", "1%", "2%", "10%"] },
  16: { text: "Un sistema de poleas tiene una ventaja mecánica de 4. Debe levantarse una carga de 400 N. ¿Qué fuerza debe aplicarse?", options: ["400 N", "100 N", "200 N", "1,600 N"] },
  17: { text: "¿Qué material conduce mejor el calor?", options: ["Madera", "Caucho", "Plástico", "Cobre"] },
  18: { text: "Una presión de 500 Pa actúa sobre un área de 2 m². ¿Cuál es la fuerza total?", options: ["250 N", "500 N", "1,000 N", "2,000 N"] },
  19: { text: "El Engranaje A (10 dientes) impulsa el Engranaje B (30 dientes), que impulsa el Engranaje C (15 dientes). El Engranaje A gira a 90 RPM. ¿A qué velocidad gira el Engranaje C?", options: ["30 RPM", "60 RPM", "90 RPM", "180 RPM"] },
  20: { text: "En un sistema hidráulico, un pistón de área 5 cm² se empuja con 100 N. ¿Qué fuerza produce un pistón de área 50 cm²?", options: ["10 N", "100 N", "1,000 N", "500 N"] },
  21: { text: "Un objeto de 10 kg cae desde una altura de 5 m. ¿Cuál es su velocidad justo antes del impacto? (g = 10 m/s²)", options: ["5 m/s", "10 m/s", "50 m/s", "100 m/s"] },
  22: { text: "Un perno requiere un torque de 60 Nm. La llave mide 0.3 m de longitud. ¿Qué fuerza debe aplicarse?", options: ["18 N", "180 N", "200 N", "20 N"] },
  23: { text: "Si el voltaje permanece constante y la resistencia se duplica, la corriente:", options: ["Se duplica", "Permanece igual", "Se reduce a la mitad", "Se cuadruplica"] },
  24: { text: "Una rueda de radio 0.5 m tiene un torque de 30 Nm aplicado. ¿Qué fuerza tangencial produce este torque?", options: ["15 N", "30 N", "60 N", "90 N"] },
  25: { text: "Tres resistencias de 2 Ω, 3 Ω y 5 Ω están conectadas en serie. ¿Cuál es la resistencia total?", options: ["0.97 Ω", "10 Ω", "5 Ω", "3 Ω"] },
  26: { text: "Una caja de 10 kg se mueve a 2 m/s en una cinta transportadora. ¿Cuál es la energía cinética de la caja?", options: ["10 J", "20 J", "40 J", "100 J"] },
  27: { text: "Un contenedor sellado contiene aire a 200 kPa y 300 K. La temperatura sube a 600 K a volumen constante. ¿Cuál es la nueva presión?", options: ["100 kPa", "200 kPa", "400 kPa", "800 kPa"] },
  28: { text: "Un tornillo tiene un paso de 2 mm. ¿Cuántas vueltas completas se necesitan para hundirlo 10 mm en una superficie?", options: ["2", "5", "10", "20"] },
  29: { text: "Un objeto flota en el agua. Esto significa que la densidad promedio del objeto es:", options: ["Mayor que la densidad del agua", "Igual a la densidad del agua", "Menor que la densidad del agua", "No tiene relación con flotar"] },
  30: { text: "Un motor eléctrico de 200 W funciona durante 30 segundos. ¿Cuánta energía consume?", options: ["200 J", "6,000 J", "666 J", "230 J"] },
};
