export const TRANSLATION_STATUS = "draft" as const;

export const PERSONALITY_QUESTIONS_ES: Record<number, { text: string }> = {
  1:  { text: "Disfruto explorar nuevas ideas, métodos o perspectivas." },
  2:  { text: "Siento curiosidad por temas fuera de mi área habitual de trabajo." },
  3:  { text: "Me gusta encontrar enfoques creativos para problemas conocidos." },
  4:  { text: "Prefiero las rutinas con tanta intensidad que evito probar nuevos enfoques." },
  5:  { text: "Noto patrones y posibilidades que otros pueden pasar por alto." },
  6:  { text: "Disfruto aprender habilidades incluso cuando no son inmediatamente necesarias." },
  7:  { text: "Me siento cómodo/a con la ambigüedad mientras una idea se está formando." },
  8:  { text: "Rara vez disfruto las discusiones abstractas o imaginativas." },
  9:  { text: "Planifico mi trabajo cuidadosamente antes de pasar a la ejecución." },
  10: { text: "Cumplo con los compromisos incluso cuando las tareas se vuelven tediosas." },
  11: { text: "Mantengo los detalles importantes organizados y fáciles de encontrar." },
  12: { text: "A menudo dejo las cosas incompletas cuando una tarea pierde impulso." },
  13: { text: "Reviso mi trabajo en busca de precisión antes de considerarlo completo." },
  14: { text: "Gestiono los plazos comenzando con suficiente anticipación para ajustar si es necesario." },
  15: { text: "Prefiero prioridades claras y ejecución estructurada." },
  16: { text: "Con frecuencia subestimo cuánto tiempo llevará el trabajo." },
  17: { text: "Obtengo energía de interactuar con personas durante el día." },
  18: { text: "Me siento cómodo/a tomando la palabra en las discusiones grupales." },
  19: { text: "Tiendo a iniciar conversaciones con personas nuevas." },
  20: { text: "Prefiero quedarme callado/a incluso cuando tengo algo útil que agregar." },
  21: { text: "Aporto entusiasmo visible al trabajo colaborativo." },
  22: { text: "Me resulta natural construir relaciones entre equipos." },
  23: { text: "Me siento cómodo/a tomando el liderazgo en situaciones sociales o grupales." },
  24: { text: "La interacción frecuente me agota tanto que la evito siempre que puedo." },
  25: { text: "Intento entender las necesidades de otras personas antes de emitir juicios." },
  26: { text: "Busco soluciones cooperativas durante los desacuerdos." },
  27: { text: "Soy considerado/a con cómo mis acciones afectan a los demás." },
  28: { text: "Puedo ser brusco/a de maneras que dañan la confianza." },
  29: { text: "Doy el beneficio de la duda a las personas cuando es posible." },
  30: { text: "Estoy dispuesto/a a ayudar a mis colegas incluso cuando no es directamente mi responsabilidad." },
  31: { text: "Manejo los conflictos con respeto por la dignidad de la otra persona." },
  32: { text: "A menudo compito con otros cuando la colaboración funcionaría mejor." },
  33: { text: "Me mantengo tranquilo/a bajo presión y evito el pensamiento catastrófico." },
  34: { text: "Me recupero rápidamente de las decepciones y sigo adelante." },
  35: { text: "Mantengo la estabilidad emocional en períodos de alto estrés o incertidumbre." },
  36: { text: "Los pequeños contratiempos tienden a afectar desproporcionadamente mi estado de ánimo." },
  37: { text: "Puedo separar mis emociones del trabajo cuando las circunstancias lo requieren." },
  38: { text: "Me siento seguro/a incluso cuando las cosas no salen como se esperaba." },
  39: { text: "Encuentro difícil manejar las críticas sin reaccionar de forma exagerada." },
  40: { text: "Mantengo una visión positiva incluso cuando el entorno de trabajo es difícil." },
};
