export const TRANSLATION_STATUS = "draft" as const;

export const SJT_QUESTIONS_ES: Record<number, {
  text: string;
  options: [string, string, string, string];
}> = {
  1:  { text: "Descubre dos soluciones razonables a un problema urgente, pero ninguna es perfecta. ¿Qué hace?", options: ["Elige la opción con la evidencia más clara y explica las compensaciones.", "Retrasa la decisión hasta que aparezca una opción perfecta.", "Pide a la persona de mayor rango que decida sin compartir su análisis.", "Elige la opción que parece más rápida y sigue adelante."] },
  2:  { text: "Un compañero de equipo está bloqueando el progreso porque no está de acuerdo con la dirección. ¿Cuál es su mejor primer movimiento?", options: ["Escucha su preocupación, aclara el objetivo compartido y busca un camino viable.", "Trabaja alrededor de ellos para que el proyecto pueda seguir avanzando.", "Les dice que la decisión ya está tomada y que deben cumplir.", "Pide a todo el grupo que haga una pausa y revise cada decisión anterior."] },
  3:  { text: "Se da cuenta de que su error causó un error de informe del que otros pueden depender. ¿Qué hace?", options: ["Lo corrige silenciosamente con la esperanza de que nadie lo haya notado.", "Notifica a las personas afectadas, corrige los datos y explica los pasos de prevención.", "Espera a ver si el error crea un problema visible.", "Le dice solo a su gerente, sin contactar a los usuarios del informe."] },
  4:  { text: "Las prioridades cambian a mitad de un proyecto. ¿Qué respuesta muestra el mejor juicio?", options: ["Sigue trabajando en el plan original porque cambiar ahora desperdicia el esfuerzo.", "Aclara el nuevo objetivo, evalúa el impacto y ajusta el plan con el equipo.", "Vuelve a empezar de inmediato antes de entender la nueva prioridad.", "Pide confirmación escrita antes de hacer cualquier trabajo adicional."] },
  5:  { text: "Un interesado malinterpreta su actualización y se frustra. ¿Qué hace?", options: ["Reitera su mensaje con más firmeza para que lo entiendan.", "Reconoce la confusión, aclara el punto clave y confirma los próximos pasos.", "Evita más discusiones hasta que se calmen.", "Envía una explicación más larga con todos los detalles incluidos."] },
  6:  { text: "Falta un dato antes de un plazo. ¿Qué debe hacer?", options: ["Hace una suposición y la presenta como un hecho.", "Indica la suposición claramente, usa la evidencia disponible y señala el riesgo.", "Se niega a presentar nada hasta que los datos estén completos.", "Pide a otra persona que tome la decisión."] },
  7:  { text: "Un colega más callado tiene experiencia pero está siendo interrumpido en una reunión. ¿Qué hace?", options: ["Deja que la reunión continúe porque las interrupciones son normales.", "Le pregunta en privado después qué habría dicho.", "Crea espacio en la reunión para que termine su punto.", "Interrumpe al que interrumpe de manera agresiva."] },
  8:  { text: "Un proyecto está atrasado porque su estimación fue demasiado optimista. ¿Qué hace?", options: ["Comparte la estimación actualizada, acepta el error y propone opciones de recuperación.", "Reduce la calidad para cumplir con la fecha original sin decírselo a nadie.", "Culpa primero a las dependencias externas.", "Pide más tiempo sin explicar por qué."] },
  9:  { text: "Una herramienta en la que confía deja de funcionar antes de que venza una entrega. ¿Cuál es la respuesta más sólida?", options: ["Espera hasta que la herramienta se repare.", "Encuentra una alternativa viable, comunica el impacto y continúa.", "Cambia de herramienta permanentemente sin verificar las consecuencias.", "Le dice al solicitante que el plazo es imposible."] },
  10: { text: "Necesita rechazar una solicitud poco realista. ¿Qué dice?", options: ["Eso no puede hacerse.", "Que sí, y luego espera en privado que el alcance cambie.", "Esto es lo que es posible para entonces, y estas son las compensaciones para el resto.", "Les pide que envíen la solicitud a su gerente."] },
  11: { text: "Dos métricas cuentan historias diferentes sobre el rendimiento. ¿Qué hace?", options: ["Usa la métrica que respalda su conclusión preferida.", "Investiga por qué difieren y explica las limitaciones de cada una.", "Ignora ambas métricas y confía en la experiencia.", "Las promedia sin verificar si eso tiene sentido."] },
  12: { text: "Otro equipo pide ayuda cuando su propia carga de trabajo es elevada. ¿Cuál es la mejor respuesta?", options: ["Ignora la solicitud hasta que su propio trabajo esté terminado.", "Dice que sí de inmediato aunque ponga en riesgo sus compromisos.", "Aclara la urgencia, negocia la capacidad y alinea las prioridades de forma transparente.", "Reenvía la solicitud a otra persona sin contexto."] },
  13: { text: "Recibe retroalimentación crítica que parece injusta. ¿Qué debe hacer primero?", options: ["Defiende su intención de inmediato.", "Hace preguntas aclaratorias y busca la parte útil de la retroalimentación.", "La descarta porque la persona carece del contexto completo.", "Acepta todo sin discusión."] },
  14: { text: "Un nuevo requisito entra en conflicto con el trabajo ya completado. ¿Qué hace?", options: ["Evalúa qué puede reutilizarse, qué debe cambiar y el impacto en el alcance.", "Rechaza el requisito porque llegó tarde.", "Comienza a cambiar el trabajo de inmediato sin confirmar la prioridad.", "Pide una reunión pero detiene todo el trabajo relacionado hasta entonces."] },
  15: { text: "Un mensaje que envió podría interpretarse como duro. ¿Cuál es el mejor siguiente paso?", options: ["Asume que las personas entenderán su intención.", "Elimina el mensaje si es posible.", "Hace un seguimiento con un tono más claro, contexto y la acción siguiente prevista.", "Envía una larga disculpa antes de saber si causó un problema."] },
  16: { text: "Una persona de alto rango recomienda un enfoque que usted considera arriesgado. ¿Qué hace?", options: ["Guarda silencio porque tiene mayor rango.", "Plantea el riesgo respetuosamente con evidencia y alternativas.", "Rechaza el enfoque frente a todos.", "Sigue el enfoque pero documenta que no fue su idea."] },
  17: { text: "Se toma una decisión del equipo, pero no fue su opción preferida. ¿Qué hace?", options: ["Apoya la decisión y ayuda a que tenga éxito.", "Sigue defendiendo su opción en conversaciones paralelas.", "Hace solo su parte asignada sin ayudar a los demás.", "Pide revisarla en cada reunión de estado."] },
  18: { text: "Nota un problema recurrente en su área. ¿Cuál es la mejor acción?", options: ["Resuelve cada instancia a medida que aparece.", "Lo escala sin sugerir una solución.", "Analiza el patrón y propone una mejora preventiva.", "Lo acepta como parte de cómo funcionan las cosas."] },
  19: { text: "Le asignan trabajo en un dominio desconocido. ¿Qué hace?", options: ["Espera instrucciones detalladas antes de comenzar.", "Identifica qué necesita aprender, hace preguntas específicas y comienza con un plan pequeño.", "Finge saber lo suficiente para no parecer poco preparado/a.", "Pide que el trabajo sea reasignado."] },
  20: { text: "Su actualización contiene malas noticias. ¿Cuál es la mejor estructura?", options: ["Comienza con el problema, explica el impacto y proporciona los próximos pasos.", "Oculta la mala noticia al final.", "Solo la comparte verbalmente para que no haya registro escrito.", "Envía un breve mensaje que dice que hay un problema."] },
  21: { text: "Un cliente solicita algo fuera de la política. ¿Qué hace?", options: ["Aplica la política sin explicación.", "Rompe la política para mantener al cliente contento.", "Entiende la necesidad, explica los límites y ofrece alternativas conformes.", "Los envía a otro departamento."] },
  22: { text: "Un compañero de equipo se atribuye el mérito del trabajo al que usted contribuyó. ¿Cuál es su mejor primera respuesta?", options: ["Le corrige públicamente de una manera que le avergüenza.", "Deja que el resentimiento crezca y deja de ayudarle.", "Lo trata en privado y aclara el reconocimiento compartido de cara al futuro.", "Le dice a su gerente de inmediato sin hablar con ellos."] },
  23: { text: "Se comprometió con una tarea pero aparece un bloqueo. ¿Qué hace?", options: ["Espera hasta el plazo para explicar el bloqueo.", "Comunica con antelación, comparte lo que intentó y solicita la ayuda específica necesaria.", "Asume que alguien más lo notará.", "Abandona otros compromisos sin decírselo a nadie."] },
  24: { text: "Un proceso familiar es reemplazado por uno nuevo. ¿Cuál es su respuesta más sólida?", options: ["Compara el proceso antiguo y el nuevo, aprende los cambios y sugiere mejoras después de usarlo.", "Sigue usando el proceso antiguo hasta que alguien le detenga.", "Se queja de que el cambio fue innecesario.", "Usa el nuevo proceso pero evita dar retroalimentación."] },
  25: { text: "Necesita información de alguien que no ha respondido. ¿Qué hace?", options: ["Envía un seguimiento claro con contexto, plazo y por qué es importante.", "Sigue enviando el mismo mensaje repetidamente.", "Asume que le está ignorando y escala de inmediato.", "Espera y confía en que responderán."] },
  26: { text: "Su equipo está entusiasmado con una idea, pero usted ve un riesgo importante de implementación. ¿Qué hace?", options: ["Deja que el entusiasmo continúe porque lo que más importa es la moral.", "Nombra el riesgo, lo cuantifica si es posible y sugiere una prueba o mitigación.", "Cierra la idea de inmediato.", "Espera a que el riesgo sea obvio."] },
  27: { text: "Un proyecto tiene demasiados propietarios y las decisiones son lentas. ¿Cuál es lo mejor?", options: ["Aclara los derechos de decisión, los roles y el camino para los problemas no resueltos.", "Toma las decisiones usted mismo/a para ahorrar tiempo.", "Pide a todos que sean más colaborativos.", "Retrocede hasta que la propiedad quede clara."] },
  28: { text: "Encuentra un atajo que ahorraría tiempo pero crearía un riesgo de mantenimiento posterior. ¿Qué hace?", options: ["Usa el atajo y lo documenta solo si alguien lo pregunta.", "Presenta el atajo, el riesgo y las alternativas más seguras antes de decidir.", "Lo usa porque la velocidad es la única prioridad.", "Evita el atajo sin explicar la compensación."] },
  29: { text: "Un colega propone una mejor manera de hacer algo que usted construyó. ¿Cuál es su respuesta?", options: ["Defiende su enfoque original.", "Evalúa la idea de manera objetiva y la adopta si mejora el resultado.", "Está de acuerdo públicamente pero mantiene su enfoque sin cambios.", "Le pide que demuestre que funciona antes de involucrarse."] },
  30: { text: "Un traspaso interfuncional falló porque las expectativas no estaban claras. ¿Qué debe ocurrir a continuación?", options: ["Crea criterios de aceptación más claros y confirma la propiedad antes del próximo traspaso.", "Pide al equipo receptor que preste más atención la próxima vez.", "Añade más personas a las futuras reuniones de traspaso.", "Escribe un resumen más largo después de cada traspaso."] },
};
