export const TRANSLATION_STATUS = "draft" as const;

export const ST_QUESTIONS_ES: Record<number, { text: string }> = {
  1:  { text: "Me mantengo tranquilo/a y sereno/a al manejar situaciones de alto estrés en el trabajo." },
  2:  { text: "Puedo manejar mis reacciones emocionales incluso cuando me siento genuinamente frustrado/a o bajo gran presión." },
  3:  { text: "Noto cuando el estrés empieza a afectar mi estado de ánimo y tomo medidas para manejarlo antes de que escale." },
  4:  { text: "Tiendo a volverme brusco/a o irritable con mis colegas cuando estoy bajo una presión significativa." },
  5:  { text: "Soy capaz de evitar que el estrés personal afecte mis interacciones profesionales." },
  6:  { text: "Cuando estoy estresado/a, suelo tomar decisiones apresuradas de las que luego me arrepiento." },
  7:  { text: "Puedo mantenerme enfocado/a en los hechos y soluciones prácticas incluso cuando una situación se siente emocionalmente cargada." },
  8:  { text: "Es obvio para mis colegas cuando estoy estresado/a, incluso cuando intento no mostrarlo." },
  9:  { text: "Cuando las cosas salen mal, me recupero rápidamente y me concentro en lo que se puede hacer después." },
  10: { text: "Veo los contratiempos profesionales como oportunidades de aprendizaje en lugar de fracasos." },
  11: { text: "Mantengo mi confianza y autoestima incluso después de cometer un error significativo en el trabajo." },
  12: { text: "Tiendo a dar vueltas a los resultados negativos durante más tiempo del que es útil o productivo." },
  13: { text: "Soy capaz de mantener la perspectiva durante períodos difíciles o exigentes en el trabajo." },
  14: { text: "Después de un período estresante, regreso a mi nivel normal de desempeño con relativa rapidez." },
  15: { text: "Cuando me encuentro con un obstáculo significativo, me resulta difícil mantenerme motivado/a y seguir adelante." },
  16: { text: "Trato los desafíos como una parte normal de la vida laboral en lugar de como una amenaza personal." },
  17: { text: "Tengo estrategias efectivas y saludables que uso para manejar el estrés cuando se vuelve intenso." },
  18: { text: "Soy proactivo/a para abordar el estrés antes de que se convierta en un problema mayor." },
  19: { text: "Uso la actividad física, los descansos u otras salidas saludables para descomprimirme de la presión laboral." },
  20: { text: "Cuando me siento abrumado/a, tiendo a evitar la fuente de estrés en lugar de abordarla directamente." },
  21: { text: "Me siento cómodo/a pidiendo apoyo o hablando con alguien cuando estoy luchando con el estrés." },
  22: { text: "Soy capaz de separar el estrés laboral de mi vida personal y desconectarme genuinamente fuera del horario de trabajo." },
  23: { text: "Tiendo a acumular el estrés en lugar de abordarlo de forma constructiva." },
  24: { text: "Rindo a mi mejor nivel o cerca de él cuando las apuestas son altas y el plazo es ajustado." },
  25: { text: "Soy capaz de mantener la atención al detalle incluso cuando trabajo bajo una presión de tiempo significativa." },
  26: { text: "Cuando recibo una tarea difícil o de alto riesgo, me siento motivado/a por el desafío en lugar de abrumado/a por él." },
  27: { text: "Cometo significativamente más errores de lo habitual cuando trabajo bajo una intensa presión de tiempo." },
  28: { text: "Puedo priorizar eficazmente incluso cuando gestiono simultáneamente varios asuntos urgentes." },
  29: { text: "Las situaciones de alta presión constantemente hacen que mi rendimiento se deteriore notablemente." },
  30: { text: "Soy capaz de entregar trabajo de calidad incluso durante períodos particularmente exigentes o estresantes." },
};
