export const TRANSLATION_STATUS = "draft" as const;

export const TW_QUESTIONS_ES: Record<number, { text: string }> = {
  1:  { text: "Apoyo activamente a mis colegas para ayudarlos a tener éxito, no solo a mí mismo/a." },
  2:  { text: "Estoy dispuesto/a a anteponer los objetivos del equipo a mis preferencias personales cuando es importante." },
  3:  { text: "Comparto información y recursos con mi equipo sin que me lo pidan." },
  4:  { text: "Contribuyo equitativamente a las tareas compartidas en lugar de permitir que otros carguen con un peso desproporcionado." },
  5:  { text: "Reconozco y aprecio las contribuciones de mis compañeros de equipo abiertamente." },
  6:  { text: "Prefiero mantener mi trabajo separado e independiente en lugar de integrarlo con el del equipo." },
  7:  { text: "Estoy dispuesto/a a ajustar mi enfoque cuando eso ayuda al equipo a funcionar con mayor eficacia." },
  8:  { text: "Intervivo para ayudar a un colega que tiene dificultades, incluso cuando no es formalmente mi responsabilidad." },
  9:  { text: "Pienso en cómo mis decisiones y acciones afectan a otros miembros del equipo antes de proceder." },
  10: { text: "Mantengo a mis compañeros informados sobre mi progreso sin esperar a que me lo pregunten." },
  11: { text: "Comunico claramente lo que necesito de otros para completar mi trabajo de manera efectiva." },
  12: { text: "Escucho atentamente las ideas y perspectivas de mis compañeros antes de formarme mi propia opinión." },
  13: { text: "Comparto mis puntos de vista abiertamente en las discusiones del equipo, incluso cuando difieren de la opinión mayoritaria." },
  14: { text: "Me demoro en actualizar al equipo cuando mis prioridades o planes cambian." },
  15: { text: "Doy retroalimentación constructiva a los colegas de manera honesta y respetuosa." },
  16: { text: "Pido aclaración en lugar de asumir que he entendido lo que quiere decir un colega." },
  17: { text: "Soy transparente con el equipo sobre los desafíos que enfrento y que pueden afectar nuestro trabajo compartido." },
  18: { text: "Me resulta difícil hablar en entornos de equipo aunque tenga algo relevante que aportar." },
  19: { text: "Cumplo de manera consistente con lo que me comprometo dentro de los plazos acordados." },
  20: { text: "Mis compañeros pueden contar conmigo para cumplir sin necesidad de seguimiento constante." },
  21: { text: "Comunico con anticipación si voy a incumplir un compromiso o un plazo." },
  22: { text: "Estoy dispuesto/a a trabajar fuera de mi zona de confort cuando el equipo lo necesita." },
  23: { text: "A veces dejo que las tareas queden pendientes cuando nadie las está supervisando activamente." },
  24: { text: "Me hago responsable de mi parte de un proyecto compartido desde el inicio hasta la entrega final." },
  25: { text: "Entrego tarde las acciones acordadas con más frecuencia de la que debería." },
  26: { text: "Voy más allá del mínimo requerido cuando el éxito compartido del equipo depende de ello." },
  27: { text: "Honro mis compromisos con el equipo incluso cuando las circunstancias personales lo dificultan." },
  28: { text: "Cuando no estoy de acuerdo con un compañero, planteo el tema de forma directa y tranquila en lugar de evitarlo." },
  29: { text: "Me esfuerzo por entender la perspectiva de la otra persona antes de responder en un conflicto." },
  30: { text: "Tiendo a evitar las conversaciones difíciles con colegas y permito que los problemas se acumulen con el tiempo." },
  31: { text: "En un conflicto, me enfoco en resolver el problema en lugar de en asignar culpas." },
  32: { text: "Me esfuerzo por reconstruir la relación de trabajo después de que se ha resuelto un desacuerdo." },
  33: { text: "Soy capaz de separar el problema profesional de cualquier sentimiento personal cuando surge un conflicto." },
  34: { text: "Tiendo a ceder en los desacuerdos incluso cuando genuinamente creo que tengo razón." },
  35: { text: "Solo involucro a un líder de equipo o gerente en un conflicto después de que la resolución directa entre las partes genuinamente no ha funcionado." },
};
