export const TRANSLATION_STATUS = "draft" as const;

export const TM_QUESTIONS_ES: Record<number, { text: string; options: [string, string, string, string] }> = {
  // Prioritization (8)
  1:  { text: "Tiene cuatro tareas vencidas hoy: dos son urgentes e importantes, una es urgente pero no importante, y una es importante pero no urgente. ¿Con cuál empieza?", options: ["La tarea urgente pero no importante, para quitarla de su lista rápidamente", "La tarea importante pero no urgente, ya que tiene mayor valor a largo plazo", "Las dos tareas que son tanto urgentes como importantes", "Avanza por la lista en el orden en que su gerente las asignó"] },
  2:  { text: "Su gerente le asigna una nueva tarea de alta prioridad mientras está a mitad de un trabajo complejo. ¿Qué hace?", options: ["Deja el trabajo actual y cambia de inmediato — la solicitud del gerente es lo primero", "Aclara con su gerente qué tan urgente es la nueva tarea en relación con su trabajo actual, y actúa según su orientación", "Termina su tarea actual por completo antes de comenzar nada nuevo", "Comienza ambas tareas simultáneamente para que ninguna sea ignorada"] },
  3:  { text: "Su lista de tareas tiene 15 elementos. ¿Cuál es el enfoque más efectivo?", options: ["Trabaja los elementos de arriba hacia abajo en el orden en que fueron añadidos", "Hace primero las tareas más fáciles para ganar impulso", "Identifica los tres o cuatro elementos de mayor impacto y se centra en ellos primero", "Delega las tareas que le resultan difíciles o desconocidas"] },
  4:  { text: "Constantemente tiene más trabajo del que el tiempo disponible le permite. ¿Cuál es la respuesta más efectiva a largo plazo?", options: ["Trabaja más horas indefinidamente para mantener el ritmo", "Intenta hacer todo y acepta una calidad de resultado inferior", "Plantea el problema con su gerente y discute qué elementos pueden descartar prioridad, delegarse o eliminarse", "Abandona silenciosamente las tareas de menor prioridad sin decírselo a nadie"] },
  5:  { text: "Un colega pide su ayuda mientras trabaja en algo urgente. ¿Cuál es la mejor acción?", options: ["Detiene de inmediato y le ayuda — las relaciones son lo más importante", "Ignora la solicitud y se centra en su tarea", "Le hace saber que está ocupado/a con algo urgente y fija una hora específica para ayudarle", "Le envía a otra persona sin explicación"] },
  6:  { text: "Le han invitado a una reunión sin agenda que cubre un tema que no requiere su participación. ¿Qué hace?", options: ["Asiste y usa el tiempo para ponerse al día con correos electrónicos", "Declina cortésmente o pide ser excusado/a, explicando sus prioridades actuales", "Asiste y se va temprano sin decírselo al organizador", "Asiste a todas las reuniones — siempre vale la pena estar en la sala"] },
  7:  { text: "¿Qué tarea debe completarse generalmente primero?", options: ["Una tarea que su gerente solicitó ayer", "Una tarea que desbloquea a tres colegas para avanzar en su propio trabajo", "Un informe detallado con vencimiento la próxima semana que requiere concentración profunda", "Vaciar y responder su bandeja de entrada de correo electrónico"] },
  8:  { text: "Tiene dos tareas con el mismo plazo que parecen igualmente importantes. ¿Cómo decide cuál comenzar primero?", options: ["Elige aleatoriamente — ambas tienen la misma prioridad", "Elige la que le resulta más agradable para ganar impulso desde el principio", "Evalúa cuál tiene mayor consecuencia si se retrasa y comienza con esa", "Pide a alguien más que asuma una de las tareas"] },
  // Planning (8)
  9:  { text: "¿Cuál es el enfoque más efectivo para planificar un proyecto complejo antes de comenzar el trabajo?", options: ["Comienza de inmediato y deja que el plan emerja a medida que avanza", "Escribe un plan aproximado pero espera actualizarlo constantemente según las circunstancias diarias", "Divide el proyecto en hitos, estima el tiempo requerido por tarea e identifica las dependencias clave antes de comenzar", "Crea un plan detallado solo después de que surjan los problemas"] },
  10: { text: "Al inicio de cada día de trabajo, ¿cuál es el hábito de planificación más efectivo?", options: ["Revisa primero el correo electrónico y deja que su contenido dicte las prioridades del día", "Identifica sus tres resultados más importantes del día y protege el tiempo para alcanzarlos", "Planifica su día en incrementos de 15 minutos de principio a fin", "Comienza a trabajar de inmediato — planificar es una distracción de hacer las cosas"] },
  11: { text: "Está planificando una tarea y se da cuenta de que le falta información clave antes de poder comenzar. ¿Cuál es la mejor acción?", options: ["Comienza de todas formas y llena los vacíos a medida que se hacen evidentes", "Espera hasta tener información perfecta antes de comprometerse con cualquier cronograma", "Identifica exactamente qué información falta y quién la tiene, luego reúne lo que necesita antes de comprometerse con una fecha de inicio", "Hace suposiciones y las presenta como hechos para avanzar rápidamente"] },
  12: { text: "Tiene dos semanas para completar un proyecto. ¿Cuál es el mayor riesgo de no establecer plazos para las subtareas a lo largo del camino?", options: ["Corre el riesgo de terminar demasiado pronto y tener tiempo no utilizado al final", "Corre el riesgo de entregar de más en cuanto a calidad", "Es probable que pase demasiado tiempo en las etapas iniciales y se apresure en las partes más críticas cerca del plazo final", "Su gerente puede sentirse excluido del proceso"] },
  13: { text: "¿Cuál es el enfoque más efectivo para estimar cuánto tiempo llevará una tarea?", options: ["Reduce a la mitad su estimación instintiva — la mayoría de las personas sobreestima significativamente la duración de las tareas", "Base su estimación en cuánto tiempo han llevado tareas comparables anteriormente y añada un margen para complicaciones inesperadas", "Acepta sin cuestionamiento cualquier plazo que le sugiera su interesado", "Dice 'llevará lo que lleve' para evitar comprometerse prematuramente"] },
  14: { text: "Ha planificado su semana en detalle pero llega una solicitud inesperada de alta prioridad el martes. ¿Cuál es la respuesta más efectiva?", options: ["La añade a su lista existente e intenta encajarla en torno a los compromisos actuales", "Evalúa qué desplaza la nueva solicitud, actualiza su plan y comunica los plazos afectados a los interesados", "La ignora hasta que su trabajo planificado originalmente esté completo", "Trabaja horas adicionales cada tarde para absorber el nuevo trabajo sin reprogramar nada"] },
  15: { text: "¿Qué enfoque apoya mejor la gestión de múltiples plazos complejos simultáneamente?", options: ["Notas mentales y una buena memoria", "Una única lista de tareas corriente actualizada diariamente", "Un plan de tareas visual que muestre tareas, responsables, plazos y dependencias a lo largo de todo el cronograma", "Reuniones diarias de pie con el equipo para mantener a todos alineados"] },
  16: { text: "Una tarea que está planificando requiere la aportación de otro equipo antes de poder continuar. ¿Cuál es el mejor enfoque?", options: ["Comienza su propio trabajo y espera que entreguen antes de que lo necesite", "Hace suposiciones sobre su aportación y la rellena usted mismo/a", "Acuerda con ellos explícitamente una fecha de entrega, la incorpora a su plan y hace un seguimiento proactivo a medida que se acerca esa fecha", "Espera a que le contacten cuando estén listos"] },
  // Focus (7)
  17: { text: "Está trabajando en una tarea que requiere concentración profunda, pero las notificaciones siguen interrumpiéndole. ¿Cuál es la acción más efectiva?", options: ["Sigue gestionando ambas — es bueno/a manejando interrupciones", "Desactiva las notificaciones durante un período definido y establece una hora específica para revisar los mensajes", "Responde a cada notificación a medida que llega para que no le distraiga después", "Cambia de ubicación cada vez que una notificación le distrae"] },
  18: { text: "Está a mitad de una tarea importante y sigue siendo desviado/a por interrupciones de menor prioridad. ¿Cuál es la mejor solución a largo plazo?", options: ["Cambia a trabajar solo por las tardes cuando hay menos personas alrededor", "Bloquea tiempo de concentración en su calendario y comunica sus ventanas de disponibilidad a los colegas", "Trabaja más rápido para reducir la ventana en la que pueden ocurrir interrupciones", "Acepta que las interrupciones son inevitables y las gestiona indefinidamente"] },
  19: { text: "Se sienta a trabajar pero se siente abrumado/a y no puede decidir por dónde empezar. ¿Cuál es el enfoque más efectivo?", options: ["Navega por Internet brevemente para restablecer su estado mental", "Anota la única tarea más importante y se compromete a centrarse solo en esa durante los próximos 25–30 minutos", "Escribe una lista completa de todo lo que necesita hacer antes de comenzar nada", "Llama a un colega para hablar sobre su carga de trabajo antes de comenzar"] },
  20: { text: "La investigación muestra consistentemente que el cambio frecuente de tareas típicamente:", options: ["Mejora el rendimiento general al mantener los niveles de energía y la variedad", "Reduce la calidad y la eficiencia debido al costo cognitivo de cada cambio de contexto", "Es efectivo siempre que las tareas utilicen diferentes habilidades cognitivas", "Es una práctica recomendada para las personas de alto rendimiento"] },
  21: { text: "Está en medio de un trabajo de concentración cuando un colega se acerca a charlar. ¿Cuál es la mejor respuesta?", options: ["Detiene su trabajo de inmediato y se involucra — las relaciones son importantes", "Le ignora y continúa trabajando sin reconocerle", "Le reconoce, le hace saber que está en un período de concentración y acuerda una hora específica para conectar pronto", "Le pide que le envíe un correo electrónico"] },
  22: { text: "¿Qué hábito apoya mejor el enfoque sostenido y el rendimiento mental a lo largo de la jornada laboral?", options: ["Consumir múltiples cafés para mantener el estado de alerta durante todo el día", "Trabajar sin pausas hasta que una tarea esté completamente terminada", "Tomar descansos breves y regulares entre sesiones de trabajo concentrado para restaurar la energía mental", "Programar todas las reuniones antes de las 9 de la mañana para proteger el resto del día"] },
  23: { text: "Necesita hacer un trabajo concentrado y cognitivamente exigente y su oficina de planta abierta es ruidosa. ¿Cuál es el enfoque más efectivo?", options: ["Intenta concentrarse de todas formas — la capacidad de bloquear el ruido es una habilidad que vale la pena desarrollar", "Espera un momento más tranquilo durante el día, que puede que nunca llegue", "Reserva una sala tranquila, usa auriculares con cancelación de ruido o habla con su gerente sobre la necesidad de tiempo de concentración protegido", "Hace la tarea rápidamente y acepta menor calidad para salir del entorno ruidoso"] },
  // Deadline Management (7)
  24: { text: "Se da cuenta tres días antes de un plazo de que no podrá entregar a tiempo. ¿Qué hace?", options: ["Entrega lo que ha completado en el plazo sin señalar la deficiencia", "Comunica de inmediato con su gerente o interesado, explica la situación y propone un cronograma revisado o un alcance reducido", "Trabaja toda la noche y espera poder cumplir con el plazo original", "Entrega tarde sin ninguna advertencia previa y explica la situación después"] },
  25: { text: "Un interesado solicita una fecha de entrega anterior a la acordada originalmente. ¿Cuál es la mejor respuesta?", options: ["Acepta de inmediato para demostrar flexibilidad y disposición para ayudar", "Evalúa de manera realista lo que se necesita para alcanzar la nueva fecha, y luego responde con confirmación o una explicación transparente de lo que es y no es alcanzable", "Se niega — la fecha original fue acordada y no debe cambiarse", "Dice que hará lo mejor posible sin comprometerse a nada específico"] },
  26: { text: "Tiene varios plazos que caen el mismo día. ¿Cuál es el mejor enfoque?", options: ["Trabaja en todos los entregables simultáneamente para hacer progreso paralelo", "Identifica qué plazo tiene la mayor consecuencia si se incumple, completa ese primero y comunica proactivamente si los demás están en riesgo", "Solicita extensiones de plazo para todos los elementos para reducir la presión", "Trabaja toda la noche el día anterior a que venzan todos los plazos"] },
  27: { text: "La entrega tardía de un colega le impide completar su propio entregable a tiempo. ¿Cuál es la respuesta más efectiva?", options: ["Espera y confía en que entreguen algo pronto", "Incumple su plazo y lo atribuye al retraso de su colega", "Contacta a su colega para establecer una expectativa de entrega revisada firme e informa a su interesado de que su plazo está en riesgo y por qué", "Completa su trabajo usted mismo/a sin discutirlo con ellos"] },
  28: { text: "Le han dado un plazo que considera poco realista desde el principio. ¿Cuál es la mejor acción?", options: ["Lo acepta y hace lo mejor posible — quejarse de los plazos da mala imagen", "Se niega a comenzar el trabajo hasta que se acuerde un plazo más realista", "Plantea su preocupación de inmediato con una explicación clara y propone un cronograma alternativo realista con justificación", "Comienza el trabajo y escala el problema solo cuando se convierte en un problema visible"] },
  29: { text: "Cumplió un plazo, pero la calidad del resultado está por debajo de su estándar habitual debido a la presión de tiempo. ¿Qué hace?", options: ["Entrega y no dice nada — se cumplió el plazo y eso es lo que se pidió", "Informa al destinatario de que las limitaciones de tiempo afectaron la calidad y propone un seguimiento para mejorar el resultado si es necesario", "Retira la entrega y solicita más tiempo aunque el plazo ya haya pasado", "Vuelve a enviar una versión mejor sin informar a nadie — puede que no lo hayan notado"] },
  30: { text: "Después de entregar a tiempo consistentemente durante meses, incumple un plazo por primera vez. ¿Cuál es la respuesta más apropiada?", options: ["Se disculpa una vez y sigue adelante sin insistir en el asunto", "Reflexiona sobre qué causó el incumplimiento, aborda la causa raíz y comparte proactivamente qué está cambiando para evitar que se repita", "Atribuye el incumplimiento a factores externos fuera de su control", "Se ofrece a trabajar sin paga para compensar el impacto del plazo incumplido"] },
};
