export const TRANSLATION_STATUS = "draft" as const;

export const VR_QUESTIONS_ES: Record<number, { text: string; options: [string, string, string, string] }> = {
  1:  { text: "MÉDICO es a PACIENTE como ABOGADO es a:", options: ["Tribunal", "Justicia", "Cliente", "Ley"] },
  2:  { text: "CALOR es a TEMPERATURA como DISTANCIA es a:", options: ["Velocidad", "Longitud", "Peso", "Tiempo"] },
  3:  { text: "PINCEL es a PINTOR como BISTURÍ es a:", options: ["Hospital", "Medicina", "Cirujano", "Enfermero"] },
  4:  { text: "¿Qué palabra NO pertenece? Observar · Notar · Ignorar · Percibir · Detectar", options: ["Observar", "Notar", "Ignorar", "Percibir"] },
  5:  { text: "¿Qué palabra NO pertenece? Piano · Guitarra · Violín · Trompeta · Escultura", options: ["Piano", "Guitarra", "Trompeta", "Escultura"] },
  6:  { text: "Lo opuesto de VALENTÍA es:", options: ["Heroísmo", "Cobardía", "Fuerza", "Audacia"] },
  7:  { text: "TRANSPARENTE es a OPACO como FLEXIBLE es a:", options: ["Elástico", "Doblable", "Rígido", "Frágil"] },
  8:  { text: "Elija la palabra que mejor completa: 'A pesar de la complejidad de la tarea, la completó con notable _____.'", options: ["Dificultad", "Rapidez", "Eficiencia", "Vacilación"] },
  9:  { text: "Un sinónimo de CONCISO es:", options: ["Extenso", "Breve", "Detallado", "Complejo"] },
  10: { text: "Un antónimo de ABUNDANTE es:", options: ["Copioso", "Generoso", "Escaso", "Adinerado"] },
  11: { text: "FUEGO es a HUMO como CAUSA es a:", options: ["Razón", "Efecto", "Origen", "Desencadenante"] },
  12: { text: "Elija la palabra más adecuada: 'La decisión del gerente fue _____, ya que satisfizo a ambos equipos.'", options: ["Polémica", "Ambigua", "Equitativa", "Arbitraria"] },
  13: { text: "BIBLIOTECA es a LIBROS como GALERÍA es a:", options: ["Visitantes", "Pinturas", "Esculturas", "Artistas"] },
  14: { text: "¿Qué palabra NO pertenece? Ansioso · Nervioso · Aprensivo · Seguro · Preocupado", options: ["Ansioso", "Nervioso", "Seguro", "Preocupado"] },
  15: { text: "DILUIR es a CONCENTRAR como DIVIDIR es a:", options: ["Compartir", "Separar", "Multiplicar", "Calcular"] },
  16: { text: "Un sinónimo de AMBIGUO es:", options: ["Claro", "Cierto", "Poco claro", "Decisivo"] },
  17: { text: "'Habló con gran _____, haciendo que cada palabra contara.' ¿Qué palabra completa mejor esta oración?", options: ["Brevedad", "Volumen", "Entusiasmo", "Claridad"] },
  18: { text: "ARQUITECTO es a PLANO como COMPOSITOR es a:", options: ["Orquesta", "Actuación", "Partitura", "Instrumento"] },
  19: { text: "¿Qué palabra tiene un significado más cercano a CORROBORAR?", options: ["Contradecir", "Confirmar", "Crear", "Ocultar"] },
  20: { text: "RUIDOSO es a ENSORDECEDOR como FRÍO es a:", options: ["Gélido", "Fresco", "Tibio", "Templado"] },
  21: { text: "Si todos los gerentes asisten al briefing semanal, y Sarah es gerente, ¿cuál debe ser verdad?", options: ["Sarah a veces asiste", "Sarah siempre asiste al briefing", "Sarah puede saltarse el briefing", "Sarah preside el briefing"] },
  22: { text: "Ningún miembro del equipo de finanzas trabaja los fines de semana. Daniel trabaja los fines de semana. ¿Cuál conclusión se deriva?", options: ["Daniel puede estar en finanzas", "Daniel no está en finanzas", "Daniel trabaja demasiado", "El equipo de finanzas nunca trabaja"] },
  23: { text: "Algunos analistas también son jefes de proyecto. Todos los jefes de proyecto asisten a la reunión del lunes. ¿Cuál debe ser verdad?", options: ["Todos los analistas asisten a la reunión del lunes", "Ningún analista asiste a la reunión del lunes", "Algunos analistas asisten a la reunión del lunes", "Ninguna de las anteriores"] },
  24: { text: "Cada informe presentado este trimestre fue revisado por un editor sénior. Este informe NO fue revisado. Por lo tanto:", options: ["Este informe fue presentado este trimestre", "Este informe puede haber sido presentado este trimestre", "Este informe no fue presentado este trimestre", "No se puede extraer ninguna conclusión"] },
  25: { text: "LIBRO es a CAPÍTULO como PELÍCULA es a:", options: ["Rollo", "Escena", "Director", "Pantalla"] },
  26: { text: "¿Qué palabra NO pertenece? Anual · Mensual · Trimestral · Semestral · Semanal · Instantáneo", options: ["Anual", "Trimestral", "Semestral", "Instantáneo"] },
  27: { text: "Un sinónimo de METICULOSO es:", options: ["Descuidado", "Minucioso", "Rápido", "Vago"] },
  28: { text: "Elija la mejor palabra: 'El testigo dio un relato _____, recordando cada detalle con precisión.'", options: ["Vago", "Exhaustivo", "Literal", "Resumido"] },
  29: { text: "CÁLIDO es a CALIENTE como INTERESADO es a:", options: ["Curioso", "Fascinado", "Consciente", "Comprometido"] },
  30: { text: "¿Cuál oración es más clara y precisa?", options: ["El proyecto va bien y más o menos estamos en el buen camino.", "El proyecto avanza según lo planificado y se completará el viernes.", "Las cosas están bien con el proyecto en su mayor parte.", "El proyecto parece estar bien para la mayoría de las personas involucradas."] },
};
