export const TRANSLATION_STATUS = "draft" as const;

export const WS_QUESTIONS_ES: Record<number, { text: string }> = {
  1:  { text: "Prefiero recopilar y analizar información antes de tomar decisiones." },
  2:  { text: "Busco las causas raíz en lugar de simplemente tratar los síntomas." },
  3:  { text: "Disfruto resolver problemas complejos de manera estructurada y sistemática." },
  4:  { text: "Baso mis decisiones en datos y evidencia en lugar de solo en la intuición." },
  5:  { text: "Me resulta fácil evaluar las fortalezas y debilidades de diferentes opciones." },
  6:  { text: "Tiendo a tomar decisiones rápidas sin un análisis exhaustivo." },
  7:  { text: "Aplico razonamiento lógico al evaluar riesgos antes de actuar." },
  8:  { text: "Me resulta difícil sacar conclusiones claras de información compleja o ambigua." },
  9:  { text: "Presto mucha atención a los detalles en todo lo que hago." },
  10: { text: "Reviso mi trabajo cuidadosamente antes de considerarlo completo." },
  11: { text: "Noto errores e inconsistencias que otros suelen pasar por alto." },
  12: { text: "Prefiero un trabajo exhaustivo y de alta calidad sobre resultados rápidos y aproximados." },
  13: { text: "Mantengo los registros y la documentación bien organizados y actualizados." },
  14: { text: "A veces paso por alto detalles importantes cuando trabajo a gran velocidad." },
  15: { text: "Reviso el resultado final frente a los requisitos originales antes de enviarlo." },
  16: { text: "Me frustran las tareas detalladas o repetitivas." },
  17: { text: "Prefiero trabajar en equipo que de forma independiente." },
  18: { text: "Busco activamente la opinión de mis colegas antes de tomar decisiones importantes." },
  19: { text: "Ajusto mi enfoque cuando otros ofrecen una mejor perspectiva." },
  20: { text: "Me resulta fácil construir relaciones de trabajo con nuevos colegas." },
  21: { text: "Contribuyo de manera constructiva a las discusiones grupales y a la planificación del equipo." },
  22: { text: "Prefiero trabajar de forma independiente en lugar de depender de otros." },
  23: { text: "Comparto el mérito de los éxitos del equipo con todos los colaboradores." },
  24: { text: "Me resulta difícil alinearme con las decisiones del equipo con las que personalmente no estoy de acuerdo." },
  25: { text: "Me adapto rápidamente cuando las prioridades o los planes cambian inesperadamente." },
  26: { text: "Veo el cambio como una oportunidad en lugar de una interrupción." },
  27: { text: "Me siento cómodo/a trabajando con ambigüedad cuando la información completa aún no está disponible." },
  28: { text: "Puedo alternar entre diferentes tipos de tareas sin perder el enfoque ni el impulso." },
  29: { text: "Me mantengo eficaz en situaciones de alta presión o incertidumbre." },
  30: { text: "Me resulta difícil trabajar eficazmente fuera de las rutinas familiares." },
  31: { text: "Aprendo con facilidad nuevas herramientas, sistemas o métodos cuando son necesarios." },
  32: { text: "Los cambios inesperados en mis planes tienden a afectar negativamente mi rendimiento." },
  33: { text: "Me mantengo enfocado/a en alcanzar objetivos incluso cuando el camino se complica." },
  34: { text: "Establezco metas personales claras y hago un seguimiento activo de mi progreso." },
  35: { text: "Tomo iniciativa sin esperar que me dirijan." },
  36: { text: "Me impulso a mí mismo/a y a mi equipo a obtener resultados excelentes." },
  37: { text: "Priorizo los resultados sobre la comodidad de las rutinas familiares o seguras." },
  38: { text: "Tiendo a perder impulso cuando un proyecto enfrenta contratiempos significativos." },
  39: { text: "Soy proactivo/a en identificar lo que debe hacerse a continuación." },
  40: { text: "Me cuesta mantener el enfoque cuando el reconocimiento o la retroalimentación no son inmediatos." },
};
