import { jsPDF } from "jspdf";

export interface CTPDFData {
  candidateName: string;
  assessmentName: string;
  date: string;
  score: number;
  correct: number;
  total: number;
  interpretation: string;
}

export interface AQPDFData {
  candidateName: string;
  assessmentName: string;
  date: string;
  score: number;
  control: number;
  ownership: number;
  reach: number;
  endurance: number;
  interpretation: string;
  description: string;
}

function bar(doc: jsPDF, x: number, y: number, w: number, pct: number, r: number, g: number, b: number) {
  doc.setFillColor(220, 226, 240);
  doc.rect(x, y, w, 4, "F");
  if (pct > 0) {
    doc.setFillColor(r, g, b);
    doc.rect(x, y, Math.max(1, w * pct), 4, "F");
  }
}

function header(doc: jsPDF, accentR: number, accentG: number, accentB: number) {
  const W = 210;
  const margin = 20;
  doc.setFillColor(7, 8, 15);
  doc.rect(0, 0, W, 42, "F");

  doc.setFillColor(accentR, accentG, accentB);
  doc.rect(margin, 14, 11, 11, "F");
  doc.setFontSize(6.5);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("IT", margin + 5.5, 21.5, { align: "center" });

  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text("Assessment Report", margin + 16, 22);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text("Intelligences Test  ·  Confidential", margin + 16, 30);
}

function candidateBox(doc: jsPDF, name: string, assessment: string, date: string, y: number) {
  const margin = 20;
  const contentW = 170;
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, contentW, 26, "F");

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text("CANDIDATE", margin + 5, y + 7);
  doc.text("ASSESSMENT", margin + 68, y + 7);
  doc.text("DATE COMPLETED", margin + 136, y + 7);

  doc.setFontSize(10.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  const safeName = name.length > 22 ? name.slice(0, 22) + "…" : name;
  doc.text(safeName, margin + 5, y + 18);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const safeAssessment = assessment.length > 22 ? assessment.slice(0, 22) + "…" : assessment;
  doc.text(safeAssessment, margin + 68, y + 18);
  doc.text(date, margin + 136, y + 18);
}

function sectionTitle(doc: jsPDF, text: string, y: number) {
  const margin = 20;
  const contentW = 170;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(71, 85, 105);
  doc.text(text, margin, y);
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y + 3, margin + contentW, y + 3);
}

function footer(doc: jsPDF) {
  const W = 210;
  const margin = 20;
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text("This report is confidential and intended solely for assessment purposes.", margin, 280);
  doc.text("Generated by Intelligences Test Platform", W - margin, 280, { align: "right" });
}

export function downloadCTPDF(data: CTPDFData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const margin = 20;
  const contentW = 170;

  header(doc, 29, 78, 216);
  candidateBox(doc, data.candidateName, data.assessmentName, data.date, 50);

  let y = 88;
  sectionTitle(doc, "RESULT SUMMARY", y);
  y += 10;

  doc.setFontSize(46);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(29, 78, 216);
  doc.text(`${data.score}%`, margin, y + 18);

  const scoreW = doc.getTextWidth(`${data.score}%`);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(data.interpretation, margin + scoreW + 6, y + 8);

  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`${data.correct} of ${data.total} correct`, margin + scoreW + 6, y + 17);

  y += 28;
  bar(doc, margin, y, contentW, data.score / 100, 29, 78, 216);
  y += 14;

  sectionTitle(doc, "SCORE BENCHMARKS", y);
  y += 10;

  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, contentW, 44, "F");

  const ctBands = [
    { range: "90–100%", label: "Exceptional Critical Thinker", r: 16, g: 185, b: 129 },
    { range: "75–89%", label: "Strong Critical Thinker", r: 59, g: 130, b: 246 },
    { range: "60–74%", label: "Developing Critical Thinker", r: 245, g: 158, b: 11 },
    { range: "45–59%", label: "Basic Critical Thinker", r: 249, g: 115, b: 22 },
    { range: "Below 45%", label: "Needs Development", r: 239, g: 68, b: 68 },
  ];

  ctBands.forEach((band, i) => {
    const by = y + 10 + i * 7;
    doc.setFillColor(band.r, band.g, band.b);
    doc.circle(margin + 7, by - 1.5, 1.8, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(band.r, band.g, band.b);
    doc.text(band.range, margin + 12, by);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    doc.text(` — ${band.label}`, margin + 12 + doc.getTextWidth(band.range), by);
  });

  footer(doc);
  doc.save(`${data.candidateName.replace(/ /g, "_")}_Critical_Thinking_Report.pdf`);
}

export function downloadAQPDF(data: AQPDFData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const margin = 20;
  const contentW = 170;

  header(doc, 109, 40, 217);
  candidateBox(doc, data.candidateName, data.assessmentName, data.date, 50);

  let y = 88;
  sectionTitle(doc, "RESULT SUMMARY", y);
  y += 10;

  doc.setFontSize(46);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(109, 40, 217);
  doc.text(`${data.score}`, margin, y + 18);

  const scoreW = doc.getTextWidth(`${data.score}`);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text("/200", margin + scoreW + 2, y + 18);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(data.interpretation, margin + scoreW + 16, y + 8);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  const descLines = doc.splitTextToSize(data.description, contentW - scoreW - 16);
  doc.text(descLines, margin + scoreW + 16, y + 17);

  y += 30;
  bar(doc, margin, y, contentW, data.score / 200, 109, 40, 217);
  y += 14;

  sectionTitle(doc, "CORE BREAKDOWN", y);
  y += 10;

  const dims = [
    { label: "Control", value: data.control, r: 59, g: 130, b: 246 },
    { label: "Ownership", value: data.ownership, r: 109, g: 40, b: 217 },
    { label: "Reach", value: data.reach, r: 16, g: 185, b: 129 },
    { label: "Endurance", value: data.endurance, r: 245, g: 158, b: 11 },
  ];

  dims.forEach(({ label, value, r, g, b }) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(label, margin, y + 3.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(`${value} / 50`, margin + contentW, y + 3.5, { align: "right" });
    bar(doc, margin, y + 6, contentW, value / 50, r, g, b);
    y += 18;
  });

  y += 4;
  sectionTitle(doc, "SCORE BENCHMARKS", y);
  y += 10;

  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, contentW, 44, "F");

  const aqBands = [
    { range: "166–200", label: "Exceptional AQ", r: 16, g: 185, b: 129 },
    { range: "135–165", label: "High AQ", r: 59, g: 130, b: 246 },
    { range: "95–134", label: "Moderate AQ", r: 245, g: 158, b: 11 },
    { range: "60–94", label: "Low AQ", r: 249, g: 115, b: 22 },
    { range: "40–59", label: "Adversely Challenged", r: 239, g: 68, b: 68 },
  ];

  aqBands.forEach((band, i) => {
    const by = y + 10 + i * 7;
    doc.setFillColor(band.r, band.g, band.b);
    doc.circle(margin + 7, by - 1.5, 1.8, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(band.r, band.g, band.b);
    doc.text(band.range, margin + 12, by);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    doc.text(` — ${band.label}`, margin + 12 + doc.getTextWidth(band.range), by);
  });

  footer(doc);
  doc.save(`${data.candidateName.replace(/ /g, "_")}_AQ_Report.pdf`);
}
