export const TRANSLATION_STATUS = "draft" as const;

export const AR_QUESTIONS_FR: Record<number, { text: string; options: [string, string, string, string] }> = {
  1:  { text: "Que vient ensuite dans la séquence ? 2, 6, 18, 54, ___", options: ["108", "162", "216", "324"] },
  2:  { text: "Que vient ensuite dans la séquence de lettres ? A, C, F, J, O, ___", options: ["T", "U", "V", "W"] },
  3:  { text: "Une séquence répétitive : Triangle, Cercle, Carré, Triangle, Cercle, ___", options: ["Triangle", "Cercle", "Carré", "Pentagone"] },
  4:  { text: "Dans une grille 3×3, chaque ligne contient ●, ■ et ▲ exactement une fois. Ligne 1 : ●, ■, ▲. Ligne 2 : ■, ▲, ●. Ligne 3 : ▲, ●, ___.", options: ["●", "■", "▲", "Aucune de ces réponses"] },
  5:  { text: "Que vient ensuite ? 1, 1, 2, 3, 5, 8, ___", options: ["11", "12", "13", "14"] },
  6:  { text: "Quel nombre complète la séquence ? 4, 9, 16, 25, 36, ___", options: ["42", "46", "49", "54"] },
  7:  { text: "Quel est l'intrus ? Carré · Rectangle · Triangle · Cercle · Pentagone", options: ["Carré", "Rectangle", "Cercle", "Pentagone"] },
  8:  { text: "Un motif de points croît : 1, 4, 9, 16, ___", options: ["20", "25", "24", "30"] },
  9:  { text: "Que vient ensuite ? Z, X, V, T, R, ___", options: ["O", "P", "Q", "N"] },
  10: { text: "Les formes alternent pleines/vides : carré plein, carré vide, cercle plein, cercle vide, triangle plein. Que vient ensuite ?", options: ["Carré plein", "Triangle plein", "Triangle vide", "Cercle vide"] },
  11: { text: "Que vient ensuite ? 3, 7, 15, 31, 63, ___", options: ["95", "111", "127", "120"] },
  12: { text: "Quel nombre N'appartient PAS à la série ? 16, 25, 36, 42, 49, 64", options: ["25", "36", "42", "49"] },
  13: { text: "Chaque ligne totalise 15. Ligne 1 : 8, 4, 3. Ligne 2 : 9, 2, 4. Ligne 3 : 6, 5, ___.", options: ["3", "4", "5", "6"] },
  14: { text: "Que vient ensuite dans cette séquence de nombres premiers ? 2, 3, 5, 7, 11, 13, ___", options: ["15", "17", "19", "14"] },
  15: { text: "Une flèche pointant vers le haut tourne de 90° dans le sens horaire à chaque étape. À l'étape 5 (après 4 rotations), la flèche pointe :", options: ["Vers le haut", "Vers la droite", "Vers le bas", "Vers la gauche"] },
  16: { text: "Que vient ensuite ? AB, DE, GH, JK, ___", options: ["MN", "LM", "NO", "NP"] },
  17: { text: "Une grille : Colonne 1 = cercles, Colonne 2 = carrés, Colonne 3 = triangles. Lignes 1/2/3 = grand/moyen/petit. Qu'y a-t-il en ligne 3, colonne 2 ?", options: ["Grand cercle", "Petit triangle", "Petit carré", "Carré moyen"] },
  18: { text: "Que vient ensuite ? 100, 50, 25, 12.5, ___", options: ["5", "6.25", "10", "6"] },
  19: { text: "Quelle forme est l'intruse si toutes les autres ont exactement 4 côtés ? Carré · Rectangle · Losange · Trapèze · Pentagone", options: ["Carré", "Rectangle", "Losange", "Pentagone"] },
  20: { text: "Que vient ensuite ? 1, 4, 13, 40, ___", options: ["100", "121", "80", "130"] },
  21: { text: "Une grille 3×3 contient les chiffres 1, 2 et 3 une fois par ligne et par colonne. Ligne 1 : 1,2,3. Ligne 2 : 3,1,2. Ligne 3 : 2,_,1.", options: ["1", "2", "3", "4"] },
  22: { text: "Que vient ensuite ? A1, B4, C9, D16, ___", options: ["E20", "E25", "F25", "E24"] },
  23: { text: "Motif de couleurs : Rouge, Bleu, Vert, Rouge, Bleu, Vert, Rouge, Bleu, ___", options: ["Rouge", "Bleu", "Vert", "Jaune"] },
  24: { text: "Règle de la grille numérique : chaque nombre double le long de la ligne. Ligne 1 : 2, 4, 8. Ligne 2 : 3, 6, 12. Ligne 3 : 5, 10, ___.", options: ["15", "18", "20", "25"] },
  25: { text: "Que vient ensuite ? 1, 2, 4, 7, 11, 16, ___", options: ["20", "21", "22", "23"] },
};
