export const TRANSLATION_STATUS = "draft" as const;

export const AQ_QUESTIONS_FR: Record<number, { text: string }> = {
  1:  { text: "Face à une situation difficile au travail, je pense pouvoir influencer le résultat." },
  2:  { text: "Quand quelque chose se passe mal, je me demande ce que j'aurais pu faire différemment, même si ce n'était pas de ma faute." },
  3:  { text: "Quand je subis un revers au travail, cela tend à affecter négativement ma vie personnelle aussi." },
  4:  { text: "Quand je subis un revers majeur, j'en ressens les effets négatifs pendant longtemps après." },
  5:  { text: "Je sens que j'ai un réel pouvoir pour influencer la façon dont les défis de ma vie se résolvent." },
  6:  { text: "J'assume une responsabilité personnelle pour améliorer les situations, même quand d'autres ont créé le problème." },
  7:  { text: "Les problèmes dans un domaine de ma vie ont tendance à déborder sur d'autres domaines." },
  8:  { text: "Il me faut beaucoup de temps pour me remettre après une épreuve." },
  9:  { text: "Même dans des situations chaotiques, je trouve quelque chose qui est sous mon contrôle." },
  10: { text: "Je me tiens responsable des résultats dans ma vie." },
  11: { text: "Un seul échec me fait souvent douter de mes capacités dans des domaines complètement différents." },
  12: { text: "L'impact des problèmes dans ma vie a tendance à perdurer bien au-delà de l'événement initial." },
  13: { text: "Quand les choses tournent mal, je me concentre sur ce que je peux faire différemment plutôt que de me sentir impuissant(e)." },
  14: { text: "Quand mon équipe échoue, j'examine ma propre contribution indépendamment du rôle des autres." },
  15: { text: "Quand quelque chose se passe mal, cela tend à assombrir le reste de ma journée dans d'autres domaines aussi." },
  16: { text: "Je m'inquiète souvent que les difficultés actuelles me poursuivent longtemps dans le futur." },
  17: { text: "Je fais confiance à ma capacité à traverser des circonstances difficiles." },
  18: { text: "Je trouve rarement des excuses quand les choses ne se passent pas comme prévu." },
  19: { text: "Les difficultés dans ma vie professionnelle affectent significativement mes relations avec mes amis et ma famille." },
  20: { text: "Quand quelque chose de mauvais arrive, j'ai tendance à croire que cela m'affectera très longtemps." },
  21: { text: "Je me sens rarement totalement impuissant(e) face à un obstacle majeur." },
  22: { text: "Je prends activement des mesures pour résoudre les problèmes plutôt que d'attendre que d'autres les règlent." },
  23: { text: "Quand je fais face à l'adversité, cela mine ma confiance dans de nombreux autres domaines." },
  24: { text: "J'ai du mal à envisager un futur où les défis actuels seront résolus." },
  25: { text: "Je crois que mes actions font une réelle différence quand l'adversité frappe." },
  26: { text: "Je me sens personnellement responsable d'améliorer les situations difficiles que je rencontre." },
  27: { text: "Je constate qu'un problème a tendance à créer une réaction en chaîne d'autres problèmes dans ma vie." },
  28: { text: "Après un échec, il me faut un temps considérable avant de me sentir redevenir moi-même." },
  29: { text: "Quand les circonstances sont accablantes, j'identifie tout de même des choses sur lesquelles agir." },
  30: { text: "J'assume ma part dans les revers, même quand des facteurs externes ont joué un rôle important." },
  31: { text: "Un revers dans une relation affecte souvent la façon dont j'interagis avec d'autres personnes." },
  32: { text: "J'ai souvent l'impression que les effets de l'adversité dans ma vie sont permanents ou quasi permanents." },
  33: { text: "Je me sens capable de gérer la plupart des défis qui se présentent à moi." },
  34: { text: "Face à l'adversité, mon premier réflexe est de me demander ce que je peux faire pour améliorer la situation." },
  35: { text: "Quand les choses tournent mal, j'ai tendance à sentir que tout s'effondre dans ma vie." },
  36: { text: "Face à une situation difficile, j'ai tendance à croire qu'elle durera très longtemps." },
  37: { text: "Je me concentre sur ce que je peux changer plutôt que de m'attarder sur ce que je ne peux pas." },
  38: { text: "Je m'impose des standards élevés dans ma façon de répondre aux défis." },
  39: { text: "L'adversité dans une partie de ma vie rend difficile mon bon fonctionnement dans d'autres parties." },
  40: { text: "Les épreuves que je traverse me semblent avoir un impact durable et permanent sur ma vie." },
};
