export const TRANSLATION_STATUS = "draft" as const;

export const CS_QUESTIONS_FR: Record<number, { text: string }> = {
  1:  { text: "J'organise mes communications écrites avec une structure claire avant de rédiger." },
  2:  { text: "Je relis attentivement mes écrits avant de les envoyer." },
  3:  { text: "J'adapte le ton et le degré de formalité de mes écrits au destinataire." },
  4:  { text: "Mes écrits manquent souvent de clarté ou sont difficiles à suivre pour les autres." },
  5:  { text: "J'utilise un langage précis à l'écrit pour éviter les malentendus." },
  6:  { text: "Je garde mes messages écrits concis sans omettre d'informations importantes." },
  7:  { text: "J'ai du mal à exprimer des idées complexes clairement à l'écrit." },
  8:  { text: "Je choisis le format écrit le plus adapté (e-mail, rapport, note) selon la situation." },
  9:  { text: "Je m'assure que le message clé est clairement énoncé dès le début de mes communications écrites." },
  10: { text: "Je parle clairement et à un rythme adapté à mon audience." },
  11: { text: "J'organise mes propos de façon logique avant de parler." },
  12: { text: "Je suis à l'aise pour prendre la parole lors des réunions." },
  13: { text: "J'ai tendance à digresser ou à perdre le fil de mes idées en parlant." },
  14: { text: "J'adapte ma façon de parler selon mon interlocuteur." },
  15: { text: "J'exprime mon désaccord ou des idées alternatives avec respect et clarté." },
  16: { text: "J'évite souvent de m'exprimer en groupe même lorsque j'ai quelque chose de pertinent à dire." },
  17: { text: "Je peux résumer un sujet complexe en termes simples et accessibles si nécessaire." },
  18: { text: "J'utilise des exemples pertinents pour rendre mes explications orales plus claires." },
  19: { text: "J'accorde toute mon attention à mon interlocuteur et j'évite les distractions." },
  20: { text: "Je pose des questions de clarification lorsque je ne suis pas certain(e) d'avoir bien compris." },
  21: { text: "Je peux me rappeler avec précision les points clés d'une conversation après coup." },
  22: { text: "Mon esprit vagabonde souvent lorsque quelqu'un d'autre parle." },
  23: { text: "J'écoute pour comprendre plutôt que simplement pour préparer ma réponse." },
  24: { text: "Je perçois les signaux émotionnels dans la voix de quelqu'un, pas seulement ses mots." },
  25: { text: "J'interromps les autres avant qu'ils aient terminé leur propos." },
  26: { text: "Je reformule ce que j'ai entendu pour confirmer ma compréhension." },
  27: { text: "Je peux suivre des instructions orales détaillées sans avoir besoin qu'on me les répète." },
  28: { text: "J'ai conscience de la façon dont mon langage corporel peut affecter le message que je communique." },
  29: { text: "Je maintiens un contact visuel approprié en parlant ou en écoutant." },
  30: { text: "Je remarque les signaux non verbaux qui indiquent ce que ressent une personne." },
  31: { text: "J'ai du mal à interpréter avec précision les expressions faciales ou le langage corporel." },
  32: { text: "J'utilise naturellement des gestes et des expressions faciales pour renforcer mon message oral." },
  33: { text: "Mon langage corporel est cohérent avec ce que je dis." },
  34: { text: "Je n'ai généralement pas conscience de l'image physique que je renvoie en conversation." },
  35: { text: "Je peux identifier quand les signaux non verbaux de quelqu'un contredisent ce qu'il dit." },
};
