export const TRANSLATION_STATUS = "draft" as const;

export const CSERV_QUESTIONS_FR: Record<number, { text: string; options: [string, string, string, string] }> = {
  // Empathy (9)
  1:  { text: "Un client appelle, extrêmement contrarié par un retard de commande. Quelle est votre première action ?", options: ["Expliquer immédiatement les raisons opérationnelles du retard", "Reconnaître à quel point cela doit être frustrant et présenter des excuses sincères avant de demander le moindre détail", "Transférer l'appel à un responsable qui traite les réclamations", "Demander le numéro de commande pour vérifier le statut tout de suite"] },
  2:  { text: "Un client dit : « Personne dans votre entreprise ne m'écoute jamais. » Quelle est la meilleure réponse ?", options: ["« Je suis désolé(e) que vous ressentiez cela — laissez-moi vérifier votre compte. »", "« Je veux m'assurer qu'aujourd'hui sera différent. Dites-moi ce qui se passe, je vous accorde toute mon attention. »", "Défendre le bilan de service de votre entreprise avec des faits", "S'excuser et transférer immédiatement à un agent senior sans échanger davantage"] },
  3:  { text: "Quelle réponse démontre le mieux une empathie sincère envers un client frustré ?", options: ["« Je comprends. »", "« Cela n'aurait pas dû arriver — il est tout à fait normal que vous soyez frustré(e), et je veux résoudre cela pour vous. »", "« Tout le monde fait des erreurs — notre équipe n'est que humaine. »", "« Vous n'êtes pas le premier client à qui cela arrive, nous avons donc une procédure pour cela. »"] },
  4:  { text: "Un client est contrarié parce qu'un produit sur lequel il comptait a échoué lors d'un événement important. Quelle est la meilleure réponse ?", options: ["Passer directement au dépannage — c'est ce dont il a besoin", "Proposer immédiatement un remboursement ou un remplacement", "Reconnaître d'abord l'impact émotionnel : « Je suis vraiment désolé(e) que cela soit arrivé à un moment aussi important pour vous »", "Expliquer les limites déclarées du produit et les conditions de garantie"] },
  5:  { text: "Un client dit qu'il est gêné de ne pas avoir compris comment utiliser votre produit. Quelle est la meilleure réponse ?", options: ["Le rassurer en lui disant que le produit est simple pour la plupart des utilisateurs", "Lui dire que de nombreux clients trouvent exactement cette étape confuse et proposer de la lui expliquer tout de suite", "Envoyer un lien vers le guide d'utilisation à consulter", "Transférer au support technique"] },
  6:  { text: "Comment démontrer au mieux de l'empathie dans une réponse écrite au service client ?", options: ["Commencer par « Cher client » et passer directement à la résolution", "Commencer par reconnaître spécifiquement l'expérience du client, puis traiter le problème", "Utiliser un langage formel et professionnel en permanence pour transmettre de la compétence", "Lister clairement et efficacement toutes les étapes que le client doit suivre pour résoudre son problème"] },
  7:  { text: "Un client est en colère au sujet d'une erreur de facturation sur son compte. Avant de demander toute information sur le compte, que devez-vous faire ?", options: ["Expliquer le processus de facturation pour qu'il comprenne comment cela fonctionne", "Reconnaître clairement l'erreur et affirmer que vous allez la corriger", "Lui dire que ces erreurs sont parfois inévitables dans les grands systèmes de facturation", "Transférer immédiatement au service de facturation"] },
  8:  { text: "Quelle approche construit le mieux la confiance à long terme du client ?", options: ["Toujours proposer des remises lorsqu'un client se plaint", "Répondre rapidement avec des réponses polies mais génériques", "Tenir systématiquement ses engagements et vérifier proactivement après la résolution des problèmes", "Escalader chaque réclamation à un membre senior de l'équipe pour montrer qu'elle est prise au sérieux"] },
  9:  { text: "Un appel se termine avec une résolution en place, mais le client ne semble toujours pas satisfait. Quelle est la meilleure prochaine étape ?", options: ["Clore le dossier — le problème a été techniquement résolu", "Effectuer un suivi 24 à 48 heures plus tard pour confirmer que la résolution a fonctionné et vérifier qu'il se sent désormais écouté", "Appliquer automatiquement une remise sur sa prochaine facture", "Déclencher immédiatement une enquête de satisfaction pendant que l'interaction est encore fraîche"] },
  // Problem Resolution (9)
  10: { text: "Un client signale un produit défectueux. Quelle est la première étape la plus efficace ?", options: ["S'excuser et proposer immédiatement un remboursement complet ou un remplacement", "Recueillir les détails du défaut — ce qui s'est passé, quand, comment cela l'a affecté et quel résultat il attend", "Dire au client de retourner le produit via la procédure standard", "Transférer à une équipe spécialisée sans recueillir la moindre information au préalable"] },
  11: { text: "Un client demande un remboursement que votre politique ne couvre normalement pas. Quelle est la meilleure approche ?", options: ["Refuser immédiatement en citant votre politique mot pour mot", "Reconnaître pleinement la situation, vérifier si une exception s'applique et expliquer clairement toutes les options disponibles", "Proposer un avoir sans explorer la situation dans son ensemble", "Escalader sans avoir recueilli au préalable tous les faits pertinents"] },
  12: { text: "Vous avez résolu le problème d'un client mais n'êtes pas totalement certain(e) que la solution tiendra. Que faites-vous ?", options: ["Dire au client que le problème est définitivement et durablement résolu", "Être transparent : expliquer ce que vous avez fait et fixer un délai pour confirmer que le problème est résolu", "Clore le ticket et attendre de voir s'il vous recontacte", "Transmettre le ticket à une équipe technique et clore votre implication"] },
  13: { text: "Un client vous contacte pour un problème complexe nécessitant l'intervention de plusieurs équipes internes. Quelle est la meilleure approche ?", options: ["Transférer à la première équipe disponible et la laisser coordonner", "Prendre personnellement en charge le problème, coordonner en interne et tenir le client informé à chaque étape jusqu'à la résolution complète", "Demander au client de contacter directement chaque équipe concernée", "Demander au client de soumettre son problème par écrit avant toute action"] },
  14: { text: "Un client vous a contacté pour la troisième fois au sujet du même problème récurrent. Que devez-vous faire différemment ?", options: ["Résoudre le problème de la même manière qu'avant — le processus a fonctionné par le passé", "Résoudre le problème immédiat ET escalader en interne pour enquêter sur la cause profonde et la traiter afin d'éviter toute récidive", "Proposer une remise pour le désagrément et clore rapidement le ticket", "Demander au client de modifier son comportement pour éviter de déclencher le problème"] },
  15: { text: "Après avoir résolu le problème d'un client, quelle action apporte le plus de valeur ?", options: ["Clore immédiatement le dossier — votre temps est nécessaire pour d'autres clients", "Confirmer que la résolution répond aux attentes du client et demander s'il a besoin d'autre chose avant de clore", "Demander au client de laisser un avis sur l'interaction", "Envoyer une offre promotionnelle en geste de bonne volonté"] },
  16: { text: "Un client souhaite une résolution que vos systèmes ne peuvent pas fournir actuellement. Quelle est la meilleure réponse ?", options: ["Lui dire que c'est techniquement impossible et clore le dossier", "Reconnaître clairement la limitation, expliquer ce que vous pouvez faire dès maintenant et fixer des attentes réalistes sur ce qui est possible et pour quand", "Promettre ce qu'il demande pour le satisfaire sur l'instant", "Rejeter la faute sur un autre service pour cette limitation"] },
  17: { text: "Deux clients vous contactent simultanément avec des problèmes urgents. Comment gérez-vous cela ?", options: ["Essayer de traiter les deux en temps réel simultanément sur deux canaux", "Accuser réception immédiatement pour les deux, fixer un délai de réponse réaliste pour chacun et prioriser selon la gravité", "Demander au client le moins urgent de rappeler plus tard", "Escalader immédiatement les deux à un responsable"] },
  18: { text: "Un client est en colère au sujet de la lenteur de la résolution et exige une action immédiate. Quelle est la meilleure réponse ?", options: ["Lui dire d'être patient — les bonnes résolutions prennent du temps", "Expliquer clairement quelle action vous entreprenez à l'instant et donner un délai réaliste et précis pour la prochaine mise à jour", "Escalader immédiatement pour le sortir de votre file d'attente", "Proposer une compensation financière sans discuter davantage de la situation"] },
  // Communication (9)
  19: { text: "Un client pose une question dont vous ne connaissez pas la réponse. Quelle est la meilleure réponse ?", options: ["Donner votre meilleure estimation avec assurance pour qu'il se sente aidé immédiatement", "Dire « Je ne sais pas » et mettre fin à l'échange", "« Excellente question — laissez-moi trouver la bonne réponse et je reviens vers vous dans [délai réaliste précis]. »", "Transférer à un autre agent sans fournir de contexte à personne"] },
  20: { text: "Un client utilise un langage technique que vous ne connaissez pas. Quelle est la meilleure action ?", options: ["Faire semblant de comprendre et poursuivre l'échange", "Poser une question de clarification : « Pourriez-vous m'aider à comprendre ce que vous entendez par [terme] afin que je puisse vous aider le plus précisément possible ? »", "Transférer immédiatement à un spécialiste technique", "Demander au client de simplifier son langage avant de continuer"] },
  21: { text: "Quelle réponse écrite clôt le mieux un échange avec le service client ?", options: ["« N'hésitez pas à nous recontacter s'il y a autre chose. »", "« Votre problème a été enregistré dans notre système. »", "« J'ai résolu [le problème spécifique]. Si vous avez des questions sur la solution ou rencontrez autre chose, n'hésitez pas à nous recontacter. »", "« Merci de nous avoir contactés aujourd'hui. »"] },
  22: { text: "Un client répond avec colère à une résolution que vous avez proposée. Quelle est la meilleure approche de communication ?", options: ["Adopter la même énergie pour montrer que vous prenez cela au sérieux", "Utiliser un ton calme et empathique et demander quel résultat lui permettrait de considérer le problème comme entièrement résolu", "Répéter votre résolution initiale de façon plus ferme et plus claire", "Escalader sans échanger davantage"] },
  23: { text: "Vous devez annoncer une mauvaise nouvelle à un client — sa commande a été annulée. Quelle est la meilleure approche ?", options: ["Annoncer immédiatement la mauvaise nouvelle par respect pour son temps", "Noyer la nouvelle dans un long message pour en atténuer l'impact", "Reconnaître son expérience, annoncer la nouvelle honnêtement et clairement, puis se concentrer immédiatement sur ce que vous pouvez faire pour aider", "Retarder l'annonce et voir si la situation se résout d'elle-même"] },
  24: { text: "Quand est-il approprié d'utiliser un jargon technique avec un client ?", options: ["Toujours — cela établit crédibilité et expertise", "Jamais — cela rebute toujours les clients", "Seulement lorsque le client a lui-même utilisé un langage technique, indiquant qu'il est à l'aise avec", "Seulement lorsque vous devez terminer rapidement l'échange"] },
  25: { text: "Vous gérez un chat en direct avec plusieurs clients et l'un d'eux met plusieurs minutes à répondre. Quelle est la meilleure action ?", options: ["Fermer le chat après deux minutes d'inactivité", "Se concentrer entièrement sur les clients réactifs et revenir quand le client silencieux écrit", "Envoyer un bref message pour vérifier qu'il est toujours là et confirmer que vous êtes prêt quand il le sera", "Escalader après une minute de silence"] },
  26: { text: "Un client appelle au sujet d'une réclamation qu'il a déjà envoyée par e-mail. Que devez-vous faire en premier ?", options: ["Lui demander de répéter toute l'histoire depuis le début", "Consulter son e-mail avant qu'il ait fini d'expliquer afin de pouvoir faire référence à son contact précédent et lui éviter de se répéter", "Transférer à la personne qui a traité l'e-mail initial", "Lui demander pourquoi il appelle alors qu'il a déjà envoyé un e-mail"] },
  27: { text: "Vous avez expliqué une résolution, mais le client n'a pas compris et a reposé la même question. Quelle est la meilleure réponse ?", options: ["Copier-coller votre réponse précédente mot pour mot", "S'excuser et essayer une explication différente ou un format différent qui pourrait mieux lui convenir", "Lui demander pourquoi il ne comprend pas votre réponse", "Transférer à un agent senior qui pourrait mieux l'expliquer"] },
  // Patience (8)
  28: { text: "Un client explique son problème très lentement et avec un luxe de détails excessif. Quelle est la meilleure approche ?", options: ["L'interrompre poliment et lui demander d'aller droit au but rapidement", "Le laisser terminer — il partage peut-être un contexte qui s'avérera important — puis résumer ce que vous avez compris", "Faire plusieurs choses à la fois pendant qu'il parle pour utiliser votre temps efficacement", "Lui demander d'écrire un e-mail à la place pour qu'il puisse structurer ses idées d'abord"] },
  29: { text: "Un client vous contacte pour la troisième fois au sujet d'un problème récurrent. Il est visiblement frustré. Comment abordez-vous cela différemment ?", options: ["Suivre le processus de résolution standard — c'est la procédure correcte", "Reconnaître explicitement le schéma : « Je constate que cela s'est déjà produit et c'est inacceptable. Je vais personnellement m'assurer que ce soit résolu aujourd'hui. »", "Proposer immédiatement un remboursement pour rompre le cycle sans enquête plus approfondie", "Demander au client d'être patient pendant que le système sous-jacent se met à jour"] },
  30: { text: "Un client utilise un langage grossier ou vulgaire. Quelle est la meilleure réponse ?", options: ["Utiliser un langage tout aussi ferme pour montrer que vous n'êtes pas intimidé", "Mettre fin immédiatement à l'échange", "Rester calme, reconnaître sa frustration, chercher à résoudre le problème sous-jacent et, si le langage persiste, expliquer clairement ce dont vous avez besoin pour poursuivre l'échange de manière productive", "Ignorer complètement le langage et continuer comme si de rien n'était"] },
  31: { text: "Un client pose une question qui semble simple mais dont la réponse est complexe et nuancée. Que faites-vous ?", options: ["Donner la réponse rapide et simplifiée pour gagner du temps pour les deux parties", "Prendre le temps nécessaire pour donner une réponse complète et précise, même si cela prend plus de temps", "Le diriger vers la FAQ ou la base de connaissances", "Transférer à un spécialiste pour éviter de donner une réponse incomplète"] },
  32: { text: "De nombreux clients attendent, mais le client actuel parle encore et son problème n'est pas encore résolu. Quelle est l'action la plus appropriée ?", options: ["Presser le client actuel vers une conclusion", "Accorder au client actuel le temps dont il a besoin pour se sentir écouté — puis trouver des moyens de traiter la file d'attente plus efficacement ensuite", "Mettre le client en attente sans le prévenir", "Le transférer à un collègue en pleine interaction"] },
  33: { text: "Un client pose plusieurs fois la même question de clarification parce qu'il ne comprend pas vos réponses. Quelle est la meilleure action ?", options: ["Copier-coller votre réponse précédente — il doit la lire plus attentivement", "S'excuser et essayer un format ou une approche d'explication différente qui pourrait mieux lui convenir", "Lui demander pourquoi il continue à poser la même question", "Transférer à un agent senior pour gérer le malentendu"] },
  34: { text: "Un client se défoule longuement avant d'arriver à sa demande réelle. Quelle est la meilleure approche ?", options: ["L'interrompre poliment après 30 secondes pour rediriger vers le problème concret", "Le laisser terminer, puis répondre au contenu émotionnel avant de passer à la question pratique", "Lui demander à répétition de se concentrer sur le problème précis", "Le mettre en attente jusqu'à ce qu'il se soit calmé"] },
  35: { text: "Après un échange long et difficile, le client vous remercie sincèrement et dit que vous avez restauré sa confiance envers votre entreprise. Quelle est la réponse la plus efficace ?", options: ["Dire « Pas de problème » et clore l'échange", "Reconnaître que vous étiez heureux d'aider, confirmer brièvement les prochaines étapes et lui souhaiter sincèrement le meilleur", "Demander s'il serait disposé à laisser un avis positif", "Lui offrir une remise sur son prochain achat en récompense de sa patience"] },
};
