export const TRANSLATION_STATUS = "draft" as const;

export const EI_QUESTIONS_FR: Record<number, { text: string }> = {
  1: { text: "Je peux généralement nommer l'émotion que je ressens pendant qu'elle se produit." },
  2: { text: "Je remarque comment mon humeur affecte ma façon de communiquer avec les autres." },
  3: { text: "Je comprends les déclencheurs personnels qui peuvent me rendre sur la défensive." },
  4: { text: "J'agis souvent sans remarquer ce que je ressens avant coup." },
  5: { text: "Je peux reconnaître quand le stress affecte mon jugement." },
  6: { text: "Je recherche des retours pour comprendre comment les autres me perçoivent." },
  7: { text: "Je peux distinguer les faits de mon interprétation émotionnelle d'une situation." },
  8: { text: "Je comprends rarement pourquoi certaines situations me contrarient." },
  9: { text: "Je peux rester suffisamment calme pour réagir avec réflexion en cas de tension." },
  10: { text: "Lorsque je me sens frustré(e), je marque une pause avant de parler ou d'agir." },
  11: { text: "Je me remets rapidement après une interaction difficile." },
  12: { text: "Je dis des choses que je regrette ensuite quand la pression est forte." },
  13: { text: "Je peux ajuster mon comportement quand ma première réaction serait inutile." },
  14: { text: "Je gère les changements inattendus sans perdre ma concentration." },
  15: { text: "Je gère les conflits sans les envenimer inutilement." },
  16: { text: "De petits revers perturbent souvent mon humeur pour le reste de la journée." },
  17: { text: "Je reste engagé(e) envers des objectifs importants même quand les progrès sont lents." },
  18: { text: "Je peux trouver du sens dans un travail difficile ou répétitif." },
  19: { text: "Je me fixe des standards personnels qui me poussent à progresser." },
  20: { text: "Je perds rapidement de l'énergie quand la reconnaissance n'est pas immédiate." },
  21: { text: "Je cherche des leçons quand quelque chose ne se passe pas comme prévu." },
  22: { text: "Je reste optimiste tout en restant réaliste face aux obstacles." },
  23: { text: "Je prends des initiatives sans attendre qu'on me dicte chaque étape suivante." },
  24: { text: "J'évite les objectifs difficiles si le succès est incertain." },
  25: { text: "Je peux généralement sentir quand quelqu'un est mal à l'aise même s'il ne le dit pas." },
  26: { text: "J'écoute ce que les gens ressentent autant que ce qu'ils disent." },
  27: { text: "Je considère comment les décisions peuvent affecter des personnes aux besoins différents." },
  28: { text: "J'ai du mal à comprendre pourquoi les gens réagissent différemment de moi." },
  29: { text: "Je pose des questions avant de supposer que je comprends le point de vue d'une autre personne." },
  30: { text: "Je remarque quand quelqu'un a besoin de soutien, d'espace ou d'encouragement." },
  31: { text: "Je peux être en désaccord avec quelqu'un tout en respectant son vécu." },
  32: { text: "Quand les gens sont émotifs, j'ai tendance à minimiser leurs préoccupations." },
  33: { text: "Je construis la confiance en communiquant clairement et de façon constante." },
  34: { text: "Je peux adapter mon style de communication à différentes personnes." },
  35: { text: "J'aide les groupes à avancer vers un accord en cas de désaccord." },
  36: { text: "J'évite les conversations importantes quand elles risquent de devenir inconfortables." },
  37: { text: "Je donne des retours de manière directe et respectueuse." },
  38: { text: "Je maintiens des relations professionnelles même après un conflit." },
  39: { text: "Je peux influencer les autres sans m'appuyer sur l'autorité ou la pression." },
  40: { text: "J'ai du mal à réparer les relations après des malentendus." },
};
