export const TRANSLATION_STATUS = "draft" as const;

export const IE_QUESTIONS_FR: Record<number, { text: string; options: [string, string, string, string] }> = {
  // Honesty (8)
  1:  { text: "Vous avez commis une erreur dans un rapport déjà partagé avec la direction. Que faites-vous ?", options: ["Espérer que personne ne le remarque et la corriger discrètement dans la prochaine version", "Informer immédiatement les personnes concernées, corriger l'erreur et expliquer ce qui s'est passé", "Attendre de voir si quelqu'un le signale avant d'agir", "Demander à un collègue de confiance de le signaler anonymement à votre place"] },
  2:  { text: "Votre responsable demande un point d'avancement sur le projet, mais celui-ci a pris du retard. Que dites-vous ?", options: ["Indiquer que les choses sont « globalement dans les temps » pour éviter un examen plus approfondi", "Donner un compte-rendu honnête de la situation réelle, des raisons du retard et de votre plan pour y remédier", "Fournir une mise à jour vague qui n'engage sur rien de précis", "Dire que vous enverrez une mise à jour écrite plus tard et retarder la conversation"] },
  3:  { text: "Lors d'une présentation commerciale, un client pose une question sur une fonctionnalité qui n'existe pas encore. Que faites-vous ?", options: ["Confirmer que la fonctionnalité existe — elle sera probablement prête avant qu'il en ait besoin", "Lui dire qu'elle est « en cours de développement » sans préciser quand ni si elle sera disponible", "Être honnête : la fonctionnalité n'existe pas encore, partager ce qui est prévu sur la feuille de route et le laisser décider avec des informations exactes", "Changer habilement de sujet avant qu'il ne relance"] },
  4:  { text: "Vous êtes fortement en désaccord avec une conclusion clé du rapport d'un collègue qui en est manifestement fier. Que faites-vous ?", options: ["Lui dire que le rapport est excellent pour préserver la relation", "Faire part de votre préoccupation en privé et de manière constructive, avec des éléments clairs à l'appui de votre point de vue", "Ne rien dire tant que personne d'autre ne soulève le problème", "Exprimer publiquement votre préoccupation en réunion d'équipe pour qu'elle soit entendue"] },
  5:  { text: "On vous demande d'estimer le délai d'achèvement d'un projet et vous êtes véritablement incertain(e). Que dites-vous ?", options: ["Donner une estimation précise et assurée même sans base fiable pour la justifier", "Fournir une fourchette réaliste fondée sur ce que vous savez et signaler clairement les principales incertitudes", "Dire que cela ne peut pas être estimé sans plus d'informations et refuser de vous engager", "Donner le délai que vous pensez que votre responsable veut entendre"] },
  6:  { text: "Un client vous demande votre avis honnête sur le produit d'un concurrent. Vous savez qu'il est en réalité plutôt bon. Que dites-vous ?", options: ["Rejeter le produit du concurrent sans analyse équitable", "Donner une évaluation honnête et équilibrée — reconnaître les points forts du concurrent et préciser où votre solution apporte davantage de valeur pour leurs besoins spécifiques", "Dire que la politique de l'entreprise vous empêche de commenter les concurrents", "Partager une histoire négative trompeuse sur le concurrent sans preuve"] },
  7:  { text: "En remplissant votre relevé d'heures, vous remarquez avoir facturé plus d'heures à un projet client que celles réellement travaillées. Que faites-vous ?", options: ["Laisser tel quel — la différence est minime et s'équilibrera avec le temps", "Corriger le relevé pour refléter les heures réellement travaillées", "Enregistrer les heures initialement prévues et vous rattraper sur le prochain projet", "Demander informellement à un responsable si c'est acceptable de laisser tel quel"] },
  8:  { text: "Un collègue vous confie quelque chose de personnel en toute confidentialité. Quelqu'un d'autre vous demande ensuite si vous êtes au courant de quelque chose. Que faites-vous ?", options: ["Partager l'information — votre collègue aurait dû faire plus attention à qui il en parlait", "Respecter la confidentialité : dire à l'autre personne que vous n'avez rien à partager", "Partager une version de l'information que vous jugez moins sensible", "Demander la permission de votre collègue avant de répondre à l'autre personne"] },
  // Accountability (8)
  9:  { text: "Un projet que vous dirigiez n'a pas atteint ses objectifs. Votre équipe demande ce qui s'est passé. Que faites-vous ?", options: ["Attribuer principalement l'échec à des facteurs externes hors de votre contrôle", "Assumer honnêtement ce dont vous étiez responsable, reconnaître ce qui n'a pas fonctionné et partager ce que vous en avez retenu", "Identifier quel membre de l'équipe a le plus contribué à l'échec", "Dire que vous préparerez un rapport détaillé mais le repousser indéfiniment"] },
  10: { text: "Vous avez donné à un collègue un conseil incorrect qui a directement causé une erreur significative. Quelle est la réponse la plus appropriée ?", options: ["Laisser le collègue assumer la responsabilité — c'est lui qui a pris la décision finale", "Reconnaître clairement que votre conseil était erroné et prendre des mesures actives pour aider à corriger la situation", "Proposer des conseils pour corriger l'erreur sans mentionner votre rôle dans celle-ci", "Revoir discrètement votre propre façon de conseiller sans informer le collègue de ce qui s'est passé"] },
  11: { text: "Vous vous étiez engagé(e) à assister à une réunion importante mais vous l'avez oubliée et manquée entièrement. Que faites-vous ?", options: ["Attendre de voir si quelqu'un vous contacte à ce sujet", "Vous excuser auprès des personnes concernées, découvrir ce que vous avez manqué et assumer les actions de suivi nécessaires", "Dire que vous traitiez une urgence client", "Vous excuser seulement si quelqu'un vous interpelle directement sur votre absence"] },
  12: { text: "Vous découvrez qu'un processus dont vous êtes responsable produit des erreurs depuis plusieurs semaines. Comment réagissez-vous ?", options: ["Corriger les erreurs discrètement sans en informer votre responsable ou les parties prenantes", "Informer votre responsable, quantifier l'ampleur du problème, corriger le processus et mettre en place un contrôle pour éviter que cela se reproduise", "Poursuivre avec le processus existant et examiner les erreurs lors du prochain rapport mensuel prévu", "Chercher qui a mis en place le processus initial et lui attribuer la responsabilité"] },
  13: { text: "On vous demande de prendre en charge une tâche largement en dehors de votre domaine d'expertise. Que faites-vous ?", options: ["Accepter sans mentionner vos limites et espérer trouver une solution", "Refuser — ce n'est pas votre domaine et vous ne devriez pas prendre de risques avec votre réputation", "Accepter tout en étant honnête sur vos limites, et identifier proactivement où vous aurez besoin de soutien ou de conseils", "Accepter la tâche mais sous-traiter les parties inconnues sans en informer votre responsable"] },
  14: { text: "Votre responsable félicite un travail qui a été considérablement soutenu par un collègue. Que faites-vous ?", options: ["Accepter les félicitations — vous avez tout de même apporté une contribution réelle", "Créditer clairement et précisément la contribution de votre collègue auprès de votre responsable", "Ne rien dire à votre collègue mais remercier votre responsable en privé", "Demander à votre responsable de reconnaître publiquement vous deux la prochaine fois"] },
  15: { text: "Vous prenez du retard sur un engagement et il devient clair que vous manquerez l'échéance. Quelle est la bonne réponse ?", options: ["Continuer à travailler et essayer de rattraper le retard avant que quelqu'un ne le remarque", "Informer immédiatement la partie prenante concernée, expliquer ce qui s'est passé et convenir d'un plan révisé réaliste", "Soumettre ce que vous avez terminé à l'échéance même si c'est substantiellement incomplet", "Demander à un collègue de soumettre quelque chose en votre nom"] },
  16: { text: "Une décision d'équipe à laquelle vous avez participé s'est révélée être un mauvais choix. Vous aviez des réserves mais ne les aviez pas exprimées à l'époque. Quelle est votre responsabilité ?", options: ["Aucune — vous n'avez pas pris la décision finale", "Vous partagez une part de responsabilité et devriez reconnaître que vous auriez pu exprimer vos préoccupations à l'époque", "La pleine responsabilité incombe à celui qui a pris la décision finale", "Vous devriez maintenant vous concentrer sur qui aurait dû signaler le problème avant la décision"] },
  // Ethics (7)
  17: { text: "Vous découvrez qu'un collègue soumet des notes de frais gonflées. Que faites-vous ?", options: ["Ignorer cela — ce n'est pas votre responsabilité et vous ne voulez pas créer de conflit", "Le couvrir — c'est un ami et les montants ne sont pas importants", "Le signaler par le canal interne approprié, comme votre responsable ou les RH", "Le confronter publiquement devant l'équipe pour décourager un comportement similaire"] },
  18: { text: "Votre responsable vous met la pression pour dénaturer des données dans un rapport client afin que les résultats paraissent meilleurs qu'ils ne le sont. Que faites-vous ?", options: ["Suivre les instructions de votre responsable — il a l'autorité et la responsabilité du rapport", "Faire part directement de votre préoccupation à votre responsable et expliquer pourquoi vous ne pouvez pas dénaturer les données", "Modifier les données mais ajouter une nuance discrète en annexe", "Le faire cette fois-ci et soulever le problème par un autre canal ensuite"] },
  19: { text: "Un client vous offre un cadeau personnel d'une valeur dix fois supérieure à la limite acceptée par votre entreprise. Que faites-vous ?", options: ["L'accepter — cela reflète une relation client forte et précieuse", "L'accepter mais ne le divulguer à personne dans votre entreprise", "Refuser poliment, mentionner la politique de cadeaux de votre entreprise et le remercier sincèrement pour son geste", "L'accepter et le donner à une œuvre caritative pour ne pas en bénéficier personnellement"] },
  20: { text: "On vous propose l'accès à un document confidentiel de tarification d'un concurrent, transmis par quelqu'un affirmant l'avoir reçu de façon non officielle. Que faites-vous ?", options: ["L'utiliser — cela offre un avantage concurrentiel légitime pour votre entreprise", "Refuser de l'utiliser et signaler la situation à votre responsable", "L'utiliser confidentiellement au sein de votre équipe immédiate uniquement", "Demander à votre responsable si son utilisation est permise avant de décider"] },
  21: { text: "On vous demande de rédiger une référence professionnelle pour un collègue dont vous savez qu'il a mal performé. Que faites-vous ?", options: ["Rédiger une référence fortement positive — la loyauté et l'esprit d'équipe passent avant tout", "Soit refuser de rédiger la référence, soit en rédiger une qui reflète honnêtement et équitablement votre expérience professionnelle de lui", "Rédiger une référence délibérément vague qui ne confirme ni ne dément sa performance", "Écrire exactement ce qu'il vous a demandé d'inclure"] },
  22: { text: "Vous remarquez que des données d'un segment minoritaire sont exclues d'une analyse d'une manière qui modifie sensiblement les conclusions. Que faites-vous ?", options: ["Supposer qu'il s'agit d'un oubli accidentel et ne rien dire", "Soulever directement le problème auprès de la personne responsable de l'analyse", "Inclure vous-même les données dans un document séparé sans en informer personne", "Ajouter une brève note à ce sujet en annexe, loin des conclusions principales"] },
  23: { text: "Vous êtes sous pression de temps et réalisez que sauter une étape d'un contrôle de sécurité ou de conformité ferait gagner plusieurs heures. Que faites-vous ?", options: ["Sauter l'étape — un cas isolé ne causera probablement aucun tort réel", "Effectuer le contrôle intégralement malgré la pression temporelle", "Le sauter cette fois mais le noter comme quelque chose à revoir plus tard", "Demander à un collègue junior d'effectuer le contrôle pour gagner du temps"] },
  // Trustworthiness (7)
  24: { text: "Vous acceptez de terminer une tâche pour jeudi, mais dès mercredi vous savez qu'elle ne sera prête que vendredi. Que faites-vous ?", options: ["Travailler toute la nuit et espérer livrer jeudi sans en informer personne", "Informer la partie concernée dès mercredi, expliquer la raison du retard et convenir d'une nouvelle échéance", "Soumettre un travail incomplet jeudi pour respecter techniquement l'échéance", "Demander à un collègue de vous couvrir sans en informer la partie prenante"] },
  25: { text: "Un collègue partage avec vous un brouillon confidentiel en vous demandant de ne pas le diffuser. Vous le transférez accidentellement à la mauvaise personne. Que faites-vous ?", options: ["Faire comme si de rien n'était et espérer que l'autre personne n'en parle pas", "Informer immédiatement votre collègue et le destinataire involontaire, et prendre des mesures pour limiter l'impact", "Demander au destinataire involontaire de le supprimer et ne rien dire à votre collègue", "Attendre de voir si l'une des parties le signale avant d'agir"] },
  26: { text: "Vous avez accepté d'encadrer un nouveau membre de l'équipe, mais votre charge de travail est devenue écrasante. Quelle est l'action la plus digne de confiance ?", options: ["Continuer comme prévu mais sauter des séances chaque fois que d'autres priorités surgissent", "Être honnête sur votre disponibilité, renégocier l'engagement pour quelque chose de réaliste, ou trouver un mentor alternatif adapté", "Envoyer des ressources et documents de lecture par e-mail en remplacement des réunions", "Arrêter l'encadrement sans aucune explication"] },
  27: { text: "Vous recevez une information non confirmée selon laquelle un projet serait probablement annulé. Un collègue qui y a beaucoup travaillé vous demande directement si vous avez entendu quelque chose. Que faites-vous ?", options: ["Partager tout ce que vous avez entendu intégralement, même si c'est non confirmé", "Mentir et dire que vous n'avez rien entendu pour lui épargner une inquiétude inutile", "Lui dire honnêtement que vous avez entendu quelque chose, mais que c'est non confirmé, et suggérer qu'il en parle directement à la personne concernée", "Changer de sujet et éviter de répondre à la question"] },
  28: { text: "Une équipe dépend de votre analyse hebdomadaire pour prendre des décisions clés. Vous savez que la méthodologie comporte une faille mais la corriger prendrait beaucoup de temps. Que faites-vous ?", options: ["Continuer à utiliser la méthodologie défaillante — l'analyse est suffisamment bonne à des fins pratiques", "Signaler immédiatement la faille, noter son impact potentiel sur les résultats précédents et la corriger le plus rapidement possible", "La corriger discrètement sans informer personne que la méthodologie était défaillante", "Prévoir de la traiter dans la prochaine version sans signaler le problème actuel"] },
  29: { text: "On vous demande de vous engager sur une échéance de livraison dont vous n'êtes véritablement pas certain(e) de pouvoir la tenir. Quelle est la réponse la plus digne de confiance ?", options: ["Vous engager sur l'échéance demandée pour montrer votre volonté et votre intention positive", "Fournir une évaluation honnête de ce que vous pouvez réalistement livrer et pour quand, en indiquant clairement les risques ou réserves", "Vous engager sur l'échéance et alerter si vous la manquez", "Dire que vous « ferez de votre mieux » sans vous engager sur rien de précis"] },
  30: { text: "Vous réalisez que vous vous êtes involontairement attribué le mérite d'une idée provenant d'un collègue lors d'une discussion. Que faites-vous ?", options: ["Continuer ainsi puisque la situation a déjà évolué et l'attribution n'est plus claire", "Clarifier proactivement auprès des parties prenantes concernées que l'idée provenait de votre collègue", "Le dire en privé à votre collègue mais ne pas corriger publiquement", "Offrir à votre collègue un rôle plus important dans le projet en compensation indirecte"] },
};
