export const TRANSLATION_STATUS = "draft" as const;

export const LEADERSHIP_QUESTIONS_FR: Record<number, {
  text: string;
  options: [string, string, string, string, string, string];
}> = {
  1:  { text: "Une équipe n'est pas certaine de la direction d'une nouvelle initiative. Que faites-vous en premier ?", options: ["Expliquer une direction future claire et pourquoi elle est importante.", "Rencontrer chaque personne pour comprendre ses besoins de développement.", "Créer de l'apaisement et réduire la tension dans le groupe.", "Inviter l'équipe à construire le plan ensemble.", "Fixer un objectif ambitieux et montrer le rythme à suivre.", "Définir immédiatement les rôles, délais et actions requises."] },
  2:  { text: "Un membre compétent de l'équipe sous-performe. Votre première réaction est de :", options: ["Reconnecter son travail à la mission plus large.", "L'accompagner à travers ses objectifs, obstacles et compétences.", "Vérifier si des tensions personnelles ou d'équipe l'affectent.", "Demander son avis et convenir ensemble des prochaines étapes.", "Montrer à quoi ressemble une exécution solide et relever la barre.", "Donner des attentes directes et un délai ferme pour progresser."] },
  3:  { text: "Deux services sont en désaccord sur les priorités. Vous êtes le plus susceptible de :", options: ["Clarifier l'objectif commun que les deux groupes doivent soutenir.", "Aider les personnes clés à comprendre ce qu'elles peuvent apprendre du conflit.", "Réparer la confiance avant de pousser vers une décision.", "Faciliter une conversation de décision avec les deux parties.", "Concentrer tout le monde sur le résultat mesurable et la rapidité.", "Trancher et exiger l'alignement."] },
  4:  { text: "Lors du lancement d'un projet difficile, vous préférez :", options: ["Décrire la destination et laisser les gens trouver leur chemin.", "Attribuer des rôles exigeants qui aident les gens à se développer.", "Construire la confiance et le lien avant que la pression n'augmente.", "Co-construire le rythme de travail avec l'équipe.", "Fixer des standards exigeants et travailler en première ligne.", "Créer un plan serré avec des règles non négociables claires."] },
  5:  { text: "Une échéance est en danger. Quel style vous vient le plus naturellement ?", options: ["Recentrer l'équipe sur le résultat important.", "Aider ceux qui sont bloqués à apprendre à résoudre des problèmes similaires plus vite.", "Maintenir le moral pour que les gens ne se referment pas.", "Demander à l'équipe le plan de rattrapage le plus rapide et réaliste.", "Augmenter le rythme et montrer personnellement l'urgence.", "Prendre des décisions rapides et diriger l'exécution."] },
  6:  { text: "Un nouvel employé rejoint votre équipe. Vous êtes le plus susceptible de :", options: ["Montrer comment son rôle s'inscrit dans l'avenir de l'organisation.", "Construire un plan de développement avec lui.", "L'aider à se sentir accueilli et connecté.", "L'inviter tôt aux discussions d'équipe.", "Donner des exemples de travail excellent à égaler.", "Fournir des attentes et des règles précises."] },
  7:  { text: "Votre équipe doit améliorer la qualité. Vous commencez par :", options: ["Expliquer le standard de qualité comme partie d'une ambition plus large.", "Développer les compétences dont dépend la qualité.", "Créer un climat sûr pour discuter ouvertement des erreurs.", "Demander à l'équipe de diagnostiquer les causes profondes.", "Relever le standard et examiner le travail de près.", "Imposer un processus qualité plus strict."] },
  8:  { text: "En réunion, votre contribution la plus forte est généralement :", options: ["Aider les gens à voir la vue d'ensemble.", "Faire émerger des opportunités d'apprentissage et de développement.", "Maintenir un ton constructif et respectueux.", "S'assurer que toutes les voix pertinentes sont entendues.", "Pousser vers un résultat clair et des standards élevés.", "Piloter les décisions et attribuer les actions."] },
  9:  { text: "Une équipe est devenue trop confortable. Vous réagissez en :", options: ["Peignant un prochain chapitre convaincant.", "Aidant les gens à identifier des objectifs de croissance.", "Renforçant les relations pour que le changement paraisse plus sûr.", "Demandant au groupe à quoi devrait ressembler l'amélioration.", "Fixant un rythme plus exigeant.", "Changeant les attentes et exigeant leur respect."] },
  10: { text: "Une crise survient avec peu de préavis. Votre premier réflexe est de :", options: ["Rappeler à chacun l'objectif principal.", "Accompagner les personnes clés face à des exigences inhabituelles.", "Garder le groupe calme et soudé.", "Recueillir rapidement l'avis de ceux qui sont au plus près du problème.", "Agir rapidement et incarner une concentration intense.", "Prendre les commandes et donner des instructions claires."] },
  11: { text: "Vous recevez une idée audacieuse d'un membre junior de l'équipe. Vous :", options: ["La reliez à l'orientation stratégique.", "L'aidez à l'affiner et à la présenter.", "L'encouragez et protégez la sécurité psychologique.", "Invitez l'équipe à l'évaluer ouvertement.", "La testez face à un standard de haute performance.", "Décidez rapidement si elle doit avancer."] },
  12: { text: "Lorsque vous donnez un retour, vous avez tendance à insister sur :", options: ["Comment le travail soutient l'orientation future.", "Comment la personne peut en tirer une croissance.", "Comment préserver la confiance et l'assurance.", "Comment le retour peut devenir une conversation à double sens.", "Comment le travail se compare à l'excellence.", "Ce qui doit changer immédiatement."] },
  13: { text: "Un interlocuteur senior demande un plan que vous ne soutenez pas pleinement. Vous :", options: ["Reformulez autour de l'orientation à long terme.", "En faites un moment de développement pour l'équipe.", "Gérez les relations avec soin pour réduire les frictions.", "Impliquez les personnes clés dans le processus de décision.", "Vous concentrez sur l'exécution de la meilleure version possible.", "Alignez l'équipe et avancez rapidement."] },
  14: { text: "Votre équipe est divisée après un changement difficile. Vous :", options: ["Expliquez où mène le changement pour l'organisation.", "Aidez chacun à assimiler et s'adapter.", "Priorisez la reconstruction de la confiance et du sentiment d'appartenance.", "Créez des espaces pour que les gens participent aux solutions.", "Fixez rapidement de nouvelles attentes de performance.", "Clarifiez les nouvelles règles et les faites respecter."] },
  15: { text: "Lorsque vous déléguez, vous êtes le plus susceptible de :", options: ["Décrire le résultat attendu et l'objectif stratégique.", "Faire correspondre la tâche aux besoins de développement de quelqu'un.", "Tenir compte des relations et de l'équilibre de charge de travail.", "Laisser le groupe décider de la responsabilité quand c'est possible.", "La confier au plus performant pour aller vite.", "L'attribuer directement avec des exigences précises."] },
  16: { text: "L'équipe manque un objectif important. Vous vous concentrez sur :", options: ["Reconnecter tout le monde à l'objectif plus large.", "Transformer l'échec en plan d'apprentissage.", "Préserver le moral avant le prochain effort.", "Revoir les causes et solutions en groupe.", "Renforcer la discipline et l'intensité de la performance.", "L'action corrective et la responsabilisation."] },
  17: { text: "Un coéquipier souhaite davantage de responsabilités. Vous répondez en :", options: ["Montrant comment une plus grande responsabilité sert la mission.", "Créant un parcours de progression étape par étape.", "L'encourageant et en vérifiant ses besoins de soutien.", "Discutant des options avec l'équipe si cela les concerne.", "Lui donnant une mission ambitieuse et exigeante.", "Attribuant la responsabilité avec des règles claires."] },
  18: { text: "Vous avez besoin d'innovation de la part du groupe. Vous :", options: ["Fixez une vision audacieuse qui ouvre de nouvelles possibilités.", "Accompagnez les gens pour renforcer leur confiance dans de nouvelles compétences.", "Rendez l'environnement sûr pour l'expérimentation.", "Menez une idéation collaborative suivie d'un vote.", "Poussez vers des prototypes rapides et des standards élevés.", "Définissez le problème et exigez des propositions rapides."] },
  19: { text: "Lorsque la performance est solide, vous avez tendance à :", options: ["Désigner le prochain horizon stratégique.", "Demander ce que les gens veulent apprendre ensuite.", "Célébrer l'équipe et renforcer les liens.", "Inviter à réfléchir sur ce qui a fonctionné.", "Relever encore la barre.", "Verrouiller le processus qui a produit les résultats."] },
  20: { text: "Si les gens résistent à votre décision, vous avez tendance à :", options: ["Expliquer le sens et la valeur future.", "Explorer ce que la résistance révèle sur les besoins de développement.", "Écouter les préoccupations et préserver les relations.", "Rouvrir la discussion si la participation améliorerait l'adhésion.", "Vous recentrer sur les résultats et les attentes.", "Tenir votre position et exiger l'engagement."] },
  21: { text: "Une décision complexe n'a pas de réponse évidente. Vous :", options: ["Choisissez la voie la plus alignée avec l'orientation future.", "Utilisez la décision pour développer le jugement de l'équipe.", "Réduisez l'anxiété et aidez les gens à rester connectés.", "Facilitez la contribution des bonnes personnes.", "Utilisez les données de performance et les meilleures pratiques.", "Prenez la décision et la communiquez clairement."] },
  22: { text: "Votre équipe manque de confiance. Vous :", options: ["Montrez une voie convaincante à suivre.", "Accompagnez les gens à travers des étapes de progrès atteignables.", "Vous concentrez sur l'encouragement et le soutien émotionnel.", "Demandez au groupe ce qui reconstruirait la confiance.", "Fixez un standard visible et démontrez la réussite.", "Créez une structure pour que chacun sache exactement quoi faire."] },
  23: { text: "Un processus est inefficace. Vous :", options: ["Reliez les améliorations à un état futur plus solide.", "Développez les personnes capables d'améliorer le processus.", "Veillez à ce que les changements ne nuisent pas à la confiance.", "Demandez aux utilisateurs du processus de le repenser.", "Remplacez les étapes faibles par un standard de haute performance.", "Imposez le nouveau processus."] },
  24: { text: "Lors des entretiens individuels, vous consacrez généralement le plus de temps à :", options: ["Le sens, la direction et les priorités.", "Les objectifs, le retour et le développement.", "Le bien-être, la confiance et les relations.", "Les idées, les préoccupations et les décisions partagées.", "Le résultat, les standards et le rythme.", "Les attentes, la responsabilisation et les blocages."] },
  25: { text: "Lorsqu'un coéquipier commet une erreur visible, vous :", options: ["Le reconnectez à ce à quoi ressemble la réussite.", "Accompagnez la leçon et le prochain comportement.", "Protégez sa dignité et réduisez la honte.", "Invitez l'équipe à améliorer le système.", "Attendez une correction rapide et un standard plus élevé.", "L'abordez directement et fixez des conséquences si nécessaire."] },
  26: { text: "Vous préférez que les équipes vous perçoivent comme :", options: ["Clair sur la direction et le sens.", "Investi dans leur développement.", "Bienveillant et centré sur les relations.", "Collaboratif et inclusif.", "Exigeant et tourné vers l'excellence.", "Décisif et directif."] },
  27: { text: "Lorsque les priorités entrent en concurrence, vous :", options: ["Choisissez en fonction de la vision à long terme.", "Considérez quel choix développe les compétences.", "Considérez l'impact sur la cohésion de l'équipe.", "Réunissez les parties prenantes pour peser les compromis.", "Choisissez la voie au résultat mesurable le plus élevé.", "Fixez la priorité et arrêtez le débat."] },
  28: { text: "Un membre de l'équipe est prêt pour une promotion. Vous :", options: ["Reliez la promotion aux besoins futurs de l'organisation.", "Le préparez par du coaching et des retours exigeants.", "Construisez un large soutien autour de sa transition.", "Recueillez l'avis des personnes qui travaillent avec lui.", "L'évaluez face à un niveau de performance très élevé.", "Clarifiez les attentes précises pour le niveau suivant."] },
  29: { text: "Votre façon habituelle de créer de la responsabilisation est de :", options: ["Aligner tout le monde sur une destination porteuse de sens.", "Aider les gens à s'approprier leurs objectifs de développement.", "Construire la confiance pour que les gens ne cachent pas les problèmes.", "Rendre les engagements visibles pour le groupe.", "Suivre étroitement la performance par rapport aux standards.", "Fixer des règles et des conséquences explicites."] },
  30: { text: "Lorsque vous menez un changement, vous êtes le plus à l'aise en :", options: ["Créant un récit convaincant sur la destination du changement.", "Aidant les gens à développer les compétences requises par le changement.", "Préservant le sentiment d'appartenance et la stabilité émotionnelle.", "Laissant les gens contribuer à façonner le changement.", "Avançant rapidement et démontrant ce à quoi ressemble l'excellence.", "Dirigeant le changement avec clarté et autorité."] },
};
