export const TRANSLATION_STATUS = "draft" as const;

export const MR_QUESTIONS_FR: Record<number, { text: string; options: [string, string, string, string] }> = {
  1:  { text: "L'engrenage A a 20 dents et s'engrène avec l'engrenage B qui a 60 dents. Si l'engrenage A tourne à 180 tr/min, à quelle vitesse tourne l'engrenage B ?", options: ["60 tr/min", "90 tr/min", "120 tr/min", "540 tr/min"] },
  2:  { text: "Un levier a son point d'appui à 1 m d'une charge de 300 N. Le bras de force mesure 3 m de long. Quel effort est nécessaire pour équilibrer le levier ?", options: ["50 N", "75 N", "100 N", "150 N"] },
  3:  { text: "Une poulie fixe est utilisée pour soulever une charge de 200 N. Quelle force doit être appliquée à la corde ?", options: ["100 N", "200 N", "400 N", "50 N"] },
  4:  { text: "Une poulie mobile est utilisée pour soulever une charge de 200 N. Quel effort est approximativement nécessaire ?", options: ["200 N", "100 N", "50 N", "400 N"] },
  5:  { text: "L'eau circule dans un tuyau de rayon 4 cm qui se rétrécit à un rayon de 2 cm. La vitesse dans la section large est de 1 m/s. Quelle est la vitesse dans la section étroite ?", options: ["2 m/s", "4 m/s", "8 m/s", "0.5 m/s"] },
  6:  { text: "Une poutre est soutenue à ses deux extrémités. Un poids de 600 N est suspendu en son centre. Quelle est la force de réaction à chaque appui ?", options: ["600 N", "300 N", "200 N", "150 N"] },
  7:  { text: "Vous doublez la pression sur un volume fixe de gaz à température constante. Le volume :", options: ["Double", "Reste identique", "Est divisé par deux", "Est multiplié par quatre"] },
  8:  { text: "L'engrenage A a 15 dents et s'engrène avec l'engrenage B qui a 45 dents. Si l'engrenage A tourne dans le sens horaire, l'engrenage B tourne :", options: ["Dans le sens horaire", "Dans le sens antihoraire", "Dans les deux sens indifféremment", "Il ne tourne pas"] },
  9:  { text: "Un bloc de 50 kg sur une surface sans frottement subit une force horizontale de 150 N. Quelle est son accélération ?", options: ["2 m/s²", "3 m/s²", "6 m/s²", "7 500 m/s²"] },
  10: { text: "Une rampe mesure 5 m de long et s'élève de 1 m. Quel effort est nécessaire pour faire glisser une charge de 200 N le long de la rampe (sans frottement) ?", options: ["20 N", "40 N", "100 N", "200 N"] },
  11: { text: "Un circuit électrique comporte une batterie de 12 V et une résistance de 4 Ω. Quel courant circule ?", options: ["48 A", "3 A", "0.33 A", "8 A"] },
  12: { text: "Deux résistances de 6 Ω chacune sont connectées en parallèle. Quelle est la résistance totale ?", options: ["12 Ω", "6 Ω", "3 Ω", "1 Ω"] },
  13: { text: "Un ressort est comprimé de 0.1 m par une force de 50 N. Quelle est la constante de raideur du ressort ?", options: ["5 N/m", "50 N/m", "500 N/m", "5 000 N/m"] },
  14: { text: "Quelle classe de levier a le point d'appui placé entre l'effort et la charge ?", options: ["Classe 1", "Classe 2", "Classe 3", "Classe 4"] },
  15: { text: "Une tige métallique de 2 m de long se dilate de 0.02 m sous l'effet de la chaleur. Quel est le pourcentage d'augmentation de la longueur ?", options: ["0.1%", "1%", "2%", "10%"] },
  16: { text: "Un système de poulies a un avantage mécanique de 4. Une charge de 400 N doit être soulevée. Quelle force doit être appliquée ?", options: ["400 N", "100 N", "200 N", "1 600 N"] },
  17: { text: "Quel matériau est le meilleur conducteur thermique ?", options: ["Bois", "Caoutchouc", "Plastique", "Cuivre"] },
  18: { text: "Une pression de 500 Pa s'exerce sur une surface de 2 m². Quelle est la force totale ?", options: ["250 N", "500 N", "1 000 N", "2 000 N"] },
  19: { text: "L'engrenage A (10 dents) entraîne l'engrenage B (30 dents), qui entraîne l'engrenage C (15 dents). L'engrenage A tourne à 90 tr/min. À quelle vitesse tourne l'engrenage C ?", options: ["30 tr/min", "60 tr/min", "90 tr/min", "180 tr/min"] },
  20: { text: "Dans un système hydraulique, un piston de surface 5 cm² est poussé avec une force de 100 N. Quelle force est produite par un piston de surface 50 cm² ?", options: ["10 N", "100 N", "1 000 N", "500 N"] },
  21: { text: "Un objet de 10 kg tombe d'une hauteur de 5 m. Quelle est sa vitesse juste avant l'impact ? (g = 10 m/s²)", options: ["5 m/s", "10 m/s", "50 m/s", "100 m/s"] },
  22: { text: "Un boulon nécessite un couple de 60 Nm. La clé mesure 0.3 m de long. Quelle force doit être appliquée ?", options: ["18 N", "180 N", "200 N", "20 N"] },
  23: { text: "Si la tension reste constante et que la résistance double, le courant va :", options: ["Doubler", "Rester identique", "Être divisé par deux", "Être multiplié par quatre"] },
  24: { text: "Une roue de rayon 0.5 m reçoit un couple de 30 Nm. Quelle force tangentielle produit ce couple ?", options: ["15 N", "30 N", "60 N", "90 N"] },
  25: { text: "Trois résistances de 2 Ω, 3 Ω et 5 Ω sont connectées en série. Quelle est la résistance totale ?", options: ["0.97 Ω", "10 Ω", "5 Ω", "3 Ω"] },
  26: { text: "Une boîte de 10 kg se déplace à 2 m/s sur un tapis roulant. Quelle est l'énergie cinétique de la boîte ?", options: ["10 J", "20 J", "40 J", "100 J"] },
  27: { text: "Un récipient scellé contient de l'air à 200 kPa et 300 K. La température monte à 600 K à volume constant. Quelle est la nouvelle pression ?", options: ["100 kPa", "200 kPa", "400 kPa", "800 kPa"] },
  28: { text: "Une vis a un pas de 2 mm. Combien de tours complets sont nécessaires pour l'enfoncer de 10 mm dans une surface ?", options: ["2", "5", "10", "20"] },
  29: { text: "Un objet flotte dans l'eau. Cela signifie que la densité moyenne de l'objet est :", options: ["Supérieure à celle de l'eau", "Égale à celle de l'eau", "Inférieure à celle de l'eau", "Sans rapport avec la flottaison"] },
  30: { text: "Un moteur électrique de 200 W fonctionne pendant 30 secondes. Quelle énergie consomme-t-il ?", options: ["200 J", "6 000 J", "666 J", "230 J"] },
};
