export const TRANSLATION_STATUS = "draft" as const;

export const PERSONALITY_QUESTIONS_FR: Record<number, { text: string }> = {
  1:  { text: "J'aime explorer de nouvelles idées, méthodes ou perspectives." },
  2:  { text: "Je suis curieux/curieuse de sujets en dehors de mon domaine de travail habituel." },
  3:  { text: "J'aime trouver des approches créatives à des problèmes familiers." },
  4:  { text: "Je préfère tellement les routines que j'évite d'essayer de nouvelles approches." },
  5:  { text: "Je remarque des schémas et des possibilités que d'autres peuvent négliger." },
  6:  { text: "J'aime apprendre de nouvelles compétences même quand elles ne sont pas immédiatement nécessaires." },
  7:  { text: "Je suis à l'aise avec l'ambiguïté pendant qu'une idée est encore en train de se former." },
  8:  { text: "J'apprécie rarement les discussions abstraites ou imaginatives." },
  9:  { text: "Je planifie mon travail soigneusement avant de passer à l'exécution." },
  10: { text: "Je tiens mes engagements même quand les tâches deviennent fastidieuses." },
  11: { text: "Je garde les détails importants organisés et faciles à retrouver." },
  12: { text: "Je laisse souvent des choses inachevées quand une tâche perd de son élan." },
  13: { text: "Je vérifie mon travail par souci d'exactitude avant de le considérer terminé." },
  14: { text: "Je gère les délais en commençant assez tôt pour pouvoir ajuster si nécessaire." },
  15: { text: "Je préfère des priorités claires et une exécution structurée." },
  16: { text: "Je sous-estime fréquemment le temps que prendra un travail." },
  17: { text: "J'obtiens de l'énergie en interagissant avec des gens au cours de la journée." },
  18: { text: "Je suis à l'aise pour prendre la parole lors de discussions de groupe." },
  19: { text: "J'ai tendance à engager la conversation avec de nouvelles personnes." },
  20: { text: "Je préfère rester silencieux/silencieuse même quand j'ai quelque chose d'utile à ajouter." },
  21: { text: "J'apporte un enthousiasme visible au travail collaboratif." },
  22: { text: "Il m'est naturel de construire des relations entre équipes." },
  23: { text: "Je suis à l'aise pour prendre les devants dans des situations sociales ou de groupe." },
  24: { text: "Les interactions fréquentes m'épuisent au point que je les évite autant que possible." },
  25: { text: "J'essaie de comprendre les besoins des autres avant de porter des jugements." },
  26: { text: "Je recherche des solutions coopératives en cas de désaccord." },
  27: { text: "Je fais attention à l'impact de mes actions sur les autres." },
  28: { text: "Je peux être direct(e) d'une manière qui nuit à la confiance." },
  29: { text: "J'accorde le bénéfice du doute aux gens lorsque c'est possible." },
  30: { text: "Je suis disposé(e) à aider mes collègues même quand ce n'est pas directement ma responsabilité." },
  31: { text: "Je gère les conflits dans le respect de la dignité de l'autre personne." },
  32: { text: "Je suis souvent en compétition avec les autres alors que la collaboration fonctionnerait mieux." },
  33: { text: "Je reste posé(e) quand le travail devient incertain ou stressant." },
  34: { text: "Je me remets rapidement après avoir reçu un retour difficile." },
  35: { text: "Je peux garder du recul quand plusieurs choses tournent mal en même temps." },
  36: { text: "Je me sens souvent dépassé(e) par la pression normale du travail." },
  37: { text: "Je reste stable quand les priorités changent de façon inattendue." },
  38: { text: "Je peux gérer la frustration sans la laisser dicter mon comportement." },
  39: { text: "Je préfère généralement laisser reposer les problèmes plutôt que de les ressasser constamment." },
  40: { text: "De petits revers peuvent me rendre anxieux/anxieuse pendant longtemps." },
};
