export const TRANSLATION_STATUS = "draft" as const;

export const SA_QUESTIONS_FR: Record<number, { text: string; options: [string, string, string, string] }> = {
  // Prospecting (9)
  1:  { text: "En entrant sur un nouveau territoire commercial, quelle doit être votre première étape ?", options: ["Envoyer immédiatement des e-mails de prospection en masse à autant d'entreprises que possible", "Étudier le marché, définir votre profil de client idéal et constituer une liste de prospects ciblée", "Appeler toutes les entreprises de la zone par ordre alphabétique", "Attendre les leads entrants du marketing"] },
  2:  { text: "Quel facteur est LE PLUS important pour qualifier un nouveau prospect ?", options: ["La taille apparente de l'entreprise sur LinkedIn", "La rapidité avec laquelle il répond à votre première prise de contact", "S'il correspond à votre profil de client idéal et dispose du budget et de l'autorité nécessaires pour décider d'un achat", "S'il a déjà entendu parler de votre entreprise"] },
  3:  { text: "Quelle approche améliore le plus fiablement les taux d'ouverture des e-mails de prospection ?", options: ["Personnaliser l'objet en mentionnant spécifiquement l'entreprise ou le poste du prospect", "Utiliser les récompenses et distinctions de votre entreprise dans l'objet", "Écrire « Opportunité de partenariat » dans l'objet", "Relancer quotidiennement jusqu'à ce qu'il l'ouvre"] },
  4:  { text: "Vous avez identifié une entreprise cible mais ne trouvez pas les coordonnées du bon décideur. Quelle est la meilleure approche ?", options: ["Envoyer un e-mail à l'adresse générique de l'entreprise en espérant qu'il atteigne la bonne personne", "Utiliser LinkedIn pour identifier le bon contact, étudier son rôle et envoyer un message personnalisé", "Appeler l'accueil et demander « la personne responsable de l'achat de logiciels »", "Passer au prospect suivant — c'est trop difficile"] },
  5:  { text: "Combien de points de contact devriez-vous typiquement effectuer avant de disqualifier un prospect froid qui n'a pas répondu ?", options: ["1 à 2 tentatives sur un seul canal", "3 à 4 tentatives sur un seul canal", "5 à 8 tentatives réparties sur plusieurs canaux durant plusieurs semaines", "10 ou plus — ne jamais abandonner un prospect"] },
  6:  { text: "Avant un premier appel à froid, quelle information est la plus essentielle à préparer ?", options: ["L'historique de carrière complet du prospect sur LinkedIn", "Les principaux défis de l'entreprise, les priorités probables de votre interlocuteur, et comment votre solution pourrait spécifiquement l'aider", "Le cours actuel de l'action de l'entreprise et ses performances financières", "Le nombre d'employés et les emplacements des bureaux"] },
  7:  { text: "Quelle approche de message LinkedIn est la plus efficace pour obtenir une réponse ?", options: ["« J'aimerais vous ajouter à mon réseau professionnel. »", "« Bonjour [Nom], j'aide [son poste] dans des entreprises comme la vôtre à atteindre [résultat spécifique]. Cela vaut-il un appel de 15 minutes pour voir si c'est pertinent pour vous ? »", "Un long message listant toute la gamme de produits et les tarifs de votre entreprise", "« Puis-je avoir 5 minutes de votre temps cette semaine ? »"] },
  8:  { text: "Votre pipeline est très faible. Quelle est l'action immédiate la plus efficace ?", options: ["Réduire vos prix pour accélérer les affaires existantes", "Se concentrer uniquement sur les clients existants pour des opportunités de montée en gamme", "Recontacter systématiquement les prospects inactifs, les sources de recommandation et les nouvelles cibles de votre profil idéal sur plusieurs canaux", "Attendre que l'équipe marketing génère de nouveaux leads entrants"] },
  9:  { text: "Vous disposez de deux heures pour prospecter. Comment devriez-vous prioriser ?", options: ["Consacrer les deux heures entières uniquement aux appels à froid", "Répartir votre temps entre une prise de contact personnalisée avec des leads chauds et une recherche ciblée sur de nouveaux prospects prioritaires", "Rédiger un e-mail très détaillé pour un seul prospect", "Publier du contenu sur LinkedIn et surveiller l'engagement"] },
  // Persuasion (9)
  10: { text: "Un prospect dit : « Parlez-moi de votre produit. » Quelle est la meilleure réponse ?", options: ["Dérouler immédiatement votre démonstration complète du produit du début à la fin", "Poser d'abord deux ou trois questions de découverte sur sa situation actuelle, puis adapter votre explication à ses besoins spécifiques", "Lui envoyer une brochure produit et relancer dans une semaine", "Lister toutes les fonctionnalités du produit, de la plus chère à la moins chère"] },
  11: { text: "Quelle approche commerciale est la plus efficace dans un contexte B2B ?", options: ["Commencer par les spécifications techniques et la liste de fonctionnalités du produit", "Se différencier principalement par le prix", "Comprendre les points de douleur du prospect et montrer précisément comment votre solution y répond", "Créer une rareté et une urgence artificielles pour accélérer la décision"] },
  12: { text: "Pendant une démonstration, un acheteur mentionne un concurrent connu par son nom. Quelle est la meilleure réponse ?", options: ["Lister immédiatement tout ce qui ne va pas avec le produit du concurrent", "Reconnaître le concurrent et rebondir sur ce qui rend votre solution particulièrement meilleure pour la situation spécifique de cet acheteur", "Ignorer la mention et poursuivre votre présentation", "Dire à l'acheteur que votre entreprise est leader du marché sans apporter de preuve spécifique"] },
  13: { text: "Après un appel de découverte, par quoi votre proposition doit-elle commencer ?", options: ["L'histoire, les valeurs et les distinctions sectorielles de votre entreprise", "Une répartition complète de tous les niveaux de tarification disponibles", "Un résumé concis des objectifs et défis exprimés par le prospect, suivi de la façon dont votre solution répond à chacun", "Des spécifications techniques détaillées du produit"] },
  14: { text: "Quelle approche crée le mieux une urgence authentique sans exercer de pression contraire à l'éthique ?", options: ["« Ce prix n'est valable qu'aujourd'hui — mon responsable le retirera demain. »", "« Nos disponibilités sont limitées — vous devez décider maintenant. »", "« D'après vos objectifs, démarrer ce trimestre vous permettrait de voir des résultats avant [échéance commerciale précise mentionnée par le prospect]. »", "« L'un de vos concurrents est déjà en discussion finale avec nous. »"] },
  15: { text: "Un prospect est intéressé mais pas encore convaincu. Quelle est la meilleure prochaine étape ?", options: ["Insister fortement pour une conclusion immédiate — l'hésitation signifie qu'il a besoin de plus de pression", "Proposer de le mettre en relation avec un client de référence dans un rôle ou secteur similaire, et planifier un appel de suivi pour répondre aux questions restantes", "Réduire le prix pour lever le frein financier", "Lui laisser de l'espace et attendre qu'il revienne vers vous"] },
  16: { text: "Quelle est la manière la plus efficace d'utiliser des études de cas clients dans un processus de vente ?", options: ["Joindre un PDF d'étude de cas générique à chaque e-mail de prospection", "Sélectionner une étude de cas d'une entreprise proche du profil du prospect et mettre en avant des résultats spécifiques et mesurables pertinents pour ses objectifs", "Ne partager des études de cas que lorsque le prospect en fait explicitement la demande", "Toujours citer votre client le plus prestigieux, indépendamment de la pertinence du secteur ou de la taille"] },
  17: { text: "Vous présentez à un groupe d'acheteurs de cinq personnes ayant des rôles et priorités différents. Quelle est la meilleure approche ?", options: ["Dérouler votre présentation standard et laisser les questions pour la fin", "Commencer en demandant à chaque partie prenante à quoi ressemblerait un résultat réussi pour elle, puis aborder chaque point de vue durant la présentation", "Concentrer toute votre attention sur la personne la plus haut placée et lui adresser tous vos propos", "Ne présenter que la spécification technique — toutes les parties prenantes s'intéressent finalement aux détails"] },
  18: { text: "Un prospect demande : « Pourquoi devrions-nous vous choisir plutôt que vos concurrents ? » Quelle structure de réponse est la meilleure ?", options: ["Lister immédiatement tout ce qui manque à vos concurrents", "Reconnaître le paysage concurrentiel, puis se concentrer sur les résultats précis que votre solution apporte à des entreprises comme la leur, preuves concrètes à l'appui", "Leur dire que vous êtes leader du marché et s'en tenir là", "Demander quel concurrent précis ils envisagent avant de dire quoi que ce soit sur votre propre solution"] },
  // Objection Handling (9)
  19: { text: "Un prospect dit : « Votre prix est trop élevé. » Quelle est la meilleure réponse initiale ?", options: ["Proposer immédiatement une remise pour faire avancer la conversation", "S'excuser et expliquer en détail pourquoi vos coûts sont ce qu'ils sont", "Demander « Comparé à quoi ? » et explorer la valeur que l'investissement générerait pour lui par rapport au coût", "Lui dire que le prix n'est pas négociable et demander s'il souhaite continuer"] },
  20: { text: "Un prospect dit : « Nous sommes satisfaits de notre fournisseur actuel. » Quelle est la meilleure réponse ?", options: ["Lui dire que son fournisseur actuel commet des erreurs dont il n'a peut-être pas conscience", "Accepter poliment l'objection et clore l'appel", "« C'est une excellente nouvelle. La plupart des clients avec qui nous travaillons disaient la même chose avant notre premier échange. Qu'est-ce qui devrait changer pour que vous envisagiez une alternative ? »", "Proposer immédiatement un prix inférieur à celui de son fournisseur actuel"] },
  21: { text: "Un prospect dit : « Je dois y réfléchir. » Quelle est la meilleure réponse ?", options: ["Dire « Pas de problème » et relancer dans deux semaines avec le même argumentaire", "« Bien sûr — de quoi auriez-vous précisément besoin pour avancer en toute confiance ? »", "Lui envoyer une liste complète des fonctionnalités à examiner à son rythme", "Lui dire que vous avez besoin d'une décision avant la fin de la semaine"] },
  22: { text: "Un prospect dit : « Ce n'est pas une priorité en ce moment. » Quelle est la meilleure réponse ?", options: ["Accepter l'objection et le placer dans une séquence de nurturing à long terme sans autre échange", "Demander quelles sont ses priorités actuelles et explorer si votre solution pourrait l'aider à en atteindre certaines plus rapidement", "Proposer une remise pour que cela paraisse une décision moins risquée", "Recontacter la même personne la semaine suivante avec le même argumentaire"] },
  23: { text: "Un prospect dit : « Je dois en discuter avec mon équipe avant de décider. » Quelle est la meilleure réponse ?", options: ["Proposer de participer à une réunion d'équipe ou de fournir des supports adaptés aux préoccupations spécifiques de chaque partie prenante", "Lui dire que la décision doit finalement lui revenir", "Réduire le périmètre de votre proposition pour que l'équipe ait moins à examiner", "Lui donner un ultimatum — signer avant la prochaine réunion d'équipe ou l'offre expire"] },
  24: { text: "Un prospect dit : « Nous avons déjà essayé quelque chose de similaire et cela n'a pas fonctionné. » Quelle est la meilleure réponse ?", options: ["Écarter son expérience passée comme non pertinente pour votre solution", "« Je comprends — dites-m'en plus sur ce qui s'est passé. Je veux m'assurer que nous ne vous exposons pas au même résultat. »", "Passer outre la remarque et revenir aux fonctionnalités de votre produit", "Lui dire que votre produit est complètement différent sans chercher à comprendre ce qui s'est passé"] },
  25: { text: "Un prospect demande : « Pouvez-vous vous aligner sur le prix du Concurrent X ? » Quelle est la meilleure réponse ?", options: ["Accepter immédiatement de s'aligner pour ne pas perdre l'affaire", "Refuser fermement et expliquer que vos tarifs sont fixes", "Explorer la valeur spécifique qu'il voit dans l'offre du concurrent et clarifier comment votre retour sur investissement total se compare avant de discuter d'un ajustement de prix", "Lui dire que le produit du concurrent est inférieur sans preuve"] },
  26: { text: "Un prospect qui semblait engagé est devenu complètement silencieux après deux relances. Quelle est la meilleure approche ?", options: ["Envoyer un e-mail de relance chaque jour jusqu'à ce qu'il réponde", "Envoyer un court e-mail de « rupture » axé sur la valeur, reconnaissant qu'il est peut-être passé à autre chose, en laissant la porte ouverte avec respect", "Escalader en contactant son responsable ou un autre contact senior", "Considérer l'affaire comme perdue et le retirer immédiatement de votre pipeline"] },
  27: { text: "La même objection revient dans plusieurs affaires de votre pipeline. Quelle est la réponse la plus productive ?", options: ["Essayer de la contourner différemment dans chaque affaire individuelle", "Baisser vos prix de façon généralisée pour anticiper l'objection", "Documenter l'objection, développer une réponse solide fondée sur des preuves, et revoir votre marché cible pour vous assurer de l'adéquation produit-marché", "Retirer de votre argumentaire la fonctionnalité ou l'élément à l'origine de l'objection"] },
  // Closing (8)
  28: { text: "Une affaire est bloquée sans avancée depuis deux semaines. Quelle est l'approche la plus efficace ?", options: ["Appeler tous les jours jusqu'à ce que quelqu'un de l'entreprise réponde", "Envoyer un message de relance qui exprime le coût de l'inaction en fonction de leurs objectifs et propose une prochaine étape claire et simple", "Baisser le prix de 20 % pour relancer le mouvement", "Considérer l'affaire comme perdue et concentrer votre attention sur de nouveaux prospects"] },
  29: { text: "Le prospect a donné son accord de principe mais ne signe pas le contrat. Quelle est l'approche la plus efficace ?", options: ["Renvoyer le contrat et attendre qu'il agisse", "Demander directement : « Qu'est-ce qui vous empêche précisément de signer maintenant ? » et traiter ces préoccupations", "Ajouter des incitations ou des conditions supplémentaires au contrat sans en discuter au préalable", "Escalader directement auprès du responsable du prospect"] },
  30: { text: "Vous avez envoyé une proposition il y a une semaine et n'avez reçu aucune réponse. Quelle est la meilleure prochaine étape ?", options: ["Supposer qu'il n'est pas intéressé et clore l'opportunité", "Appeler pour demander s'il a pu la consulter, en proposant de passer en revue les questions ensemble lors d'un court appel", "Envoyer une version moins chère de la proposition sans explication", "Renvoyer la même proposition avec « Relance » dans l'objet"] },
  31: { text: "Un prospect demande plus de temps avant de s'engager. Quelle est la meilleure réponse ?", options: ["Lui dire que l'offre expire à la fin du mois pour créer de l'urgence", "« Bien sûr — de quoi auriez-vous besoin de voir ou de résoudre pendant ce temps pour avancer en toute confiance ? »", "Lui dire que vous relancerez dans un mois et en rester là", "Proposer un contrat initial plus petit pour réduire l'engagement requis"] },
  32: { text: "Quelle technique de clôture est la plus adaptée à une affaire B2B complexe ?", options: ["La clôture « à prendre ou à laisser » — faire une offre finale et se retirer en cas d'hésitation", "La clôture présomptive — agir comme si la décision était déjà prise et commencer à discuter de la mise en œuvre", "La clôture récapitulative — résumer la valeur convenue, confirmer la volonté d'avancer et proposer des prochaines étapes claires", "Créer une fausse rareté pour forcer une décision cette semaine"] },
  33: { text: "Le décideur est convaincu, mais l'équipe finance a soulevé des préoccupations budgétaires. Quelle est la meilleure prochaine étape ?", options: ["Réduire immédiatement votre prix pour satisfaire la finance", "Proposer de présenter directement le dossier économique à l'équipe finance, en mettant l'accent sur le retour sur investissement et le coût total de possession", "Demander au décideur de passer outre les préoccupations de la finance", "Abandonner — si la finance n'est pas alignée, l'affaire ne se conclura pas"] },
  34: { text: "Une affaire approche de sa conclusion en fin de trimestre. Comment créer une urgence authentique et éthique ?", options: ["Le prévenir que le prix augmentera le mois prochain même si ce n'est pas vrai", "Lui dire qu'un autre prospect envisage la même offre", "Lier la date de démarrage à un résultat commercial précis qui compte pour le prospect — comme un lancement avant un événement clé ou une période de pointe qu'il a mentionnée", "Proposer un module gratuit qui expire artificiellement en fin de mois"] },
  35: { text: "Immédiatement après la signature d'un prospect et la conclusion de l'affaire, quelle est la prochaine étape la plus importante ?", options: ["Demander des recommandations tout de suite pendant que la relation est chaleureuse", "Confirmer clairement les prochaines étapes — calendrier de mise en œuvre, contacts clés, et ce que le client doit s'attendre à voir se passer et quand", "Célébrer en interne et concentrer votre attention sur le prochain prospect", "Envoyer un e-mail de bienvenue générique et transmettre au service client sans le briefer"] },
};
