export const TRANSLATION_STATUS = "draft" as const;

export const SJT_QUESTIONS_FR: Record<number, {
  text: string;
  options: [string, string, string, string];
}> = {
  1:  { text: "Vous découvrez deux solutions raisonnables à un problème urgent, mais aucune n'est parfaite. Que faites-vous ?", options: ["Choisir l'option avec les preuves les plus claires et expliquer les compromis.", "Retarder la décision jusqu'à ce qu'une option parfaite apparaisse.", "Demander à la personne la plus haut placée de décider sans partager votre analyse.", "Choisir l'option qui semble la plus rapide et continuer."] },
  2:  { text: "Un coéquipier bloque l'avancement car il n'est pas d'accord avec la direction prise. Quelle est votre meilleure première action ?", options: ["Écouter sa préoccupation, clarifier l'objectif commun et chercher une voie viable.", "Contourner la personne pour que le projet puisse continuer.", "Lui dire que la décision est déjà prise et qu'il doit s'y conformer.", "Demander à tout le groupe de faire une pause et de revoir chaque décision antérieure."] },
  3:  { text: "Vous réalisez que votre erreur a causé une erreur de reporting sur laquelle d'autres pourraient s'appuyer. Que faites-vous ?", options: ["La corriger discrètement en espérant que personne ne l'ait remarquée.", "Informer les personnes concernées, corriger les données et expliquer les mesures de prévention.", "Attendre de voir si l'erreur crée un problème visible.", "En informer uniquement votre responsable, sans contacter les utilisateurs du rapport."] },
  4:  { text: "Les priorités changent à mi-parcours d'un projet. Quelle réponse démontre le meilleur jugement ?", options: ["Continuer sur le plan initial car changer maintenant gaspillerait des efforts.", "Clarifier le nouvel objectif, évaluer l'impact et ajuster le plan avec l'équipe.", "Tout recommencer immédiatement avant de comprendre la nouvelle priorité.", "Demander une confirmation écrite avant de faire tout travail supplémentaire."] },
  5:  { text: "Une partie prenante comprend mal votre mise à jour et devient frustrée. Que faites-vous ?", options: ["Répéter votre message plus fermement pour qu'elle comprenne.", "Reconnaître la confusion, clarifier le point clé et confirmer les prochaines étapes.", "Éviter toute discussion supplémentaire jusqu'à ce qu'elle se calme.", "Envoyer une explication plus longue avec tous les détails inclus."] },
  6:  { text: "Il vous manque une donnée avant une échéance. Que devez-vous faire ?", options: ["Faire une hypothèse et la présenter comme un fait.", "Énoncer clairement l'hypothèse, utiliser les preuves disponibles et signaler le risque.", "Refuser de soumettre quoi que ce soit tant que les données ne sont pas complètes.", "Demander à quelqu'un d'autre de prendre la décision."] },
  7:  { text: "Un collègue plus discret a de l'expertise mais se fait interrompre en réunion. Que faites-vous ?", options: ["Laisser la réunion se poursuivre car les interruptions sont normales.", "Lui demander en privé plus tard ce qu'il aurait dit.", "Créer un espace dans la réunion pour qu'il termine son propos.", "Interrompre agressivement celui qui interrompt."] },
  8:  { text: "Un projet prend du retard parce que votre estimation était trop optimiste. Que faites-vous ?", options: ["Partager l'estimation actualisée, assumer l'erreur et proposer des options de rattrapage.", "Réduire la qualité pour respecter la date initiale sans le dire à personne.", "Rejeter d'abord la faute sur des dépendances externes.", "Demander plus de temps sans expliquer pourquoi."] },
  9:  { text: "Un outil dont vous dépendez cesse de fonctionner avant l'échéance d'un livrable. Quelle est la réponse la plus solide ?", options: ["Attendre que l'outil soit réparé.", "Trouver une alternative viable, communiquer l'impact et continuer.", "Changer d'outil définitivement sans vérifier les conséquences.", "Dire au demandeur que l'échéance est impossible à tenir."] },
  10: { text: "Vous devez refuser une demande irréaliste. Que dites-vous ?", options: ["Cela ne peut pas être fait.", "Oui, puis espérer en privé que le périmètre change.", "Voici ce qui est possible d'ici là, et voici les compromis pour le reste.", "Leur demander d'envoyer la demande à votre responsable."] },
  11: { text: "Deux indicateurs racontent des histoires différentes sur la performance. Que faites-vous ?", options: ["Utiliser l'indicateur qui soutient votre conclusion préférée.", "Étudier pourquoi ils diffèrent et expliquer les limites de chacun.", "Ignorer les deux indicateurs et vous fier à l'expérience.", "Les moyenner sans vérifier si cela a du sens."] },
  12: { text: "Une autre équipe demande de l'aide alors que votre propre charge de travail est déjà lourde. Quelle est la meilleure réponse ?", options: ["Ignorer la demande jusqu'à ce que votre propre travail soit terminé.", "Dire oui immédiatement même si cela met en péril vos engagements.", "Clarifier l'urgence, négocier la capacité et aligner les priorités de façon transparente.", "Transmettre la demande à quelqu'un d'autre sans contexte."] },
  13: { text: "Vous recevez un retour critique qui vous semble injuste. Que devez-vous faire en premier ?", options: ["Défendre immédiatement votre intention.", "Poser des questions de clarification et chercher la partie utile du retour.", "L'écarter car la personne n'a pas tout le contexte.", "Tout accepter sans discussion."] },
  14: { text: "Une nouvelle exigence entre en conflit avec un travail déjà réalisé. Que faites-vous ?", options: ["Évaluer ce qui peut être réutilisé, ce qui doit changer, et l'impact sur le périmètre.", "Rejeter l'exigence parce qu'elle arrive tard.", "Commencer à modifier le travail immédiatement sans confirmer la priorité.", "Demander une réunion mais suspendre tout le travail lié jusqu'à celle-ci."] },
  15: { text: "Un message que vous avez envoyé pourrait être perçu comme dur. Quelle est la meilleure prochaine étape ?", options: ["Supposer que les gens comprendront votre intention.", "Supprimer le message si possible.", "Faire un suivi avec un ton plus clair, du contexte et l'action suivante prévue.", "Envoyer de longues excuses avant même de savoir si cela a posé problème."] },
  16: { text: "Une personne senior recommande une approche que vous jugez risquée. Que faites-vous ?", options: ["Rester silencieux car elle est plus haut placée.", "Soulever le risque avec respect, preuves et alternatives à l'appui.", "Rejeter l'approche devant tout le monde.", "Suivre l'approche mais documenter que ce n'était pas votre idée."] },
  17: { text: "Une décision d'équipe est prise, mais ce n'était pas votre option préférée. Que faites-vous ?", options: ["Soutenir la décision et aider à la faire réussir.", "Continuer à défendre votre option dans des conversations informelles.", "Ne faire que votre part assignée sans aider les autres.", "Demander à la revoir à chaque réunion de suivi."] },
  18: { text: "Vous remarquez un problème récurrent dans votre domaine. Quelle est la meilleure action ?", options: ["Corriger chaque cas au fur et à mesure.", "L'escalader sans proposer de solution.", "Analyser le schéma et proposer une amélioration préventive.", "L'accepter comme faisant partie du fonctionnement normal."] },
  19: { text: "On vous confie un travail dans un domaine que vous ne connaissez pas. Que faites-vous ?", options: ["Attendre des instructions détaillées avant de commencer.", "Identifier ce que vous devez apprendre, poser des questions ciblées et démarrer avec un petit plan.", "Faire semblant d'en savoir assez pour ne pas paraître mal préparé.", "Demander que le travail soit réattribué."] },
  20: { text: "Votre mise à jour contient une mauvaise nouvelle. Quelle est la meilleure structure ?", options: ["Commencer par le problème, expliquer l'impact et donner les prochaines étapes.", "Cacher la mauvaise nouvelle à la fin.", "La partager uniquement à l'oral pour qu'il n'y ait pas de trace écrite.", "Envoyer un bref message disant qu'il y a un problème."] },
  21: { text: "Un client demande quelque chose en dehors de la politique établie. Que faites-vous ?", options: ["Appliquer la politique sans explication.", "Enfreindre la politique pour satisfaire le client.", "Comprendre le besoin, expliquer les limites et proposer des alternatives conformes.", "Le rediriger vers un autre service."] },
  22: { text: "Un coéquipier s'attribue le mérite d'un travail auquel vous avez contribué. Quelle est votre meilleure première réponse ?", options: ["Le corriger publiquement d'une manière qui l'embarrasse.", "Laisser le ressentiment s'accumuler et cesser de l'aider.", "En discuter en privé et clarifier le partage du mérite à l'avenir.", "En parler immédiatement à votre responsable sans lui en parler d'abord."] },
  23: { text: "Vous vous étiez engagé sur une tâche, mais un blocage survient. Que faites-vous ?", options: ["Attendre l'échéance pour expliquer le blocage.", "Communiquer tôt, partager ce que vous avez essayé et demander l'aide précise nécessaire.", "Supposer que quelqu'un d'autre le remarquera.", "Abandonner d'autres engagements sans le dire à personne."] },
  24: { text: "Un processus familier est remplacé par un nouveau. Quelle est votre réponse la plus solide ?", options: ["Comparer l'ancien et le nouveau processus, apprendre les changements et suggérer des améliorations après usage.", "Continuer à utiliser l'ancien processus jusqu'à ce qu'on vous arrête.", "Se plaindre que le changement était inutile.", "Utiliser le nouveau processus mais éviter de donner un retour."] },
  25: { text: "Vous avez besoin d'informations de la part de quelqu'un qui n'a pas répondu. Que faites-vous ?", options: ["Envoyer une relance claire avec contexte, échéance et enjeu.", "Continuer à envoyer le même message de façon répétée.", "Supposer qu'on vous ignore et escalader immédiatement.", "Attendre en espérant une réponse."] },
  26: { text: "Votre équipe est enthousiaste à propos d'une idée, mais vous voyez un risque majeur de mise en œuvre. Que faites-vous ?", options: ["Laisser l'enthousiasme continuer car le moral compte avant tout.", "Nommer le risque, le quantifier si possible, et suggérer un test ou une atténuation.", "Rejeter immédiatement l'idée.", "Attendre que le risque devienne évident."] },
  27: { text: "Un projet a trop de responsables et les décisions sont lentes. Quelle est la meilleure solution ?", options: ["Clarifier les droits de décision, les rôles et le chemin pour les questions non résolues.", "Prendre les décisions vous-même pour gagner du temps.", "Demander à tout le monde d'être plus collaboratif.", "Prendre du recul jusqu'à ce que la responsabilité soit clarifiée."] },
  28: { text: "Vous trouvez un raccourci qui ferait gagner du temps mais créerait un risque de maintenance plus tard. Que faites-vous ?", options: ["Utiliser le raccourci et ne le documenter que si on vous le demande.", "Présenter le raccourci, le risque et des alternatives plus sûres avant de décider.", "L'utiliser car la rapidité est la seule priorité.", "Éviter le raccourci sans expliquer le compromis."] },
  29: { text: "Un collègue propose une meilleure façon de faire quelque chose que vous avez construit. Quelle est votre réponse ?", options: ["Défendre votre approche initiale.", "Évaluer l'idée objectivement et l'adopter si elle améliore le résultat.", "Être d'accord publiquement mais garder votre approche inchangée.", "Lui demander de prouver que cela fonctionne avant de vous impliquer."] },
  30: { text: "Une passation transverse a échoué car les attentes n'étaient pas claires. Que doit-il se passer ensuite ?", options: ["Créer des critères d'acceptation plus clairs et confirmer la responsabilité avant la prochaine passation.", "Demander à l'équipe réceptrice d'être plus attentive la prochaine fois.", "Ajouter plus de personnes aux futures réunions de passation.", "Rédiger un résumé plus long après chaque passation."] },
};
