export const TRANSLATION_STATUS = "draft" as const;

export const ST_QUESTIONS_FR: Record<number, { text: string }> = {
  1:  { text: "Je reste calme et posé(e) face à des situations très stressantes au travail." },
  2:  { text: "Je peux gérer mes réactions émotionnelles même lorsque je me sens réellement frustré(e) ou sous forte pression." },
  3:  { text: "Je remarque quand le stress commence à affecter mon humeur et j'agis pour le gérer avant qu'il ne s'aggrave." },
  4:  { text: "J'ai tendance à devenir sec/sèche ou irritable avec mes collègues lorsque je suis sous forte pression." },
  5:  { text: "Je suis capable d'éviter que le stress personnel ne déborde sur mes interactions professionnelles." },
  6:  { text: "Quand je suis stressé(e), je prends souvent des décisions hâtives que je regrette ensuite." },
  7:  { text: "Je peux rester concentré(e) sur les faits et les solutions pratiques même lorsqu'une situation est chargée émotionnellement." },
  8:  { text: "C'est évident pour mes collègues quand je suis stressé(e), même quand j'essaie de ne pas le montrer." },
  9:  { text: "Quand les choses tournent mal, je me remets rapidement et me reconcentre sur ce qui peut être fait ensuite." },
  10: { text: "Je considère les revers professionnels comme des occasions d'apprentissage plutôt que comme des échecs." },
  11: { text: "Je conserve ma confiance et mon estime de moi-même même après avoir commis une erreur importante au travail." },
  12: { text: "J'ai tendance à ressasser les résultats négatifs plus longtemps que ce qui est utile ou productif." },
  13: { text: "Je suis capable de garder du recul pendant les périodes difficiles ou exigeantes au travail." },
  14: { text: "Après une période stressante, je retrouve mon niveau de performance normal relativement rapidement." },
  15: { text: "Face à un obstacle important, j'ai du mal à rester motivé(e) et à continuer d'avancer." },
  16: { text: "Je considère les défis comme une partie normale de la vie professionnelle plutôt que comme une menace personnelle." },
  17: { text: "J'ai des stratégies efficaces et saines que j'utilise pour gérer le stress lorsqu'il devient intense." },
  18: { text: "J'agis de manière proactive pour traiter le stress avant qu'il ne devienne un problème plus important." },
  19: { text: "J'utilise l'activité physique, des pauses ou d'autres exutoires sains pour décompresser de la pression liée au travail." },
  20: { text: "Quand je me sens dépassé(e), j'ai tendance à éviter la source du stress plutôt que de l'affronter directement." },
  21: { text: "Je suis à l'aise pour demander du soutien ou parler à quelqu'un lorsque je suis en difficulté face au stress." },
  22: { text: "Je suis capable de séparer le stress professionnel de ma vie personnelle et de vraiment déconnecter en dehors des heures de travail." },
  23: { text: "J'ai tendance à garder le stress pour moi plutôt que de l'aborder de façon constructive." },
  24: { text: "Je donne le meilleur de moi-même, ou presque, quand les enjeux sont élevés et le délai serré." },
  25: { text: "Je suis capable de maintenir mon attention aux détails même en travaillant sous une pression de temps importante." },
  26: { text: "Face à une tâche difficile ou à fort enjeu, je me sens motivé(e) par le défi plutôt que dépassé(e) par celui-ci." },
  27: { text: "Je commets nettement plus d'erreurs que d'habitude lorsque je travaille sous une intense pression de temps." },
  28: { text: "Je peux prioriser efficacement même en gérant simultanément plusieurs dossiers urgents." },
  29: { text: "Les situations de forte pression font systématiquement se détériorer nettement ma performance." },
  30: { text: "Je suis capable de livrer un travail de qualité même pendant des périodes particulièrement exigeantes ou stressantes." },
};
