export const TRANSLATION_STATUS = "draft" as const;

export const TW_QUESTIONS_FR: Record<number, { text: string }> = {
  1:  { text: "Je soutiens activement mes collègues pour les aider à réussir, pas seulement moi-même." },
  2:  { text: "Je suis prêt(e) à faire passer les objectifs de l'équipe avant mes préférences personnelles quand c'est important." },
  3:  { text: "Je partage informations et ressources avec mon équipe sans qu'on ait besoin de me le demander." },
  4:  { text: "Je contribue équitablement aux tâches communes plutôt que de laisser d'autres porter une charge disproportionnée." },
  5:  { text: "Je reconnais et apprécie ouvertement les contributions de mes coéquipiers." },
  6:  { text: "Je préfère garder mon travail séparé et indépendant plutôt que de l'intégrer à celui de l'équipe." },
  7:  { text: "Je suis prêt(e) à ajuster mon approche lorsque cela aide l'équipe à fonctionner plus efficacement." },
  8:  { text: "J'interviens pour aider un collègue en difficulté, même quand ce n'est pas formellement ma responsabilité." },
  9:  { text: "Je réfléchis à la façon dont mes décisions et actions affectent les autres membres de l'équipe avant d'agir." },
  10: { text: "Je tiens mes coéquipiers informés de mon avancement sans attendre qu'on me le demande." },
  11: { text: "Je communique clairement ce dont j'ai besoin des autres pour accomplir efficacement mon travail." },
  12: { text: "J'écoute attentivement les idées et points de vue de mes coéquipiers avant de me forger ma propre opinion." },
  13: { text: "Je partage ouvertement mon point de vue lors des discussions d'équipe, même s'il diffère de l'opinion majoritaire." },
  14: { text: "Je tarde à informer l'équipe quand mes priorités ou mes plans changent." },
  15: { text: "Je donne des retours constructifs à mes collègues d'une manière à la fois honnête et respectueuse." },
  16: { text: "Je demande des clarifications plutôt que de supposer avoir compris ce qu'un collègue veut dire." },
  17: { text: "Je suis transparent(e) avec l'équipe sur les difficultés que je rencontre et qui pourraient affecter notre travail commun." },
  18: { text: "J'ai du mal à m'exprimer en réunion d'équipe même quand j'ai quelque chose de pertinent à apporter." },
  19: { text: "Je tiens systématiquement mes engagements dans les délais convenus." },
  20: { text: "Mes coéquipiers peuvent compter sur moi pour aller jusqu'au bout sans avoir à me relancer." },
  21: { text: "Je préviens à l'avance si je vais manquer un engagement ou une échéance." },
  22: { text: "Je suis prêt(e) à sortir de ma zone de confort quand l'équipe en a besoin." },
  23: { text: "Il m'arrive de laisser des tâches passer entre les mailles du filet quand personne ne les suit activement." },
  24: { text: "J'assume la responsabilité de ma part d'un projet commun du début jusqu'à la livraison finale." },
  25: { text: "Je suis en retard sur des actions convenues plus souvent que je ne le devrais." },
  26: { text: "Je vais au-delà du minimum requis quand le succès commun de l'équipe en dépend." },
  27: { text: "Je respecte mes engagements envers l'équipe même quand des circonstances personnelles rendent cela difficile." },
  28: { text: "Quand je suis en désaccord avec un coéquipier, je soulève le problème directement et calmement plutôt que de l'éviter." },
  29: { text: "Je fais l'effort de comprendre le point de vue de l'autre personne avant de répondre lors d'un conflit." },
  30: { text: "J'ai tendance à éviter les conversations difficiles avec mes collègues et à laisser les problèmes s'accumuler." },
  31: { text: "Dans un conflit, je me concentre sur la résolution du problème plutôt que sur la recherche d'un coupable." },
  32: { text: "Je fais l'effort de reconstruire la relation de travail après la résolution d'un désaccord." },
  33: { text: "Je suis capable de séparer le problème professionnel de tout sentiment personnel lorsqu'un conflit survient." },
  34: { text: "J'ai tendance à céder dans les désaccords même quand je pense sincèrement avoir raison." },
  35: { text: "Je n'implique un chef d'équipe ou un responsable dans un conflit qu'après l'échec véritable d'une résolution directe entre les parties." },
};
