export const TRANSLATION_STATUS = "draft" as const;

export const VR_QUESTIONS_FR: Record<number, { text: string; options: [string, string, string, string] }> = {
  1:  { text: "MÉDECIN est à PATIENT ce que AVOCAT est à :", options: ["Tribunal", "Justice", "Client", "Droit"] },
  2:  { text: "CHALEUR est à TEMPÉRATURE ce que DISTANCE est à :", options: ["Vitesse", "Longueur", "Poids", "Temps"] },
  3:  { text: "PINCEAU est à PEINTRE ce que SCALPEL est à :", options: ["Hôpital", "Médecine", "Chirurgien", "Infirmière"] },
  4:  { text: "Quel mot n'appartient PAS au groupe ? Observer · Remarquer · Ignorer · Percevoir · Détecter", options: ["Observer", "Remarquer", "Ignorer", "Percevoir"] },
  5:  { text: "Quel mot n'appartient PAS au groupe ? Piano · Guitare · Violon · Trompette · Sculpture", options: ["Piano", "Guitare", "Trompette", "Sculpture"] },
  6:  { text: "COURAGE est le contraire de :", options: ["Bravoure", "Lâcheté", "Force", "Audace"] },
  7:  { text: "TRANSPARENT est à OPAQUE ce que FLEXIBLE est à :", options: ["Élastique", "Souple", "Rigide", "Fragile"] },
  8:  { text: "Choisissez le mot qui complète le mieux la phrase : « Malgré la complexité de la tâche, elle l'a accomplie avec une _____ remarquable. »", options: ["Difficulté", "Rapidité", "Efficacité", "Hésitation"] },
  9:  { text: "Un synonyme de CONCIS est :", options: ["Verbeux", "Bref", "Détaillé", "Complexe"] },
  10: { text: "Un antonyme d'ABONDANT est :", options: ["Copieux", "Généreux", "Rare", "Riche"] },
  11: { text: "FEU est à FUMÉE ce que CAUSE est à :", options: ["Raison", "Effet", "Source", "Déclencheur"] },
  12: { text: "Choisissez le mot qui convient le mieux : « La décision du responsable était _____, car elle a satisfait les deux équipes. »", options: ["Controversée", "Ambiguë", "Équitable", "Arbitraire"] },
  13: { text: "BIBLIOTHÈQUE est à LIVRES ce que GALERIE est à :", options: ["Visiteurs", "Peintures", "Sculptures", "Artistes"] },
  14: { text: "Quel mot n'appartient PAS au groupe ? Anxieux · Nerveux · Appréhensif · Confiant · Inquiet", options: ["Anxieux", "Nerveux", "Confiant", "Inquiet"] },
  15: { text: "DILUER est à CONCENTRER ce que DIVISER est à :", options: ["Partager", "Séparer", "Multiplier", "Calculer"] },
  16: { text: "Un synonyme d'AMBIGU est :", options: ["Clair", "Certain", "Flou", "Décisif"] },
  17: { text: "« Elle a parlé avec une grande _____, chaque mot comptait. » Quel mot complète le mieux cette phrase ?", options: ["Concision", "Volume", "Enthousiasme", "Clarté"] },
  18: { text: "ARCHITECTE est à PLAN ce que COMPOSITEUR est à :", options: ["Orchestre", "Représentation", "Partition", "Instrument"] },
  19: { text: "Quel mot est le plus proche en signification de CORROBORER ?", options: ["Contredire", "Confirmer", "Créer", "Dissimuler"] },
  20: { text: "BRUYANT est à ASSOURDISSANT ce que FROID est à :", options: ["Glacial", "Frais", "Frisquet", "Tiède"] },
  21: { text: "Si tous les responsables assistent au point hebdomadaire, et que Sarah est responsable, que doit-on nécessairement en conclure ?", options: ["Sarah y assiste parfois", "Sarah assiste toujours au point", "Sarah peut manquer le point", "Sarah préside le point"] },
  22: { text: "Aucun membre de l'équipe finance ne travaille le week-end. Daniel travaille le week-end. Quelle conclusion en découle ?", options: ["Daniel fait peut-être partie de la finance", "Daniel ne fait pas partie de la finance", "Daniel travaille trop", "L'équipe finance ne travaille jamais"] },
  23: { text: "Certains analystes sont aussi chefs de projet. Tous les chefs de projet assistent à la réunion du lundi. Que doit-on nécessairement en conclure ?", options: ["Tous les analystes assistent à la réunion du lundi", "Aucun analyste n'assiste à la réunion du lundi", "Certains analystes assistent à la réunion du lundi", "Aucune de ces réponses"] },
  24: { text: "Chaque rapport soumis ce trimestre a été relu par un éditeur senior. Ce rapport n'a PAS été relu. Par conséquent :", options: ["Ce rapport a été soumis ce trimestre", "Ce rapport a peut-être été soumis ce trimestre", "Ce rapport n'a pas été soumis ce trimestre", "Aucune conclusion ne peut être tirée"] },
  25: { text: "LIVRE est à CHAPITRE ce que FILM est à :", options: ["Bobine", "Scène", "Réalisateur", "Écran"] },
  26: { text: "Quel mot n'appartient PAS au groupe ? Annuel · Mensuel · Trimestriel · Semestriel · Hebdomadaire · Instantané", options: ["Annuel", "Trimestriel", "Semestriel", "Instantané"] },
  27: { text: "Un synonyme de MÉTICULEUX est :", options: ["Négligent", "Minutieux", "Rapide", "Vague"] },
  28: { text: "Choisissez le meilleur mot : « Le témoin a fait un récit _____, se rappelant chaque détail avec précision. »", options: ["Vague", "Complet", "Textuel", "Résumé"] },
  29: { text: "TIÈDE est à CHAUD ce que INTÉRESSÉ est à :", options: ["Curieux", "Fasciné", "Conscient", "Engagé"] },
  30: { text: "Quelle phrase est la plus claire et la plus précise ?", options: ["Le projet se passe plutôt bien et on est un peu dans les temps.", "Le projet avance comme prévu et sera terminé vendredi.", "Les choses vont globalement bien pour le projet.", "Le projet semble correct pour la plupart des personnes impliquées."] },
};
