export const TRANSLATION_STATUS = "draft" as const;

export const WS_QUESTIONS_FR: Record<number, { text: string }> = {
  1:  { text: "Je préfère rassembler et analyser l'information avant de prendre des décisions." },
  2:  { text: "Je recherche les causes profondes plutôt que de simplement traiter les symptômes." },
  3:  { text: "J'aime résoudre des problèmes complexes de manière structurée et systématique." },
  4:  { text: "Je base mes décisions sur des données et des preuves plutôt que sur la seule intuition." },
  5:  { text: "J'évalue facilement les forces et faiblesses de différentes options." },
  6:  { text: "J'ai tendance à prendre des décisions rapides sans analyse approfondie." },
  7:  { text: "J'applique un raisonnement logique pour évaluer les risques avant d'agir." },
  8:  { text: "J'ai du mal à tirer des conclusions claires d'informations complexes ou ambiguës." },
  9:  { text: "Je porte une attention particulière aux détails dans tout ce que je fais." },
  10: { text: "Je vérifie soigneusement mon travail avant de le considérer terminé." },
  11: { text: "Je remarque des erreurs et incohérences que d'autres négligent souvent." },
  12: { text: "Je préfère un travail approfondi et de qualité plutôt que des résultats rapides et approximatifs." },
  13: { text: "Je tiens mes dossiers et ma documentation bien organisés et à jour." },
  14: { text: "Il m'arrive de négliger des détails importants quand je travaille rapidement." },
  15: { text: "Je vérifie le résultat final par rapport aux exigences initiales avant de le soumettre." },
  16: { text: "Je trouve les tâches détaillées ou répétitives frustrantes." },
  17: { text: "Je préfère travailler en équipe plutôt que de manière indépendante." },
  18: { text: "Je recherche activement l'avis de mes collègues avant de prendre des décisions importantes." },
  19: { text: "J'ajuste mon approche quand d'autres proposent une meilleure perspective." },
  20: { text: "J'établis facilement des relations de travail avec de nouveaux collègues." },
  21: { text: "Je contribue de façon constructive aux discussions de groupe et à la planification d'équipe." },
  22: { text: "Je préfère travailler de manière indépendante plutôt que de dépendre des autres." },
  23: { text: "Je partage le mérite des succès d'équipe avec tous les contributeurs." },
  24: { text: "J'ai du mal à me rallier à des décisions d'équipe avec lesquelles je suis personnellement en désaccord." },
  25: { text: "Je m'ajuste rapidement quand les priorités ou les plans changent de façon inattendue." },
  26: { text: "Je considère le changement comme une opportunité plutôt qu'une perturbation." },
  27: { text: "Je suis à l'aise pour travailler dans l'ambiguïté quand toutes les informations ne sont pas encore disponibles." },
  28: { text: "Je peux passer d'un type de tâche à un autre sans perdre ma concentration ni mon élan." },
  29: { text: "Je reste efficace dans des situations de forte pression ou d'incertitude." },
  30: { text: "J'ai du mal à travailler efficacement en dehors de mes habitudes familières." },
  31: { text: "J'apprends volontiers de nouveaux outils, systèmes ou méthodes lorsque cela est nécessaire." },
  32: { text: "Les changements inattendus dans mes plans ont tendance à affecter négativement ma performance." },
  33: { text: "Je reste concentré(e) sur l'atteinte des objectifs même quand le chemin devient difficile." },
  34: { text: "Je fixe des objectifs personnels clairs et suis activement mes progrès par rapport à eux." },
  35: { text: "Je prends des initiatives sans attendre qu'on me le demande." },
  36: { text: "Je me pousse, ainsi que mon équipe, à obtenir d'excellents résultats." },
  37: { text: "Je privilégie les résultats plutôt que le confort de routines familières ou sûres." },
  38: { text: "J'ai tendance à perdre mon élan quand un projet rencontre des revers importants." },
  39: { text: "Je suis proactif/proactive pour identifier ce qu'il faut faire ensuite." },
  40: { text: "J'ai du mal à rester concentré(e) quand la reconnaissance ou les retours ne sont pas immédiats." },
};
