import type { AgencyBriefData } from "./types";

// Static fake data for template development. See types.ts for the shape this
// will take once wired to real candidate/shortlist data.
export const FAKE_AGENCY_BRIEF: AgencyBriefData = {
  agencyName: "Atlas Talent Partners",
  roleTitle: "Customer Service Agent",
  shortlistName: "Customer Service Shortlist — July 2026",
  date: "July 2026",
  preparedBy: "Atlas Talent Partners",
  showClientName: false,
  snapshot: {
    totalCandidates: 5,
    completedAssessments: 4,
    recommendedForInterview: 2,
    requiresVerification: 2,
    incompleteEvidence: 1,
  },
  candidates: [
    {
      name: "Sara M.",
      recommendation: "Recommended for client interview",
      clientPriority: "Priority 1",
      roleFit: "Strong",
      confidence: "High",
      summary:
        "Sara shows strong evidence of alignment with the Customer Service Agent role, especially in communication clarity, customer handling judgment, and structured problem solving.",
      matrixNote: "Strong alignment across communication, customer handling, and structured problem solving.",
      keyVerificationPhrase: "stress handling",
      strengths: ["Communication clarity", "Customer handling", "Structured problem solving"],
      pointsToVerify: ["Stress handling in high-volume situations"],
      interviewFocus: "Ask about difficult customer interactions and workload pressure.",
      interviewVerifies: "Confirms composure and consistent judgment when customer volume and pressure increase.",
    },
    {
      name: "Yassine B.",
      recommendation: "Recommended with verification",
      clientPriority: "Priority 2",
      roleFit: "Moderate to strong",
      confidence: "Medium",
      summary:
        "Yassine shows consistent evidence of attention to detail and reliability, with a strong pace of learning. Interview discussion should confirm his verbal confidence under pressure.",
      matrixNote: "Reliable and detail-oriented with a fast learning curve; verbal confidence under pressure not yet confirmed.",
      keyVerificationPhrase: "verbal confidence under pressure",
      strengths: ["Attention to detail", "Reliability", "Learning agility"],
      pointsToVerify: ["Verbal confidence and speed under pressure"],
      interviewFocus: "Ask for examples of handling multiple customer requests at once.",
      interviewVerifies: "Confirms his ability to stay clear and composed when handling several requests at once.",
    },
    {
      name: "Amine K.",
      recommendation: "Keep under review",
      clientPriority: "Review",
      roleFit: "Moderate",
      confidence: "Medium",
      summary:
        "Amine demonstrates consistency and calm, process-driven communication. The evidence available does not yet clarify how he adapts when a situation falls outside standard procedure.",
      matrixNote: "Consistent, process-driven communicator; adaptability outside standard procedure not yet evidenced.",
      keyVerificationPhrase: "adaptability",
      strengths: ["Consistency", "Process following", "Calm communication"],
      pointsToVerify: ["Initiative and adaptability"],
      interviewFocus: "Ask how he reacts when procedures change.",
      interviewVerifies: "Confirms how he adjusts his approach when a situation falls outside the standard process.",
    },
    {
      name: "Lina R.",
      recommendation: "Lower priority for this role",
      clientPriority: "Lower priority",
      roleFit: "Limited",
      confidence: "Medium",
      summary:
        "Lina shows a positive attitude and basic communication ability. Current evidence suggests she may need more development in role-specific judgment before this position is a strong fit.",
      matrixNote: "Positive attitude and basic communication; role-specific judgment needs further development.",
      keyVerificationPhrase: "role-specific judgment",
      strengths: ["Basic communication", "Positive attitude"],
      pointsToVerify: ["Role-specific judgment and attention to detail"],
      interviewFocus: "Ask scenario-based customer service questions if proceeding.",
      interviewVerifies: "Confirms her ability to apply sound judgment in realistic customer service scenarios.",
    },
    {
      name: "Mehdi T.",
      recommendation: "Not enough evidence",
      clientPriority: "Incomplete",
      roleFit: "Incomplete",
      confidence: "Low",
      summary:
        "Mehdi has not yet completed the assessment battery for this shortlist. No recommendation can be made until the outstanding assessments are finished.",
      matrixNote: "Assessment battery not yet completed — no recommendation possible at this time.",
      keyVerificationPhrase: "assessment completion",
      strengths: ["Assessment incomplete"],
      pointsToVerify: ["Completion required before recommendation"],
      interviewFocus: "Not ready for client recommendation.",
      interviewVerifies: "Not applicable until outstanding assessments are completed.",
    },
  ],
};
