export type CServDimension = "Empathy" | "Problem Resolution" | "Communication" | "Patience";

export interface CServQuestion {
  id: number;
  text: string;
  dimension: CServDimension;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const CSERV_QUESTIONS: CServQuestion[] = [
  // Empathy (9)
  { id: 1,  text: "A customer calls extremely upset about a delayed order. What is your first action?", dimension: "Empathy", options: ["Immediately explain the operational reasons for the delay", "Acknowledge how frustrating that must be and apologise sincerely before asking for any details", "Transfer the call to a manager who deals with complaints", "Ask for the order number so you can look up the status straight away"], correct: 1 },
  { id: 2,  text: "A customer says: 'No one at your company ever listens to me.' What is the best response?", dimension: "Empathy", options: ["'I'm sorry you feel that way — let me check your account.'", "'I want to make sure today is different. Please tell me what is happening and I will give this my full attention.'", "Defend your company's service record with facts", "Apologise and immediately escalate to a senior agent without engaging further"], correct: 1 },
  { id: 3,  text: "Which response best demonstrates genuine empathy to a frustrated customer?", dimension: "Empathy", options: ["'I understand.'", "'That should not have happened — it makes complete sense that you are frustrated, and I want to fix this for you.'", "'Everyone makes mistakes — our team is only human.'", "'You are not the first customer this has happened to, so we do have a process for it.'"], correct: 1 },
  { id: 4,  text: "A customer is upset because a product they relied on failed during an important event. What is the best response?", dimension: "Empathy", options: ["Move straight to troubleshooting — solving the problem is what they need", "Offer a refund or replacement immediately", "Acknowledge the emotional impact first: 'I am so sorry this happened at such an important moment for you'", "Explain the product's stated limitations and warranty terms"], correct: 2 },
  { id: 5,  text: "A customer says they are embarrassed because they could not figure out how to use your product. What is the best response?", dimension: "Empathy", options: ["Reassure them the product is straightforward for the majority of users", "Tell them many customers find exactly this step confusing and offer to walk through it with them right now", "Send a link to the user guide and let them read through it", "Transfer to technical support"], correct: 1 },
  { id: 6,  text: "How can you best show empathy in a written customer service response?", dimension: "Empathy", options: ["Begin with 'Dear Customer' and move directly to the resolution", "Open by specifically acknowledging the customer's experience, then address the issue", "Use formal, professional language throughout to convey competence", "List all steps the customer must take to resolve their issue clearly and efficiently"], correct: 1 },
  { id: 7,  text: "A customer is angry about a billing error on their account. Before requesting any account details, what should you do?", dimension: "Empathy", options: ["Explain the billing process so they understand how it works", "Acknowledge the error clearly and state that you will make it right", "Tell them these errors are occasionally unavoidable in large billing systems", "Transfer to the billing department immediately"], correct: 1 },
  { id: 8,  text: "Which approach best builds long-term customer trust?", dimension: "Empathy", options: ["Always offering discounts when a customer raises a complaint", "Responding quickly with polite but generic replies", "Consistently following through on what you say you will do, and proactively checking in after issues are resolved", "Escalating every complaint to a senior team member to show it is taken seriously"], correct: 2 },
  { id: 9,  text: "A call ends with a resolution in place, but the customer still does not seem satisfied. What is the best next step?", dimension: "Empathy", options: ["Close the case — the issue was technically resolved", "Follow up 24–48 hours later to confirm the resolution worked and to check that they now feel heard", "Automatically apply a discount to their next invoice", "Trigger an immediate satisfaction survey while the interaction is fresh"], correct: 1 },
  // Problem Resolution (9)
  { id: 10, text: "A customer reports a defective product. What is the most effective first step?", dimension: "Problem Resolution", options: ["Apologise and offer a full refund or replacement immediately", "Gather the details of the defect — what happened, when, how it affected them, and what outcome they need", "Tell the customer to return the product through the standard process", "Transfer to a specialist team without collecting any information first"], correct: 1 },
  { id: 11, text: "A customer is requesting a refund your policy does not normally cover. What is the best approach?", dimension: "Problem Resolution", options: ["Refuse immediately and cite your policy verbatim", "Acknowledge the situation fully, check whether any exception applies, and explain all available options clearly", "Offer store credit without exploring the full situation", "Escalate without gathering all the relevant facts first"], correct: 1 },
  { id: 12, text: "You have resolved a customer's issue but are not fully confident the fix will hold. What do you do?", dimension: "Problem Resolution", options: ["Tell the customer the problem is definitely and permanently fixed", "Be transparent: explain what you have done and set a timeline to confirm it has resolved the issue", "Close the ticket and wait to see if they contact you again", "Hand the ticket to a technical team and close your involvement"], correct: 1 },
  { id: 13, text: "A customer contacts you with a complex issue that requires input from multiple internal teams. What is the best approach?", dimension: "Problem Resolution", options: ["Transfer to the first available team and let them coordinate", "Own the issue personally, coordinate internally, and keep the customer updated at every stage until it is fully resolved", "Ask the customer to contact each relevant team directly", "Ask the customer to submit their issue in writing before any action is taken"], correct: 1 },
  { id: 14, text: "A customer has contacted you about the same recurring problem for the third time. What should you do differently?", dimension: "Problem Resolution", options: ["Resolve it the same way as before — the process has worked in the past", "Resolve the immediate issue AND escalate internally to investigate and address the root cause so it does not recur", "Offer a discount for the inconvenience and close the ticket quickly", "Ask the customer to change their behaviour to avoid triggering the problem"], correct: 1 },
  { id: 15, text: "After resolving a customer's issue, which action adds the most value?", dimension: "Problem Resolution", options: ["Close the case immediately — your time is needed for other customers", "Confirm the resolution met the customer's expectations and ask if there is anything else they need before closing", "Ask the customer to leave a review of the interaction", "Send a promotional offer as a goodwill gesture"], correct: 1 },
  { id: 16, text: "A customer wants a resolution your systems cannot currently provide. What is the best response?", dimension: "Problem Resolution", options: ["Tell them it is technically impossible and close the case", "Acknowledge the limitation clearly, explain what you can do right now, and set realistic expectations about what is possible and by when", "Promise what they are asking for to satisfy them in the moment", "Blame a different department for the limitation"], correct: 1 },
  { id: 17, text: "Two customers contact you simultaneously with urgent issues. How do you manage this?", dimension: "Problem Resolution", options: ["Try to handle both in real-time simultaneously across two channels", "Acknowledge both immediately, set a realistic response timeline for each, and prioritise by severity", "Ask the less urgent customer to call back when you are free", "Escalate both to a manager immediately"], correct: 1 },
  { id: 18, text: "A customer is angry about the speed of resolution and is demanding immediate action. What is the best response?", dimension: "Problem Resolution", options: ["Tell them to be patient — good resolutions take time", "Explain clearly what action you are taking right now and give a realistic, specific timeframe for the next update", "Escalate immediately to get them off your queue", "Offer financial compensation without discussing the situation further"], correct: 1 },
  // Communication (9)
  { id: 19, text: "A customer asks a question you do not know the answer to. What is the best response?", dimension: "Communication", options: ["Provide your best guess confidently so they feel helped immediately", "Say 'I don't know' and end the interaction", "'Great question — let me find the correct answer and get back to you within [specific realistic timeframe].'", "Transfer to another agent without providing any context to either party"], correct: 2 },
  { id: 20, text: "A customer uses technical language you are not familiar with. What is the best action?", dimension: "Communication", options: ["Pretend you understand and continue the interaction", "Ask a clarifying question: 'Could you help me understand what you mean by [term] so I can give you the most accurate help?'", "Transfer immediately to a technical specialist", "Ask the customer to simplify their language before continuing"], correct: 1 },
  { id: 21, text: "Which written response best closes a customer service interaction?", dimension: "Communication", options: ["'Please let us know if there is anything else.'", "'Your issue has been logged in our system.'", "'I have resolved [the specific issue]. If you have any questions about the solution or run into anything else, please do not hesitate to reach out.'", "'Thanks for contacting us today.'"], correct: 2 },
  { id: 22, text: "A customer responds angrily to a resolution you offered. What is the best communication approach?", dimension: "Communication", options: ["Match their energy to demonstrate you are taking it seriously", "Use a calm, empathetic tone and ask what outcome would make them feel the issue is fully resolved", "Repeat your original resolution more firmly and clearly", "Escalate without any further communication from you"], correct: 1 },
  { id: 23, text: "You need to deliver bad news to a customer — their order has been cancelled. What is the best approach?", dimension: "Communication", options: ["Lead with the bad news immediately to respect their time", "Bury the news in a long message so the impact is softened", "Acknowledge their experience, deliver the news honestly and clearly, then focus immediately on what you can do to help", "Delay telling them and see if the situation resolves itself first"], correct: 2 },
  { id: 24, text: "When is it appropriate to use technical jargon with a customer?", dimension: "Communication", options: ["Always — it establishes credibility and expertise", "Never — it is always off-putting to customers", "Only when the customer has used technical language themselves, indicating comfort with it", "Only when you need to end the interaction quickly"], correct: 2 },
  { id: 25, text: "You are handling a live chat with multiple customers and one takes several minutes to respond. What is the best action?", dimension: "Communication", options: ["Close the chat after two minutes of inactivity", "Focus entirely on the responsive customers and return when the quiet one messages", "Send a brief message checking they are still there and confirming you are ready when they are", "Escalate after one minute of silence"], correct: 2 },
  { id: 26, text: "A customer calls with a complaint they already emailed about. What should you do first?", dimension: "Communication", options: ["Ask them to repeat the full story from the beginning", "Pull up their email before they finish explaining so you can reference their previous contact and avoid making them repeat themselves", "Transfer to whoever handled the original email", "Ask why they are calling when they already emailed"], correct: 1 },
  { id: 27, text: "You explained a resolution, but the customer did not understand and asked the same question again. What is the best response?", dimension: "Communication", options: ["Copy and paste your previous answer word for word", "Apologise and try a different explanation or a different format that may work better for them", "Ask why they are not understanding your response", "Transfer to a senior agent who may explain it better"], correct: 1 },
  // Patience (8)
  { id: 28, text: "A customer is explaining their issue very slowly and in excessive detail. What is the best approach?", dimension: "Patience", options: ["Politely interrupt and ask them to get to the point quickly", "Let them finish — they may be sharing context that turns out to be important — then summarise what you understood", "Multitask while they speak to make efficient use of your time", "Ask them to email instead so they can structure their thoughts first"], correct: 1 },
  { id: 29, text: "A customer contacts you for the third time about a recurring issue. They are visibly frustrated. How do you approach this differently?", dimension: "Patience", options: ["Follow the standard resolution process — it is correct procedure", "Explicitly acknowledge the pattern: 'I can see this has happened before and that is unacceptable. I am going to personally make sure this is resolved today.'", "Offer a refund immediately to break the cycle without deeper investigation", "Ask the customer to be patient while the underlying system catches up"], correct: 1 },
  { id: 30, text: "A customer uses rude or profane language. What is the best response?", dimension: "Patience", options: ["Use similar assertive language so they know you are not intimidated", "Terminate the interaction immediately", "Stay calm, acknowledge their frustration, work to resolve the underlying issue, and if the language continues, explain clearly what you need to continue the conversation productively", "Ignore the language entirely and continue as though it did not happen"], correct: 2 },
  { id: 31, text: "A customer asks a question that seems simple but has a complex, nuanced answer. What do you do?", dimension: "Patience", options: ["Give the quick, simplified answer to save time for both parties", "Take the time needed to give a complete and accurate answer, even if it takes longer", "Point them to the FAQ or knowledge base", "Transfer to a specialist to avoid giving an incomplete answer"], correct: 1 },
  { id: 32, text: "You have many customers waiting, but the current customer is still speaking and not yet resolved. What is the most appropriate action?", dimension: "Patience", options: ["Rush the current customer to a conclusion", "Give the current customer the time they need to feel resolved — then find ways to work through the queue more efficiently afterwards", "Put the customer on hold without warning them", "Transfer to a colleague mid-interaction"], correct: 1 },
  { id: 33, text: "A customer asks the same clarifying question multiple times because they are not understanding your responses. What is the best action?", dimension: "Patience", options: ["Copy and paste your previous answer — they need to read it more carefully", "Apologise and try a different format or explanation approach that may suit them better", "Ask why they keep asking the same question", "Transfer to a senior agent to handle the misunderstanding"], correct: 1 },
  { id: 34, text: "A customer is venting at length before reaching their actual request. What is the best approach?", dimension: "Patience", options: ["Politely interrupt after 30 seconds to redirect to the practical issue", "Let them finish, then respond to the emotional content before moving to the practical question", "Ask them repeatedly to focus on the specific issue", "Put them on hold until they have settled"], correct: 1 },
  { id: 35, text: "After a long and difficult interaction, the customer sincerely thanks you and says you have restored their confidence in your company. What is the most effective response?", dimension: "Patience", options: ["Say 'No problem' and bring the interaction to a close", "Acknowledge that you were glad to help, briefly confirm the next steps, and wish them well genuinely", "Ask if they would be willing to leave a positive review", "Offer them a discount on their next purchase as a reward for their patience"], correct: 1 },
];

export const CSERV_DURATION_SECONDS = 20 * 60;

export const CSERV_DIMENSIONS: Array<{ label: CServDimension; description: string; className: string }> = [
  { label: "Empathy",            description: "Understanding and acknowledging customer feelings.", className: "bg-pink-500/10 text-pink-300" },
  { label: "Problem Resolution", description: "Effectively diagnosing and solving customer issues.", className: "bg-blue-500/10 text-blue-300" },
  { label: "Communication",      description: "Clarity, accuracy, and appropriateness in all interactions.", className: "bg-sky-500/10 text-sky-300" },
  { label: "Patience",           description: "Composure and consistency with difficult or slow interactions.", className: "bg-violet-500/10 text-violet-300" },
];

export function scoreCServ(answers: (number | null)[]) {
  const dimStats: Record<CServDimension, { correct: number; total: number }> = {
    Empathy: { correct: 0, total: 0 },
    "Problem Resolution": { correct: 0, total: 0 },
    Communication: { correct: 0, total: 0 },
    Patience: { correct: 0, total: 0 },
  };
  let totalCorrect = 0;
  CSERV_QUESTIONS.forEach((q, i) => {
    dimStats[q.dimension].total++;
    if (answers[i] !== null && answers[i] === q.correct) {
      totalCorrect++;
      dimStats[q.dimension].correct++;
    }
  });
  const percentage = Math.round((totalCorrect / CSERV_QUESTIONS.length) * 100);
  const dimensions = Object.fromEntries(
    (Object.keys(dimStats) as CServDimension[]).map((d) => {
      const { correct, total } = dimStats[d];
      return [d, total > 0 ? Math.round((correct / total) * 100) : 0];
    })
  ) as Record<CServDimension, number>;
  return { correct: totalCorrect, total: CSERV_QUESTIONS.length, percentage, dimensions };
}
