export type DMDimension = "Analysis" | "Judgment" | "Risk Assessment" | "Speed";

export interface DMQuestion {
  id: number;
  text: string;
  dimension: DMDimension;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const DM_QUESTIONS: DMQuestion[] = [
  // Analysis (8)
  { id: 1,  text: "You must choose between two vendor proposals. What is the most effective first step?", dimension: "Analysis", options: ["Choose the proposal with the lowest price", "Define clear evaluation criteria based on your organisation's priorities before comparing the proposals", "Go with the more recognisable brand name", "Ask your manager which one to choose"], correct: 1 },
  { id: 2,  text: "You need to make a decision but the available data is incomplete. What is the best approach?", dimension: "Analysis", options: ["Wait until you have complete and perfect data", "Identify the most critical missing information, gather what you can within the available time, and proceed with clearly stated assumptions", "Make a confident decision and present it without mentioning the data gaps", "Delay the decision indefinitely until more information is available"], correct: 1 },
  { id: 3,  text: "You receive two conflicting analyses of the same data set. What is the best action?", dimension: "Analysis", options: ["Use the analysis that supports the conclusion you were already leaning towards", "Default to the most recently produced analysis", "Understand the methodology and assumptions behind each analysis and determine which is more valid for your specific question", "Discard both and commission a third analysis before making any decision"], correct: 2 },
  { id: 4,  text: "What is the biggest risk of making a decision based solely on qualitative feedback from a small group of customers?", dimension: "Analysis", options: ["Qualitative feedback is always accurate and therefore reliable", "The feedback may not represent the broader population and could reflect biases from an unrepresentative sample", "Qualitative data is too complex to analyse effectively", "Qualitative feedback always leads to the wrong decision"], correct: 1 },
  { id: 5,  text: "You need to choose between three options and have limited time for analysis. What is the most effective approach?", dimension: "Analysis", options: ["Spend equal time analysing each of the three options in full", "Identify the two or three most important decision criteria and quickly score each option against them", "Choose the middle option as a reasonable compromise", "Copy the approach taken by someone who faced a similar decision previously"], correct: 1 },
  { id: 6,  text: "When is it most appropriate to request additional information before making a decision?", dimension: "Analysis", options: ["When the decision is largely irreversible and the potential consequences are significant", "In every situation — more data always improves decision quality", "Only when your manager specifically requests it", "Never — gathering information delays action and signals hesitation"], correct: 0 },
  { id: 7,  text: "The data supporting a major proposed decision is 18 months old. What should you do?", dimension: "Analysis", options: ["Use it — business data rarely changes significantly in 18 months", "Flag the issue and verify whether the data is still current and applicable to current conditions before proceeding", "Proceed with the decision and note the data age in a brief footnote", "Halt the decision and commission a full new study before moving forward"], correct: 1 },
  { id: 8,  text: "Before making an important business decision, what is the single most valuable analytical step?", dimension: "Analysis", options: ["Consult the most senior available person and follow their recommendation", "Identify and test the key assumptions that underlie each option being considered", "Copy a decision made by a competitor in a similar situation", "Trust your instinct — extensive analysis slows you down without improving outcomes"], correct: 1 },
  // Judgment (8)
  { id: 9,  text: "A colleague presents a compelling argument for a decision you believe is wrong. What do you do?", dimension: "Judgment", options: ["Agree with them to avoid creating conflict", "Ask targeted questions to test the argument's logic and evidence before forming or changing your view", "Disagree loudly and publicly to ensure your position is registered", "Go along with the majority view in the room"], correct: 1 },
  { id: 10, text: "You must make a judgment call under time pressure with limited information. What is the most effective approach?", dimension: "Judgment", options: ["Delay until you have more information — a premature decision is worse than no decision", "Identify the single most critical factor, make the best decision based on it, and stay ready to revise quickly if new information emerges", "Go entirely with instinct — structured thinking takes too long under pressure", "Ask someone with more authority to make the call on your behalf"], correct: 1 },
  { id: 11, text: "A well-reasoned decision you made turns out to be wrong. What does this indicate?", dimension: "Judgment", options: ["You are a fundamentally poor decision-maker and should defer more often", "You should trust your instincts more and rely less on structured reasoning in future", "Even well-reasoned decisions can be wrong under uncertainty — the goal is to improve the quality of your process, not just chase good outcomes", "You should always consult more people before deciding in future"], correct: 2 },
  { id: 12, text: "You are asked for a clear recommendation but the evidence genuinely points in multiple directions. What do you do?", dimension: "Judgment", options: ["Pick any option — a recommendation should not reveal uncertainty", "Make a recommendation based on the most robust evidence available, state the uncertainty clearly, and note what new information would cause you to revise your view", "Refuse to give a recommendation until the evidence is unambiguous", "Give the recommendation you believe your manager or stakeholder wants to hear"], correct: 1 },
  { id: 13, text: "A popular decision within your team carries a significant risk that you have identified but others have not. What do you do?", dimension: "Judgment", options: ["Go along with the team — consensus usually indicates the correct path", "Raise your concern clearly, explain your reasoning, and propose either a specific safeguard or an alternative course of action", "Say nothing but privately prepare for the decision to fail", "Escalate to leadership without first raising the concern with the team"], correct: 1 },
  { id: 14, text: "Every available option in a difficult decision carries significant downsides. What is the most effective approach?", dimension: "Judgment", options: ["Avoid making any decision and wait for a better option to emerge", "Choose the option with the most tolerable downside, communicate the tradeoffs transparently, and prepare a mitigation plan", "Always default to the least expensive option when facing significant uncertainty", "Make a decision by random selection — the options are equally poor"], correct: 1 },
  { id: 15, text: "A junior team member flags a concern about your decision that you had not considered. What do you do?", dimension: "Judgment", options: ["Acknowledge the concern politely but proceed with your existing plan", "Investigate the concern seriously and, if it is valid, incorporate it into your final decision", "Ask them to submit the concern in writing before taking it seriously", "Reassure them that you have the decision fully covered"], correct: 1 },
  { id: 16, text: "In hindsight, a decision you made was correct, but it was largely based on incomplete information. What is the most mature assessment?", dimension: "Judgment", options: ["You made a great decision and should trust your instincts more going forward", "The outcome was good but the decision-making process was still flawed — improving the process matters regardless of the outcome", "You were fortunate and should avoid making decisions under uncertainty in future", "The good outcome validates the approach and confirms it was the right process"], correct: 1 },
  // Risk Assessment (7)
  { id: 17, text: "You are evaluating whether a risk is acceptable. What is the most effective method?", dimension: "Risk Assessment", options: ["Accept any risk automatically if its probability appears low", "Assess both the probability of the risk occurring and its potential impact, then weigh these against the benefit of proceeding", "Ask the most risk-averse person on your team for their opinion", "Compare your organisation's risk appetite against a competitor's approach"], correct: 1 },
  { id: 18, text: "You have identified a project risk with a low probability but a potentially catastrophic impact. How do you treat it?", dimension: "Risk Assessment", options: ["Ignore it — the probability is low enough to discount", "Log it as a risk but take no active mitigation steps", "Develop a contingency plan even though the probability is low, because the severity of the potential impact is too great to leave unmanaged", "Immediately escalate and halt the project until the risk is fully eliminated"], correct: 2 },
  { id: 19, text: "A decision must be made urgently and there is no time for a full risk assessment. What is the most responsible approach?", dimension: "Risk Assessment", options: ["Skip all risk assessment — the urgency overrides the need for it", "Take five to ten minutes to identify the two or three most significant risks and determine whether any represent deal-breakers", "Refuse to proceed without a complete formal risk assessment", "Ask the legal team to approve the decision before any action is taken"], correct: 1 },
  { id: 20, text: "After a major decision has been implemented, when should active risk monitoring stop?", dimension: "Risk Assessment", options: ["Once the decision has been fully implemented and the initial transition period is complete", "At the first clear sign that outcomes are trending positively", "Risk monitoring should continue throughout the life of the decision and adapt as circumstances change", "After the first formal quarterly review has been completed"], correct: 2 },
  { id: 21, text: "A proposal offers very large potential upside but also very large potential downside. What is the most balanced approach?", dimension: "Risk Assessment", options: ["Always pursue the largest available upside regardless of the corresponding downside", "Reject it categorically — large risks are never strategically justified", "Assess whether the risk can be staged, mitigated, or capped, and whether the expected value justifies proceeding on those terms", "Make the decision based on how ambitious the team is feeling at the time"], correct: 2 },
  { id: 22, text: "A colleague argues: 'We have always done it this way, so the risk is low.' What is the critical flaw in this reasoning?", dimension: "Risk Assessment", options: ["There is no meaningful flaw — track record is the most reliable predictor of future risk", "Past success does not guarantee future results, especially if the context, environment, or scale has changed significantly", "The reasoning fails to account for the cost of switching to a different approach", "It ignores what competitors are doing differently and why"], correct: 1 },
  { id: 23, text: "You are reviewing a proposal where the risk assessment was completed six months ago. Market conditions have changed significantly since then. What do you do?", dimension: "Risk Assessment", options: ["Proceed on the original risk assessment — a formal review was conducted", "Commission an updated risk assessment before making any final decision", "Add a caveat to the proposal noting the time gap and proceed anyway", "Ask the original assessor to reconfirm their previous conclusions verbally"], correct: 1 },
  // Speed (7)
  { id: 24, text: "An unexpected event requires an immediate decision with very limited information. What is the best approach?", dimension: "Speed", options: ["Delay the decision until you have gathered more information", "Make the best decision available with the information you have, state your assumptions clearly, and be ready to revise quickly", "Ask someone with more authority to make the decision on your behalf", "Take no action — inaction is always safer than an incorrect decision"], correct: 1 },
  { id: 25, text: "How do you determine whether a decision needs to be made immediately or can wait?", dimension: "Speed", options: ["All decisions should be made immediately — hesitation is a sign of weakness", "No decision should ever be made immediately — always allow time for reflection", "Assess the cost of delay against the benefit of gathering more information — some decisions improve with time, others deteriorate rapidly", "Always ask your manager before deciding how urgently to treat any decision"], correct: 2 },
  { id: 26, text: "You have been deliberating over a decision for days and remain genuinely uncertain. What is the best action?", dimension: "Speed", options: ["Continue deliberating until you feel fully certain before committing", "Set a personal decision deadline, make the best call based on what you know, and plan how you will monitor and adjust if needed", "Ask someone else to make the decision on your behalf", "Use a structured random selection method to break the deadlock"], correct: 1 },
  { id: 27, text: "When is it appropriate to make a decision quickly without consulting others?", dimension: "Speed", options: ["Whenever you feel personally confident in your view", "When the decision is clearly within your authority, the stakes are not extreme, and the time cost of consultation would outweigh the benefit of additional input", "Never — always consult others to build buy-in and reduce personal risk", "When you want to be seen as decisive and capable of independent action"], correct: 1 },
  { id: 28, text: "A team spends three hours in discussion deciding between two software tools with very similar features and pricing. What does this suggest?", dimension: "Speed", options: ["The team is being appropriately rigorous for an important purchasing decision", "The team has likely over-invested decision-making time in a relatively low-stakes, reversible choice", "All purchasing decisions deserve equal deliberation time regardless of scale", "The right tool was genuinely impossible to identify without the time investment"], correct: 1 },
  { id: 29, text: "After making a fast decision in an emergency, you realise it was suboptimal. What is the most productive next step?", dimension: "Speed", options: ["Blame yourself heavily — better preparation should have prevented the suboptimal outcome", "Assess whether the decision was reasonable given what you knew at the time; if yes, adapt and move forward; if no, identify what to change next time", "Attribute the poor outcome entirely to the emergency conditions", "Avoid making fast decisions in the future as a standing policy"], correct: 1 },
  { id: 30, text: "Which factor most effectively separates a fast, effective decision-maker from one who simply rushes?", dimension: "Speed", options: ["The speed at which they reach a conclusion", "The confidence with which they communicate their decision to others", "Calibrating the depth of analysis to the actual stakes and reversibility of the decision rather than applying the same approach to every situation", "Their track record of being correct more often than not"], correct: 2 },
];

export const DM_DURATION_SECONDS = 20 * 60;

export const DM_DIMENSIONS: Array<{ label: DMDimension; description: string; className: string }> = [
  { label: "Analysis",         description: "Gathering and evaluating information before deciding.", className: "bg-blue-500/10 text-blue-300" },
  { label: "Judgment",         description: "Making sound calls in complex or ambiguous situations.", className: "bg-indigo-500/10 text-indigo-300" },
  { label: "Risk Assessment",  description: "Evaluating and managing the risks of each option.", className: "bg-amber-500/10 text-amber-300" },
  { label: "Speed",            description: "Calibrating decision speed appropriately to context.", className: "bg-emerald-500/10 text-emerald-300" },
];

export function scoreDM(answers: (number | null)[]) {
  const dimStats: Record<DMDimension, { correct: number; total: number }> = {
    Analysis: { correct: 0, total: 0 },
    Judgment: { correct: 0, total: 0 },
    "Risk Assessment": { correct: 0, total: 0 },
    Speed: { correct: 0, total: 0 },
  };
  let totalCorrect = 0;
  DM_QUESTIONS.forEach((q, i) => {
    dimStats[q.dimension].total++;
    if (answers[i] !== null && answers[i] === q.correct) {
      totalCorrect++;
      dimStats[q.dimension].correct++;
    }
  });
  const percentage = Math.round((totalCorrect / DM_QUESTIONS.length) * 100);
  const dimensions = Object.fromEntries(
    (Object.keys(dimStats) as DMDimension[]).map((d) => {
      const { correct, total } = dimStats[d];
      return [d, total > 0 ? Math.round((correct / total) * 100) : 0];
    })
  ) as Record<DMDimension, number>;
  return { correct: totalCorrect, total: DM_QUESTIONS.length, percentage, dimensions };
}
