export type IEDimension = "Honesty" | "Accountability" | "Ethics" | "Trustworthiness";

export interface IEQuestion {
  id: number;
  text: string;
  dimension: IEDimension;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const IE_QUESTIONS: IEQuestion[] = [
  // Honesty (8)
  { id: 1,  text: "You made an error in a report that has already been shared with senior leadership. What do you do?", dimension: "Honesty", options: ["Hope no one notices and quietly correct it in the next version", "Inform the relevant parties immediately, correct the error, and explain what happened", "Wait to see if anyone raises it before taking any action", "Ask a trusted colleague to flag it anonymously on your behalf"], correct: 1 },
  { id: 2,  text: "Your manager asks for a project status update, but the project is behind schedule. What do you say?", dimension: "Honesty", options: ["Report that things are 'broadly on track' to avoid additional scrutiny", "Give an honest update on the actual status, the reasons for the delay, and your plan to address it", "Provide a vague update that does not commit to anything specific", "Tell them you will send a written update later and delay the conversation"], correct: 1 },
  { id: 3,  text: "During a sales presentation, a client asks about a product feature that does not yet exist. What do you do?", dimension: "Honesty", options: ["Confirm that the feature exists — it will probably be ready before they need it", "Tell them it is 'under development' without clarifying when or whether it will be available", "Be honest: the feature does not exist yet, share what is on the roadmap, and let them decide with accurate information", "Change the subject smoothly before they follow up"], correct: 2 },
  { id: 4,  text: "You strongly disagree with a key conclusion in a colleague's report that they are clearly proud of. What do you do?", dimension: "Honesty", options: ["Tell them the report is excellent to preserve the relationship", "Raise your concern privately and constructively, with clear evidence to support your view", "Say nothing unless someone else raises the issue first", "Raise your concern publicly in a team meeting to ensure it is heard"], correct: 1 },
  { id: 5,  text: "You are asked to estimate a project's completion time and you are genuinely uncertain. What do you say?", dimension: "Honesty", options: ["Give a confident specific estimate even without a reliable basis for it", "Provide a realistic range based on what you know and clearly flag the key uncertainties", "Say it cannot be estimated without more information and refuse to commit", "Give the deadline you believe your manager wants to hear"], correct: 1 },
  { id: 6,  text: "A client asks for your honest opinion of a competitor's product. You know it is actually quite good. What do you say?", dimension: "Honesty", options: ["Dismiss the competitor's product without any fair analysis", "Give an honest and balanced assessment — acknowledge where the competitor performs well and clarify where your solution adds more value for their specific needs", "Say company policy prevents you from commenting on competitors", "Share a misleading negative story about the competitor without evidence"], correct: 1 },
  { id: 7,  text: "You are completing your timesheet and notice you billed more hours to a client project than you actually worked. What do you do?", dimension: "Honesty", options: ["Leave it — the difference is minor and will average out over time", "Correct the timesheet to reflect the accurate hours worked", "Log the planned hours as originally intended and make up for it on the next project", "Ask a manager informally if it is acceptable to leave it as is"], correct: 1 },
  { id: 8,  text: "A colleague shares something personal with you in confidence. Someone else then asks if you know anything about it. What do you do?", dimension: "Honesty", options: ["Share the information — your colleague should have been more careful about who they told", "Keep the confidence: tell the other person you are not aware of anything you can share", "Share a version of the information that you believe is less sensitive", "Ask your colleague for permission before responding to the other person"], correct: 1 },
  // Accountability (8)
  { id: 9,  text: "A project you led failed to meet its goals. Your team asks what happened. What do you do?", dimension: "Accountability", options: ["Attribute the failure primarily to external factors and circumstances beyond your control", "Take honest ownership of what you were responsible for, acknowledge what did not work, and share what you have learned", "Identify which team member contributed most to the failure", "Say you will prepare a detailed report but delay it indefinitely"], correct: 1 },
  { id: 10, text: "You gave a colleague incorrect advice that directly caused them to make a significant error. What is the most appropriate response?", dimension: "Accountability", options: ["Allow the colleague to take responsibility — ultimately they made the final decision", "Acknowledge clearly that your advice was wrong and take active steps to help correct the situation", "Offer advice to fix the error without mentioning your role in causing it", "Review your own advice process quietly without telling the colleague what happened"], correct: 1 },
  { id: 11, text: "You committed to attending an important meeting but forgot and missed it entirely. What do you do?", dimension: "Accountability", options: ["Wait to see if anyone contacts you about it", "Apologise to the relevant people, find out what you missed, and take responsibility for any follow-up actions required", "Tell people you were dealing with an urgent client matter", "Apologise only if someone confronts you directly about your absence"], correct: 1 },
  { id: 12, text: "You discover a process you own has been producing errors for several weeks. How do you respond?", dimension: "Accountability", options: ["Fix the errors quietly without informing your manager or stakeholders", "Inform your manager, quantify the scope of the problem, fix the process, and implement a check to prevent recurrence", "Continue with the existing process and review the errors at the next scheduled monthly report", "Investigate who set up the original process and assign responsibility to them"], correct: 1 },
  { id: 13, text: "You are asked to take on a task that is significantly outside your area of expertise. What do you do?", dimension: "Accountability", options: ["Accept without telling anyone about your limitations and hope you can figure it out", "Decline — it is not your area and you should not take risks with your reputation", "Accept while being honest about your limitations, and proactively identify where you will need support or guidance", "Accept the task but outsource the unfamiliar parts without informing your manager"], correct: 2 },
  { id: 14, text: "Your manager praises a piece of work that was significantly assisted by a colleague. What do you do?", dimension: "Accountability", options: ["Accept the praise — you still made a real contribution", "Credit your colleague's contribution clearly and accurately to your manager", "Say nothing to your colleague but thank your manager privately", "Ask your manager to acknowledge both of you publicly next time"], correct: 1 },
  { id: 15, text: "You are falling behind on a commitment and it is becoming clear you will miss the deadline. What is the right response?", dimension: "Accountability", options: ["Continue working and try to catch up before anyone notices", "Inform the relevant stakeholder immediately, explain what happened, and agree a realistic revised plan", "Submit whatever you have completed by the deadline even if it is substantially incomplete", "Ask a colleague to submit something in your name"], correct: 1 },
  { id: 16, text: "A team decision you were part of has turned out to be the wrong call. You had reservations but did not raise them at the time. What is your responsibility?", dimension: "Accountability", options: ["None — you did not make the final decision", "You share some responsibility and should acknowledge that you could have raised your concerns at the time", "Full responsibility lies with whoever made the final decision", "You should now focus on identifying who should have flagged the issue before the decision was made"], correct: 1 },
  // Ethics (7)
  { id: 17, text: "You discover a colleague has been submitting inflated expense reports. What do you do?", dimension: "Ethics", options: ["Ignore it — it is not your responsibility and you do not want to cause conflict", "Cover for them — they are a friend and the amounts are not large", "Raise it through the appropriate internal channel such as your manager or HR", "Confront them publicly in front of the team to discourage similar behaviour"], correct: 2 },
  { id: 18, text: "Your manager pressures you to misrepresent data in a client report to make results look better than they are. What do you do?", dimension: "Ethics", options: ["Follow your manager's instructions — they have authority and accountability for the report", "Raise your concern directly with your manager and explain why you cannot misrepresent the data", "Alter the data but add a subtle caveat in the appendix", "Do it this time and raise the issue through another channel afterwards"], correct: 1 },
  { id: 19, text: "A client offers you a personal gift valued at ten times your company's accepted gift limit. What do you do?", dimension: "Ethics", options: ["Accept it — it reflects a strong and valued client relationship", "Accept it but not disclose it to anyone in your company", "Politely decline, reference your company's gifts policy, and thank them genuinely for the gesture", "Accept it and donate it to charity so you are not personally benefiting"], correct: 2 },
  { id: 20, text: "You are offered access to a competitor's confidential pricing document by someone claiming it was shared with them unofficially. What do you do?", dimension: "Ethics", options: ["Use it — it provides a legitimate competitive advantage for your company", "Decline to use it and report the situation to your manager", "Use it confidentially within your immediate team only", "Ask your manager whether it is permissible to use it before making a decision"], correct: 1 },
  { id: 21, text: "You are asked to write a professional reference for a colleague who you know has performed poorly. What do you do?", dimension: "Ethics", options: ["Write a strong positive reference — loyalty and collegiality come first", "Either decline to write the reference or write one that honestly and fairly reflects your professional experience of them", "Write a deliberately vague reference that neither confirms nor denies their performance", "Write exactly what they have asked you to include"], correct: 1 },
  { id: 22, text: "You notice that data from a minority segment is being excluded from an analysis in a way that materially changes the conclusions. What do you do?", dimension: "Ethics", options: ["Assume it was an accidental oversight and say nothing", "Raise the issue directly with the person responsible for the analysis", "Include the data yourself in a separate document without telling anyone", "Add a brief note about it in the appendix, away from the main findings"], correct: 1 },
  { id: 23, text: "You are under time pressure and realise that cutting a corner on a safety or compliance check would save several hours. What do you do?", dimension: "Ethics", options: ["Cut the corner — a single instance is unlikely to cause any real harm", "Complete the check fully regardless of the time pressure", "Skip it this time but flag it in your notes as something to revisit later", "Ask a junior colleague to complete the check to save your time"], correct: 1 },
  // Trustworthiness (7)
  { id: 24, text: "You agree to complete a task by Thursday, but by Wednesday you know it will not be ready until Friday. What do you do?", dimension: "Trustworthiness", options: ["Work through the night and hope you deliver by Thursday without telling anyone", "Inform the relevant party on Wednesday, explain the reason for the delay, and agree a new deadline", "Submit incomplete work on Thursday to technically meet the deadline", "Ask a colleague to cover for you without informing the stakeholder"], correct: 1 },
  { id: 25, text: "A colleague shares a confidential draft with you and asks you not to distribute it. You accidentally forward it to the wrong person. What do you do?", dimension: "Trustworthiness", options: ["Pretend it did not happen and hope the other person does not mention it", "Immediately inform your colleague and the unintended recipient and take steps to minimise the impact", "Ask the unintended recipient to delete it and say nothing to your colleague", "Wait to see if either party raises it before taking any action"], correct: 1 },
  { id: 26, text: "You agreed to mentor a new team member, but your workload has become overwhelming. What is the most trustworthy action?", dimension: "Trustworthiness", options: ["Continue as planned but skip sessions whenever other priorities arise", "Be honest about your availability, renegotiate the commitment to something realistic, or find a suitable alternative mentor", "Send resources and reading material by email as a substitute for meeting", "Stop the mentoring arrangement without any explanation"], correct: 1 },
  { id: 27, text: "You receive unconfirmed information that a project is likely to be cancelled. A colleague who has been working hard on it asks you directly if you have heard anything. What do you do?", dimension: "Trustworthiness", options: ["Share everything you heard in full, even though it is unconfirmed", "Lie and say you have heard nothing to protect them from unnecessary anxiety", "Tell them honestly that you have heard something, but that it is unconfirmed, and suggest they speak directly to the relevant person", "Change the subject and avoid answering the question"], correct: 2 },
  { id: 28, text: "A team depends on your weekly analysis to make key decisions. You know the methodology has a flaw but fixing it would take considerable time. What do you do?", dimension: "Trustworthiness", options: ["Continue using the flawed methodology — the analysis is good enough for practical purposes", "Flag the flaw immediately, note the potential impact on previous outputs, and fix it as quickly as possible", "Fix it quietly without informing anyone that the methodology was flawed", "Plan to address it in the next version without flagging the current issue"], correct: 1 },
  { id: 29, text: "You are asked to commit to a delivery deadline that you are genuinely unsure you can meet. What is the most trustworthy response?", dimension: "Trustworthiness", options: ["Commit to the requested deadline to demonstrate willingness and positive intent", "Provide an honest assessment of what you can realistically deliver and by when, with any risks or caveats stated clearly", "Commit to the deadline and escalate if you miss it", "Say you will 'do your best' without committing to anything specific"], correct: 1 },
  { id: 30, text: "You realise you have been unintentionally taking credit for an idea that originated with a colleague during a discussion. What do you do?", dimension: "Trustworthiness", options: ["Continue as the situation has already developed and attribution is now unclear", "Proactively clarify to relevant stakeholders that the idea originated with your colleague", "Tell your colleague privately but not correct the record publicly", "Offer your colleague a larger role in the project as indirect compensation"], correct: 1 },
];

export const IE_DURATION_SECONDS = 20 * 60;

export const IE_DIMENSIONS: Array<{ label: IEDimension; description: string; className: string }> = [
  { label: "Honesty",          description: "Truthfulness and transparency in all professional situations.", className: "bg-blue-500/10 text-blue-300" },
  { label: "Accountability",   description: "Taking ownership of actions, decisions, and their consequences.", className: "bg-emerald-500/10 text-emerald-300" },
  { label: "Ethics",           description: "Doing the right thing even under pressure or when unobserved.", className: "bg-violet-500/10 text-violet-300" },
  { label: "Trustworthiness",  description: "Being reliable, keeping confidences, and honouring commitments.", className: "bg-amber-500/10 text-amber-300" },
];

export function scoreIE(answers: (number | null)[]) {
  const dimStats: Record<IEDimension, { correct: number; total: number }> = {
    Honesty: { correct: 0, total: 0 },
    Accountability: { correct: 0, total: 0 },
    Ethics: { correct: 0, total: 0 },
    Trustworthiness: { correct: 0, total: 0 },
  };
  let totalCorrect = 0;
  IE_QUESTIONS.forEach((q, i) => {
    dimStats[q.dimension].total++;
    if (answers[i] !== null && answers[i] === q.correct) {
      totalCorrect++;
      dimStats[q.dimension].correct++;
    }
  });
  const percentage = Math.round((totalCorrect / IE_QUESTIONS.length) * 100);
  const dimensions = Object.fromEntries(
    (Object.keys(dimStats) as IEDimension[]).map((d) => {
      const { correct, total } = dimStats[d];
      return [d, total > 0 ? Math.round((correct / total) * 100) : 0];
    })
  ) as Record<IEDimension, number>;
  return { correct: totalCorrect, total: IE_QUESTIONS.length, percentage, dimensions };
}
