export type LADimension = "Mental Flexibility" | "Speed of Learning" | "Feedback Receptivity" | "Experimentation";

export interface LAQuestion {
  id: number;
  text: string;
  dimension: LADimension;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const LA_QUESTIONS: LAQuestion[] = [
  // Mental Flexibility (8)
  { id: 1,  text: "You have used the same approach to a task for two years. A new colleague suggests a different method. What do you do?", dimension: "Mental Flexibility", options: ["Dismiss the suggestion — your method is proven and has always worked", "Evaluate the suggested approach on its merits and run a small trial if it shows genuine promise", "Adopt the new method only if your manager instructs you to", "Ignore the suggestion — experience and familiarity outweigh novelty"], correct: 1 },
  { id: 2,  text: "You are halfway through a project when the overall strategy changes significantly. How do you respond?", dimension: "Mental Flexibility", options: ["Continue with the original plan to avoid wasting the work already completed", "Feel frustrated by the disruption and disengage from the project", "Reframe what has been completed as useful learning, assess what is still applicable, and adapt your approach to the new direction", "Request to be removed from the project if the scope has changed too much"], correct: 2 },
  { id: 3,  text: "You discover that a key assumption you have been working from for weeks is incorrect. What is the most agile response?", dimension: "Mental Flexibility", options: ["Continue as planned if the assumption's impact seems manageable", "Acknowledge the error, assess its impact on your current work, and adjust your plan accordingly", "Continue and disclose the incorrect assumption transparently at the end of the project", "Restart the entire project from scratch now that a core assumption has changed"], correct: 1 },
  { id: 4,  text: "Two colleagues hold different but equally well-reasoned views on how to solve a complex problem. What is the most intellectually agile response?", dimension: "Mental Flexibility", options: ["Side with the more senior of the two colleagues", "Side with whoever made their argument first", "Engage seriously with both views, examine your own assumptions, and form or update your position based on the strength of the arguments", "Stay neutral and avoid committing to any position"], correct: 2 },
  { id: 5,  text: "A problem you encounter resists your usual solution approach. What do you do?", dimension: "Mental Flexibility", options: ["Apply more effort and intensity to your standard approach", "Step back, question whether your usual method is suited to this variation of the problem, and try a fundamentally different angle", "Escalate — this type of problem is beyond your current capability", "Wait for a colleague to suggest an alternative before trying anything different"], correct: 1 },
  { id: 6,  text: "What best distinguishes a mentally flexible person from one who is simply indecisive?", dimension: "Mental Flexibility", options: ["A mentally flexible person never commits firmly to any position", "A mentally flexible person changes their position in response to any argument, regardless of its strength", "A mentally flexible person forms considered views and updates them based on new evidence, rather than changing arbitrarily or refusing to change at all", "There is no meaningful distinction between the two"], correct: 2 },
  { id: 7,  text: "You attend a training session on a new methodology that challenges the way you currently work. What is the most agile response?", dimension: "Mental Flexibility", options: ["Dismiss it — your current methods are tested and reliable", "Engage with it critically, identify which elements could improve your current approach, and design a small test to evaluate them", "Implement the entire methodology immediately and abandon your previous approach", "Wait to see whether your colleagues adopt it before deciding whether it is worth considering"], correct: 1 },
  { id: 8,  text: "You are assigned to collaborate with a team that operates very differently from how you are used to working. How do you approach this?", dimension: "Mental Flexibility", options: ["Advocate strongly for the team to adapt to your way of working", "Observe how the team operates, identify what is effective, and adapt your own style to collaborate productively", "Stick to your normal approach and modify only if directly asked", "Raise your concerns about the working style differences with your manager before fully engaging with the team"], correct: 1 },
  // Speed of Learning (8)
  { id: 9,  text: "You join a new role and are unfamiliar with most of the tools the team uses. What is the most effective approach to getting up to speed?", dimension: "Speed of Learning", options: ["Observe what others do and closely imitate their approach", "Create a deliberate learning plan: identify the most critical tools, find the best available resources, practise actively, and seek feedback on your progress", "Wait until you receive formal structured training on each tool before using them", "Ask colleagues to handle the technical elements for you until you feel fully confident"], correct: 1 },
  { id: 10, text: "You need to develop a new skill quickly for an upcoming project. What is the most effective approach?", dimension: "Speed of Learning", options: ["Read and study everything available on the topic before attempting any practical application", "Identify the 20% of the skill that delivers 80% of the practical capability, practise it intensively, and expand from there", "Ask someone with the existing skill to do that part of the project for you this time", "Learn as you go without any deliberate structure or plan"], correct: 1 },
  { id: 11, text: "After completing a significant project, what is the most effective learning habit?", dimension: "Speed of Learning", options: ["Move on quickly to the next project — momentum matters more than reflection", "Conduct a short personal review: what worked well, what did not, and what you would specifically do differently next time", "Wait for your manager's formal performance review to identify what to improve", "Review only the elements that clearly went wrong and ignore everything that worked"], correct: 1 },
  { id: 12, text: "You make a mistake in an unfamiliar area. What is the most agile and productive response?", dimension: "Speed of Learning", options: ["Avoid working in that area in future — it is outside your core competence", "Extract the specific lesson from the mistake and deliberately apply it the next time a similar situation arises", "Ask someone else to take over that area of work entirely", "Document the mistake carefully but make no immediate changes to your approach"], correct: 1 },
  { id: 13, text: "You are the most junior person in a team of domain experts. How do you learn most effectively from them?", dimension: "Speed of Learning", options: ["Ask broad general questions during team meetings when everyone is present", "Listen carefully, prepare specific focused questions before interactions, and look for opportunities to shadow or co-work with the experts on real tasks", "Wait until you have developed more expertise before engaging deeply with them", "Focus primarily on formal training materials and limit interaction with the team until you feel prepared"], correct: 1 },
  { id: 14, text: "Which behaviour is the strongest predictor of fast and effective learning in a professional context?", dimension: "Speed of Learning", options: ["High academic qualifications from a prestigious institution", "Many years of experience in a single specialist area", "Actively seeking feedback, reflecting deliberately on what they observe and experience, and practising new skills outside the comfort zone", "Access to the best available training programmes and learning platforms"], correct: 2 },
  { id: 15, text: "You are given a stretch assignment that is significantly beyond your current skill level. What do you do?", dimension: "Speed of Learning", options: ["Decline the assignment — the risk of failure outweighs the potential development benefit", "Accept, break it into learning stages, identify where you need support, and deliver while building capability throughout", "Accept without revealing your current level of preparation or uncertainty", "Deliver it purely using your existing skills and avoid developing any new capability for this project"], correct: 1 },
  { id: 16, text: "You try a new piece of software for the first time and find yourself struggling with a specific feature. What is the most effective immediate response?", dimension: "Speed of Learning", options: ["Give up on the software and look for a familiar alternative", "Find a specific tutorial, help article, or colleague who can address the specific part you are struggling with", "Randomly try different options until something eventually works", "Ask a colleague to complete that part of the task on your behalf"], correct: 1 },
  // Feedback Receptivity (7)
  { id: 17, text: "Your manager gives you critical feedback on a piece of work you are genuinely proud of. What is the most effective response?", dimension: "Feedback Receptivity", options: ["Defend your approach clearly and explain the reasoning behind your choices", "Listen carefully, thank them for the feedback, and reflect on which points have genuine merit before deciding how to act on them", "Accept all feedback without questioning or evaluating any of it", "Feel discouraged and become reluctant to show your work for review in the future"], correct: 1 },
  { id: 18, text: "A peer gives you unsolicited feedback that you initially believe is wrong. What do you do?", dimension: "Feedback Receptivity", options: ["Dismiss it entirely — they are not your manager and their view is not authoritative", "Thank them for sharing it, reflect independently on whether there is any validity to the point, and respond based on its actual merits", "Agree in the moment to maintain the relationship, then ignore it later", "Tell them directly that their feedback is unhelpful"], correct: 1 },
  { id: 19, text: "You consistently receive the same piece of feedback from multiple different sources over time. What does this most reliably suggest?", dimension: "Feedback Receptivity", options: ["The feedback is likely wrong — multiple people can share the same bias or blind spot", "There is almost certainly something meaningful in the feedback that warrants genuine attention and action", "The people giving feedback have a coordinated personal agenda", "You should change roles or context to avoid the pattern continuing"], correct: 1 },
  { id: 20, text: "You receive important feedback at a moment when you are already stressed and distracted. What is the most mature response?", dimension: "Feedback Receptivity", options: ["Tell the person you do not have time for feedback right now and ask them to come back later", "Accept the feedback without truly engaging with its content", "Acknowledge the feedback, explain that you want to give it proper attention, and agree a specific time to discuss it when you can engage thoughtfully", "Dismiss the feedback as coming at a poorly chosen time"], correct: 2 },
  { id: 21, text: "After receiving feedback, you notice you are making exactly the same mistake again. What is the most self-aware response?", dimension: "Feedback Receptivity", options: ["Accept that feedback does not always change behaviour — move on", "Recognise that you have not yet changed the underlying behaviour and identify one specific, concrete action that will make the change stick", "Ask for the same feedback to be repeated to reinforce the message", "Reassure yourself that you are still developing and improvement takes time"], correct: 1 },
  { id: 22, text: "Which behaviour best demonstrates a high level of feedback receptivity?", dimension: "Feedback Receptivity", options: ["Immediately changing your behaviour in response to any feedback received, regardless of its source or quality", "Defending your approach firmly whenever you disagree with feedback given", "Proactively seeking feedback before it is offered and treating it as useful data rather than as personal criticism", "Thanking people sincerely for feedback but rarely acting on it"], correct: 2 },
  { id: 23, text: "A senior leader gives you feedback that directly contradicts feedback given by a peer. What do you do?", dimension: "Feedback Receptivity", options: ["Default to the senior leader's feedback — their seniority makes their view more authoritative", "Dismiss both and rely entirely on your own judgment", "Reflect on both perspectives, consider the context in which each was given, and decide what is genuinely most useful to act on", "Ask a third person to adjudicate which piece of feedback is correct"], correct: 2 },
  // Experimentation (7)
  { id: 24, text: "You want to improve a process you own but are unsure of the best approach. What is the most agile method?", dimension: "Experimentation", options: ["Redesign the entire process from scratch based on your best current thinking", "Research best practice thoroughly and present a comprehensive new proposal to leadership before making any changes", "Form a specific hypothesis about what would improve the process, test a small targeted change, measure the result, and iterate", "Bring in an external consultant to redesign the process on your behalf"], correct: 2 },
  { id: 25, text: "You try a new approach and it does not work. How do you most productively evaluate this outcome?", dimension: "Experimentation", options: ["The experiment failed — you should stop experimenting in this area", "The approach was clearly wrong — return to the previous method immediately", "Extract the specific insight about why it did not work and use that learning to refine and improve your next attempt", "Accept that some things simply cannot be improved and move on"], correct: 2 },
  { id: 26, text: "You have an idea to test a new approach to something, but there is a genuine chance it will not work. What is the most agile stance?", dimension: "Experimentation", options: ["Wait until you are reasonably certain it will succeed before investing time in testing it", "Avoid it entirely — the reputational risk of a visible failed experiment is not worth it", "Test it on a small, contained scale with a clearly defined success metric, and commit to learning from whatever the outcome is", "Implement it at full scale immediately so the results are meaningful and conclusive"], correct: 2 },
  { id: 27, text: "What is the most important characteristic of a productive work experiment?", dimension: "Experimentation", options: ["It results in a successful outcome", "It receives prior approval from senior leadership before it begins", "It is structured with a clear hypothesis, a defined and bounded test, and a method for measuring the outcome", "It is conducted privately to avoid distracting the rest of the team from their work"], correct: 2 },
  { id: 28, text: "Your team is resistant to trialling a new approach you believe would be effective. What is the most constructive response?", dimension: "Experimentation", options: ["Implement it unilaterally without team consensus", "Accept the resistance and drop the idea — team buy-in is a prerequisite", "Propose a small, low-commitment pilot that allows the team to evaluate the approach with minimal risk before making a broader decision", "Escalate to management to get top-down support before attempting to engage the team"], correct: 2 },
  { id: 29, text: "A colleague proposes a work experiment that you believe is unlikely to produce useful results. What is the most learning-focused response?", dimension: "Experimentation", options: ["Tell them not to bother — the time would be better spent elsewhere", "Engage with the idea: ask what hypothesis it tests and what they expect to learn, then support a well-scoped version if it has genuine learning value", "Let them run it but make clear you are not connected to the outcome", "Agree to support it only if the manager explicitly approves it first"], correct: 1 },
  { id: 30, text: "An organisation decides to terminate a running experiment early due to negative interim results. What is the most agile response?", dimension: "Experimentation", options: ["Resist the decision — insufficient data has been gathered to draw valid conclusions", "Feel discouraged about proposing experiments in the future", "Accept the decision, systematically extract whatever learning is available from the partial results, and apply those insights to the next initiative", "Identify and highlight who was responsible for the poor experimental design"], correct: 2 },
];

export const LA_DURATION_SECONDS = 20 * 60;

export const LA_DIMENSIONS: Array<{ label: LADimension; description: string; className: string }> = [
  { label: "Mental Flexibility",    description: "Adapting thinking and approaches in response to new information.", className: "bg-blue-500/10 text-blue-300" },
  { label: "Speed of Learning",     description: "Acquiring and applying new skills and knowledge quickly.", className: "bg-emerald-500/10 text-emerald-300" },
  { label: "Feedback Receptivity",  description: "Seeking, processing, and acting on feedback constructively.", className: "bg-amber-500/10 text-amber-300" },
  { label: "Experimentation",       description: "Testing new ideas deliberately and learning from results.", className: "bg-violet-500/10 text-violet-300" },
];

export function scoreLA(answers: (number | null)[]) {
  const dimStats: Record<LADimension, { correct: number; total: number }> = {
    "Mental Flexibility": { correct: 0, total: 0 },
    "Speed of Learning": { correct: 0, total: 0 },
    "Feedback Receptivity": { correct: 0, total: 0 },
    Experimentation: { correct: 0, total: 0 },
  };
  let totalCorrect = 0;
  LA_QUESTIONS.forEach((q, i) => {
    dimStats[q.dimension].total++;
    if (answers[i] !== null && answers[i] === q.correct) {
      totalCorrect++;
      dimStats[q.dimension].correct++;
    }
  });
  const percentage = Math.round((totalCorrect / LA_QUESTIONS.length) * 100);
  const dimensions = Object.fromEntries(
    (Object.keys(dimStats) as LADimension[]).map((d) => {
      const { correct, total } = dimStats[d];
      return [d, total > 0 ? Math.round((correct / total) * 100) : 0];
    })
  ) as Record<LADimension, number>;
  return { correct: totalCorrect, total: LA_QUESTIONS.length, percentage, dimensions };
}
