export interface PSQuestion {
  id: number;
  text: string;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const PS_QUESTIONS: PSQuestion[] = [
  { id: 1,  text: "Your project is behind schedule because a key supplier has not delivered materials. What is your first action?", options: ["Report the delay to leadership without further information", "Contact the supplier to understand the delay and get an updated timeline", "Begin work with inferior alternatives and hope the originals arrive", "Pause all project activities until the materials arrive"], correct: 1 },
  { id: 2,  text: "Task A takes 4 hours and is due today. Task B takes 1 hour and is due tomorrow. Task C takes 6 hours and is due in 3 days. You have 8 hours today. What do you do first?", options: ["Task A first, then as much of Task C as possible", "Task B first since it is smallest, then Task A", "Task C since it is the most complex", "Request deadline extensions for all three tasks"], correct: 0 },
  { id: 3,  text: "During a meeting, you notice the agreed approach contains a significant flaw. What do you do?", options: ["Stay quiet to avoid causing conflict", "Raise the issue after the meeting", "Raise the concern politely during the meeting and propose an alternative", "Implement the decision and flag the flaw only if it causes a problem"], correct: 2 },
  { id: 4,  text: "A client has emailed your manager to complain about a deliverable. What is your best next step?", options: ["Wait for your manager to respond and copy you in", "Reply explaining the situation is not your fault", "Contact the client proactively to understand their concern and discuss a resolution", "Prepare a document explaining why the deliverable met requirements"], correct: 2 },
  { id: 5,  text: "Halfway through a project, requirements change significantly. What do you do?", options: ["Complete the original plan, then start again with the new requirements", "Assess the impact on timeline and budget, communicate it, and agree a revised plan", "Ignore the new requirements until the original deliverable is approved", "Escalate to leadership and ask them to reject the requirement change"], correct: 1 },
  { id: 6,  text: "Two colleagues are in conflict and it is affecting team productivity. As a peer, what is most appropriate?", options: ["Take sides with the colleague you believe is correct", "Ignore the conflict — it is not your responsibility", "Speak with each colleague privately and suggest they resolve it together", "Report both colleagues to HR immediately"], correct: 2 },
  { id: 7,  text: "You receive a task with unclear instructions. Deadlines are tight. What do you do first?", options: ["Start working based on your best guess to save time", "Clarify the key ambiguities with the assigner before proceeding", "Delegate the task to a colleague who may understand it better", "Submit the task incomplete and request clarification afterwards"], correct: 1 },
  { id: 8,  text: "After launching a new process, you receive feedback it is causing problems for a downstream team. Your best response?", options: ["Defend the process — it was designed with good intentions", "Thank the team, investigate the problem, and look for a fix", "Advise the downstream team to adapt their own process", "Roll back the process immediately without investigating the root cause"], correct: 1 },
  { id: 9,  text: "You are given a complex problem with no obvious solution. What is the most effective first step?", options: ["Implement the first solution that comes to mind", "Break the problem into smaller parts and analyse each component", "Seek external help immediately", "Defer the problem until more information is available"], correct: 1 },
  { id: 10, text: "A colleague has made a significant error in a report already shared with leadership. What do you do?", options: ["Tell the colleague privately and let them decide whether to flag it", "Correct the error yourself and resubmit without mentioning it", "Alert the colleague immediately and together notify leadership with a correction", "Do nothing — you are not responsible for the error"], correct: 2 },
  { id: 11, text: "Your manager asks for input on a decision you disagree with. What is the best approach?", options: ["Support the decision publicly even if you disagree", "Share your concerns clearly and professionally, then respect the final decision", "Refuse to take part in the decision-making process", "Build support from colleagues before raising the issue"], correct: 1 },
  { id: 12, text: "A task is taking much longer than estimated. What should you do?", options: ["Work extra hours without telling anyone until you catch up", "Inform your manager early and revise the timeline or scope", "Submit whatever is done at the deadline regardless of completeness", "Wait to see if pace improves before escalating"], correct: 1 },
  { id: 13, text: "You must make a decision but are missing important data. What is the best approach?", options: ["Make a confident decision to avoid appearing uncertain", "Delay the decision indefinitely until all data is available", "Gather the most critical data available, decide, and revisit if needed", "Ask someone else to make the decision"], correct: 2 },
  { id: 14, text: "A colleague keeps sending you work outside your agreed responsibilities. What do you do?", options: ["Complete the work to maintain a good relationship", "Ignore the work until your colleague stops sending it", "Discuss the issue directly with your colleague and clarify boundaries", "Copy your manager on every email without addressing it with your colleague"], correct: 2 },
  { id: 15, text: "You cannot meet a critical deadline due to a cause outside your control. What is most effective?", options: ["Work through the night to avoid missing the deadline", "Inform relevant stakeholders early, explain the cause, and propose a revised timeline", "Wait until the deadline passes before explaining the situation", "Ask a colleague to take over without informing stakeholders"], correct: 1 },
  { id: 16, text: "A customer complains about the same issue for the third time. What does this most likely indicate?", options: ["The customer is being unreasonable", "The root cause of the issue has not been addressed", "The customer needs more patience", "The issue is outside your control"], correct: 1 },
  { id: 17, text: "Two managers both consider their work urgent and ask for your priority. What is the best action?", options: ["Work on both simultaneously to show willingness", "Do the work for the manager you prefer", "Escalate to a senior manager without speaking to either first", "Speak with both managers together to agree on a clear priority"], correct: 3 },
  { id: 18, text: "You identify three problems. Solving Problem A also eliminates Problem B. What should you do?", options: ["Solve all three simultaneously", "Solve Problem A first — it has the broadest impact", "Solve the easiest problem first regardless of impact", "Solve Problem B first to reduce the workload"], correct: 1 },
  { id: 19, text: "A new team member consistently makes the same type of mistake. What is your best response?", options: ["Document the mistakes and immediately report to a manager", "Correct each mistake as it occurs without addressing the pattern", "Give constructive feedback, explain the correct approach, and offer support", "Reassign their tasks to someone else without discussion"], correct: 2 },
  { id: 20, text: "You need to find cost savings without reducing quality. What is your first step?", options: ["Immediately cut the most expensive line items", "Map existing expenditure, identify waste or inefficiency, then propose cuts", "Propose a 10% reduction across all areas equally", "Advise that cost savings are impossible without quality impact"], correct: 1 },
  { id: 21, text: "You must present a solution but only have partial information. What do you do?", options: ["Present what you know, state your assumptions, and identify what needs further investigation", "Wait until you have complete information before presenting anything", "Present as if you have complete information to appear confident", "Ask someone else to present on your behalf"], correct: 0 },
  { id: 22, text: "A process produces a 5% error rate. What is the most systematic way to reduce it?", options: ["Increase the number of people checking each output", "Identify where errors occur most frequently and investigate root causes", "Tell the team to be more careful going forward", "Accept the error rate as reasonable and move on"], correct: 1 },
  { id: 23, text: "You have limited budget to fix a problem. Option A is cheapest but risky. Option B is moderate cost and risk. Option C eliminates all risk but is expensive. Which do you recommend?", options: ["Option A — cost is the primary concern", "Option B — it balances cost and risk appropriately", "Option C — eliminating risk is always the priority", "None — request more budget before deciding"], correct: 1 },
  { id: 24, text: "Your team's performance metrics are declining. You are asked to identify causes. What is your approach?", options: ["Assume the team is not working hard enough and increase monitoring", "Collect data on when the decline started and what changed at that time", "Make immediate process changes to show you are taking action", "Ask the team to identify causes without reviewing data yourself"], correct: 1 },
  { id: 25, text: "A stakeholder frequently changes requirements late in the development cycle. How do you address this?", options: ["Agree to every change to maintain the relationship", "Establish a formal change control process and communicate its implications", "Ignore late changes and deliver against the original brief", "Escalate every change to senior leadership without discussing with the stakeholder"], correct: 1 },
  { id: 26, text: "You are given a task with a vague objective. What is most effective?", options: ["Start immediately with your best interpretation", "Spend significant time researching before making any progress", "Clarify the expected outcome and key success criteria before starting", "Return the task as incomplete due to insufficient clarity"], correct: 2 },
  { id: 27, text: "A risk you flagged three weeks ago has now materialised. What is your first action?", options: ["Implement the mitigation plan if one was already prepared", "Prepare a detailed report on why the risk was inevitable", "Identify who failed to prevent the risk", "Wait for the full impact to be clear before acting"], correct: 0 },
  { id: 28, text: "Vendor A is cheaper but has mixed reviews. Vendor B is slightly more expensive but consistently well-reviewed. What is the most rational approach?", options: ["Always choose the cheapest option", "Always choose the best-reviewed option", "Evaluate total cost of ownership including potential risk from mixed reviews", "Ask a colleague to make the decision"], correct: 2 },
  { id: 29, text: "A team member claims they were unaware of a critical deadline. What should be investigated first?", options: ["Whether the team member is telling the truth", "Whether the deadline was clearly communicated and documented", "Whether the team member should be disciplined", "Whether the deadline needs to be moved"], correct: 1 },
  { id: 30, text: "Your solution worked in testing but fails in the live environment. What is the most important next step?", options: ["Revert to the previous solution if possible and investigate the root cause", "Continue with the new solution and monitor for further failures", "Blame the testing team for not catching the issue", "Inform stakeholders the problem cannot be solved"], correct: 0 },
];

export const PS_DURATION_SECONDS = 25 * 60;

export function scorePS(answers: (number | null)[]) {
  let correct = 0;
  answers.forEach((answer, i) => {
    if (answer !== null && i < PS_QUESTIONS.length && answer === PS_QUESTIONS[i].correct) correct++;
  });
  const percentage = Math.round((correct / PS_QUESTIONS.length) * 100);
  let interpretation = "";
  let color = "";
  if (percentage >= 90)      { interpretation = "Exceptional Problem Solving"; color = "text-emerald-400"; }
  else if (percentage >= 75) { interpretation = "Strong Problem Solving"; color = "text-green-400"; }
  else if (percentage >= 60) { interpretation = "Good Problem Solving"; color = "text-teal-400"; }
  else if (percentage >= 45) { interpretation = "Developing Problem Solving"; color = "text-amber-400"; }
  else                       { interpretation = "Needs Development"; color = "text-red-400"; }
  return { correct, total: PS_QUESTIONS.length, percentage, interpretation, color };
}
