export type SADimension = "Prospecting" | "Persuasion" | "Objection Handling" | "Closing";

export interface SAQuestion {
  id: number;
  text: string;
  dimension: SADimension;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const SA_QUESTIONS: SAQuestion[] = [
  // Prospecting (9)
  { id: 1,  text: "When entering a new sales territory, what should be your first step?", dimension: "Prospecting", options: ["Send mass cold emails immediately to as many companies as possible", "Research the market, define your ideal customer profile, and build a targeted prospect list", "Call every company in the area in alphabetical order", "Wait for inbound leads from marketing"], correct: 1 },
  { id: 2,  text: "Which factor is MOST important when qualifying a new prospect?", dimension: "Prospecting", options: ["How large the company appears on LinkedIn", "How quickly they respond to your first outreach", "Whether they fit your ICP and have the budget and authority to make a purchasing decision", "Whether they have heard of your company before"], correct: 2 },
  { id: 3,  text: "What approach most reliably improves cold email open rates?", dimension: "Prospecting", options: ["Personalising the subject line to reference the prospect's company or role specifically", "Using your company's awards and accolades in the subject line", "Writing 'Partnership Opportunity' in the subject line", "Following up daily until they open"], correct: 0 },
  { id: 4,  text: "You have identified a target company but cannot find the right decision-maker's contact details. What is the best approach?", dimension: "Prospecting", options: ["Email the generic company inbox and hope it reaches the right person", "Use LinkedIn to identify the correct contact, research their role, and send a personalised message", "Call reception and ask for 'the person in charge of buying software'", "Move to the next prospect — it is too difficult"], correct: 1 },
  { id: 5,  text: "How many touchpoints should you typically make before disqualifying a cold prospect who has not responded?", dimension: "Prospecting", options: ["1–2 attempts across one channel", "3–4 attempts across one channel", "5–8 attempts spread across multiple channels over several weeks", "10 or more — never give up on a prospect"], correct: 2 },
  { id: 6,  text: "Before a first cold call, which information is most critical to have prepared?", dimension: "Prospecting", options: ["The prospect's full career history from LinkedIn", "The company's key challenges, your contact's likely priorities, and how your solution could specifically help them", "The company's current stock price and financial performance", "The number of employees and office locations"], correct: 1 },
  { id: 7,  text: "Which LinkedIn outreach message approach is most effective for getting a response?", dimension: "Prospecting", options: ["'I'd like to add you to my professional network.'", "'Hi [Name], I help [their role] at companies like yours achieve [specific outcome]. Worth a 15-minute call to explore if that's relevant to you?'", "A long message listing your company's full product range and pricing", "'Can I have 5 minutes of your time this week?'"], correct: 1 },
  { id: 8,  text: "Your pipeline is very thin. What is the most effective immediate action?", dimension: "Prospecting", options: ["Discount your offering to accelerate existing deals", "Focus only on existing customers for upsell opportunities", "Systematically reach out to lapsed prospects, referral sources, and new ICP targets across multiple channels", "Wait for the marketing team to generate new inbound leads"], correct: 2 },
  { id: 9,  text: "You have two hours for prospecting. How should you prioritise?", dimension: "Prospecting", options: ["Spend the full two hours on cold calls only", "Split your time between personalised outreach to warm leads and targeted research on high-priority new prospects", "Write one highly detailed email to a single prospect", "Post content on LinkedIn and monitor engagement"], correct: 1 },
  // Persuasion (9)
  { id: 10, text: "A prospect says 'Tell me about your product.' What is the best response?", dimension: "Persuasion", options: ["Deliver your full product demo from start to finish immediately", "Ask two or three discovery questions about their current situation first, then tailor your explanation to their specific needs", "Send them a product brochure and follow up in a week", "List all product features from most expensive to least expensive"], correct: 1 },
  { id: 11, text: "Which sales approach is most effective in a B2B context?", dimension: "Persuasion", options: ["Leading with your product's technical specifications and feature list", "Competing primarily on price as your main differentiator", "Understanding the prospect's pain points and showing precisely how your solution addresses them", "Creating artificial scarcity and urgency to accelerate the decision"], correct: 2 },
  { id: 12, text: "During a demo, a buyer mentions a well-known competitor by name. What is the best response?", dimension: "Persuasion", options: ["Immediately list everything that is wrong with the competitor's product", "Acknowledge the competitor and pivot to what makes your solution uniquely better for this buyer's specific situation", "Ignore the mention and continue presenting your slides", "Tell the buyer your company is the market leader without offering specific evidence"], correct: 1 },
  { id: 13, text: "After a discovery call, what should your proposal lead with?", dimension: "Persuasion", options: ["Your company's history, values, and industry awards", "A full breakdown of all available pricing tiers", "A concise summary of the prospect's stated goals and challenges, followed by how your solution addresses each one", "Detailed technical product specifications"], correct: 2 },
  { id: 14, text: "Which approach best creates genuine urgency without applying unethical pressure?", dimension: "Persuasion", options: ["'This price is only valid today — my manager will pull it tomorrow.'", "'We only have limited availability — you need to decide now.'", "'Based on your goals, starting this quarter means you would see results before [specific business deadline the prospect mentioned].'", "'One of your competitors is already in final discussions with us.'"], correct: 2 },
  { id: 15, text: "A prospect is interested but not yet convinced. What is the best next step?", dimension: "Persuasion", options: ["Push hard for an immediate close — hesitation means they need more pressure", "Offer to connect them with a reference customer in a similar role or industry, and schedule a follow-up call to answer remaining questions", "Reduce the price to remove the financial barrier", "Give them space and wait for them to come back to you"], correct: 1 },
  { id: 16, text: "What is the most effective way to use customer case studies in a sales process?", dimension: "Persuasion", options: ["Attach a generic case study PDF to every outreach email", "Select a case study from a company closely matching the prospect's profile and highlight specific, measurable results relevant to their goals", "Only share case studies when the prospect explicitly asks for proof", "Always reference your most impressive logo client regardless of industry or size relevance"], correct: 1 },
  { id: 17, text: "You are presenting to a buying group with five people who have different roles and priorities. What is the best approach?", dimension: "Persuasion", options: ["Deliver your standard pitch and let them ask questions at the end", "Open by asking each stakeholder what a successful outcome looks like for them, then address each perspective during your presentation", "Focus your full attention on the most senior person and direct all comments to them", "Present only the technical specification — all stakeholders ultimately care about the details"], correct: 1 },
  { id: 18, text: "A prospect asks: 'Why should we choose you over your competitors?' What is the best response structure?", dimension: "Persuasion", options: ["Immediately list every feature your competitors lack", "Acknowledge the competitive landscape, then focus on the specific outcomes your solution delivers for companies like theirs, backed by concrete evidence", "Tell them you are the market leader and let that stand alone", "Ask which specific competitor they are considering before saying anything about your own solution"], correct: 1 },
  // Objection Handling (9)
  { id: 19, text: "A prospect says 'Your price is too high.' What is the best initial response?", dimension: "Objection Handling", options: ["Offer a discount immediately to keep the conversation moving", "Apologise and explain in detail why your costs are what they are", "Ask 'Compared to what?' and explore the value the investment would generate for them relative to the cost", "Tell them the price is non-negotiable and ask if they want to proceed"], correct: 2 },
  { id: 20, text: "A prospect says 'We're happy with our current supplier.' What is the best response?", dimension: "Objection Handling", options: ["Tell them their current supplier is making mistakes they may not be aware of", "Accept the objection politely and close the call", "'That's great to hear. Most of the clients we work with said the same before we first spoke. What would need to change for you to consider an alternative?'", "Immediately offer a lower price than their current supplier"], correct: 2 },
  { id: 21, text: "A prospect says 'I need to think about it.' What is the best response?", dimension: "Objection Handling", options: ["Say 'No problem' and follow up in two weeks with the same pitch", "'Of course — what specifically would you need clarity on to feel confident moving forward?'", "Send them a comprehensive list of features to review in their own time", "Tell them you need a decision by end of week"], correct: 1 },
  { id: 22, text: "A prospect says 'This isn't a priority right now.' What is the best response?", dimension: "Objection Handling", options: ["Accept the objection and move them to a long-term nurture sequence with no further conversation", "Ask what their current priorities are, and explore whether your solution could help them achieve any of them faster", "Offer a discount to make it feel like a lower-risk decision", "Contact the same person again next week with the same pitch"], correct: 1 },
  { id: 23, text: "A prospect says 'I need to run this by my team before deciding.' What is the best response?", dimension: "Objection Handling", options: ["Offer to join a team meeting or provide materials tailored to each stakeholder's specific concerns", "Tell them the decision should ultimately be theirs to make", "Reduce the scope of your proposal so there is less for the team to review", "Give them an ultimatum — sign before the next team meeting or the offer lapses"], correct: 0 },
  { id: 24, text: "A prospect says 'We tried something similar before and it did not work.' What is the best response?", dimension: "Objection Handling", options: ["Dismiss their past experience as unrelated to your solution", "'I understand — tell me more about what happened. I want to make sure we are not setting you up for the same outcome.'", "Move past the comment and refocus on your product's features", "Tell them your product is completely different without exploring what happened"], correct: 1 },
  { id: 25, text: "A prospect asks: 'Can you match Competitor X's price?' What is the best response?", dimension: "Objection Handling", options: ["Agree to match it immediately to keep the deal alive", "Decline firmly and explain your pricing is fixed", "Explore what specific value they see in the competitor's offer and clarify how your total ROI compares before discussing any price adjustments", "Tell them the competitor's product is inferior without evidence"], correct: 2 },
  { id: 26, text: "A prospect who seemed engaged has gone completely silent after two follow-ups. What is the best approach?", dimension: "Objection Handling", options: ["Send a follow-up email every day until they reply", "Send a short, value-led 'breakup' email acknowledging they may have moved on, leaving the door open respectfully", "Escalate by contacting their manager or another senior contact", "Write off the deal and remove them from your pipeline immediately"], correct: 1 },
  { id: 27, text: "The same objection is appearing across several deals in your pipeline. What is the most productive response?", dimension: "Objection Handling", options: ["Try to work around it differently in each individual deal", "Lower your prices across the board to pre-empt the objection", "Document the objection, develop a strong evidence-based response, and review your target market to ensure product-market fit", "Remove the feature or element causing the objection from your pitch"], correct: 2 },
  // Closing (8)
  { id: 28, text: "A deal has stalled with no movement for two weeks. What is the most effective approach?", dimension: "Closing", options: ["Call every day until someone from the company responds", "Send a re-engagement message that frames the cost of inaction in terms of their goals and proposes a clear, low-friction next step", "Drop the price by 20% to create movement", "Assume the deal is lost and move your attention to new prospects"], correct: 1 },
  { id: 29, text: "The prospect has agreed in principle but will not sign the contract. What is the most effective approach?", dimension: "Closing", options: ["Resend the contract and wait for them to act", "Ask directly: 'What specifically is preventing you from signing right now?' and address those concerns", "Add extra incentives or terms to the contract without discussing them first", "Escalate directly to the prospect's manager"], correct: 1 },
  { id: 30, text: "You sent a proposal one week ago and have received no response. What is the best next step?", dimension: "Closing", options: ["Assume they are not interested and close the opportunity", "Call and ask if they had a chance to review it, offering to walk through any questions together on a short call", "Send a lower-priced version of the proposal without explanation", "Resend the same proposal with 'Following up' in the subject line"], correct: 1 },
  { id: 31, text: "A prospect asks for more time before committing. What is the best response?", dimension: "Closing", options: ["Tell them the offer expires at end of month to create urgency", "'Of course — what would you need to see or resolve during that time to feel confident in moving forward?'", "Tell them you will follow up in a month and leave it there", "Offer a smaller initial contract as a way to lower the commitment required"], correct: 1 },
  { id: 32, text: "Which closing technique is most appropriate for a complex B2B deal?", dimension: "Closing", options: ["The 'take it or leave it' close — make a final offer and walk away if they hesitate", "The assumptive close — act as if they have already decided and begin discussing implementation", "The summary close — summarise the agreed value, confirm readiness to proceed, and propose a clear set of next steps", "Creating false scarcity to force a decision this week"], correct: 2 },
  { id: 33, text: "The decision-maker is sold, but the finance team has raised concerns about the budget. What is the best next step?", dimension: "Closing", options: ["Reduce your price immediately to satisfy finance", "Offer to present the business case directly to the finance team, focusing on ROI and total cost of ownership", "Ask the decision-maker to override the finance team's concerns", "Walk away — if finance is not aligned, the deal will not close"], correct: 1 },
  { id: 34, text: "A deal is near closing at the end of the quarter. How do you create genuine, ethical urgency?", dimension: "Closing", options: ["Warn them the price will increase next month even if it will not", "Tell them another prospect is considering the same offer", "Tie the start date to a specific business outcome the prospect cares about — such as going live before a key event or peak period they mentioned", "Offer a free add-on that artificially expires at month-end"], correct: 2 },
  { id: 35, text: "Immediately after a prospect signs and the deal is closed, what is the most important next step?", dimension: "Closing", options: ["Ask for referrals straight away while the relationship is warm", "Confirm next steps clearly — implementation timeline, key contacts, and what the customer should expect to happen and when", "Celebrate internally and move your focus to the next prospect", "Send a generic welcome email and hand off to the customer success team without briefing them"], correct: 1 },
];

export const SA_DURATION_SECONDS = 20 * 60;

export const SA_DIMENSIONS: Array<{ label: SADimension; description: string; className: string }> = [
  { label: "Prospecting",        description: "Finding and qualifying the right opportunities.", className: "bg-green-500/10 text-green-300" },
  { label: "Persuasion",         description: "Communicating value and influencing buying decisions.", className: "bg-emerald-500/10 text-emerald-300" },
  { label: "Objection Handling", description: "Responding constructively to concerns and resistance.", className: "bg-teal-500/10 text-teal-300" },
  { label: "Closing",            description: "Moving deals forward and gaining commitment.", className: "bg-cyan-500/10 text-cyan-300" },
];

export function scoreSA(answers: (number | null)[]) {
  const dimStats: Record<SADimension, { correct: number; total: number }> = {
    Prospecting: { correct: 0, total: 0 },
    Persuasion: { correct: 0, total: 0 },
    "Objection Handling": { correct: 0, total: 0 },
    Closing: { correct: 0, total: 0 },
  };
  let totalCorrect = 0;
  SA_QUESTIONS.forEach((q, i) => {
    dimStats[q.dimension].total++;
    if (answers[i] !== null && answers[i] === q.correct) {
      totalCorrect++;
      dimStats[q.dimension].correct++;
    }
  });
  const percentage = Math.round((totalCorrect / SA_QUESTIONS.length) * 100);
  const dimensions = Object.fromEntries(
    (Object.keys(dimStats) as SADimension[]).map((d) => {
      const { correct, total } = dimStats[d];
      return [d, total > 0 ? Math.round((correct / total) * 100) : 0];
    })
  ) as Record<SADimension, number>;
  return { correct: totalCorrect, total: SA_QUESTIONS.length, percentage, dimensions };
}
