export type TMDimension = "Prioritization" | "Planning" | "Focus" | "Deadline Management";

export interface TMQuestion {
  id: number;
  text: string;
  dimension: TMDimension;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
}

export const TM_QUESTIONS: TMQuestion[] = [
  // Prioritization (8)
  { id: 1,  text: "You have four tasks due today: two are urgent and important, one is urgent but not important, and one is important but not urgent. What do you tackle first?", dimension: "Prioritization", options: ["The urgent-but-not-important task, to clear it from your list quickly", "The important-but-not-urgent task, as it has higher long-term value", "The two tasks that are both urgent and important", "Work through the list in the order your manager assigned them"], correct: 2 },
  { id: 2,  text: "Your manager gives you a new high-priority task while you are mid-way through a complex piece of work. What do you do?", dimension: "Prioritization", options: ["Drop the current work and switch immediately — the manager's request comes first", "Clarify with your manager how urgent the new task is relative to your current work, then act on their guidance", "Finish your current task completely before starting anything new", "Begin both tasks simultaneously so neither is ignored"], correct: 1 },
  { id: 3,  text: "Your to-do list has 15 items on it. What is the most effective approach?", dimension: "Prioritization", options: ["Work through items from top to bottom in the order they were added", "Do the easiest tasks first to build momentum", "Identify the three or four highest-impact items and focus on those first", "Delegate any tasks you find difficult or unfamiliar"], correct: 2 },
  { id: 4,  text: "You consistently have more work than time available. What is the most effective long-term response?", dimension: "Prioritization", options: ["Work longer hours indefinitely to keep pace", "Try to do everything and accept a lower quality output", "Raise the issue with your manager and discuss which items can be deprioritised, delegated, or removed", "Silently drop the lowest-priority tasks without telling anyone"], correct: 2 },
  { id: 5,  text: "A colleague asks for your help while you are working on something urgent. What is the best action?", dimension: "Prioritization", options: ["Stop immediately and help them — relationships matter most", "Ignore the request and focus on your task", "Let them know you are dealing with something urgent and set a specific time when you will be available to help", "Send them to someone else without explanation"], correct: 2 },
  { id: 6,  text: "You have been invited to a meeting with no agenda that covers a topic requiring no input from you. What do you do?", dimension: "Prioritization", options: ["Attend and use the time to catch up on emails", "Politely decline or ask to be excused, explaining your current priorities", "Attend and leave early without telling the organiser", "Attend all meetings — it is always worth being in the room"], correct: 1 },
  { id: 7,  text: "Which task should generally be completed first?", dimension: "Prioritization", options: ["A task your manager requested yesterday", "A task that unblocks three colleagues from progressing with their own work", "A detailed report due next week that requires focused concentration", "Clearing and responding to your email inbox"], correct: 1 },
  { id: 8,  text: "You have two tasks with the same deadline that both seem equally important. How do you decide which to start first?", dimension: "Prioritization", options: ["Choose randomly — both have equal priority", "Choose the one you find more enjoyable to build early momentum", "Assess which has the higher consequence if it is delayed, and start with that one", "Ask someone else to take on one of the tasks"], correct: 2 },
  // Planning (8)
  { id: 9,  text: "What is the most effective approach to planning a complex project before starting work?", dimension: "Planning", options: ["Start immediately and allow the plan to emerge as you go", "Write a rough plan but expect to update it constantly based on daily circumstances", "Break the project into milestones, estimate the time required per task, and identify key dependencies before beginning", "Create a detailed plan only after problems emerge"], correct: 2 },
  { id: 10, text: "At the start of each working day, what is the most effective planning habit?", dimension: "Planning", options: ["Check email first and allow the contents to dictate your day's priorities", "Identify your three most important outcomes for the day and protect time to achieve them", "Plan your day in 15-minute increments from start to finish", "Start working immediately — planning is a distraction from getting things done"], correct: 1 },
  { id: 11, text: "You are planning a task and realise you are missing key information before you can begin. What is the best action?", dimension: "Planning", options: ["Start anyway and fill in the gaps as they become apparent", "Wait until you have perfect information before committing to any timeline", "Identify precisely what information is missing and who holds it, then gather what you need before committing to a start date", "Make assumptions and present them as fact to move forward quickly"], correct: 2 },
  { id: 12, text: "You have two weeks to complete a project. What is the biggest risk of not setting sub-task deadlines along the way?", dimension: "Planning", options: ["You risk finishing too early and having unused time at the end", "You risk over-delivering on quality", "You are likely to spend too long on early stages and rush the most critical parts near the final deadline", "Your manager may feel excluded from the process"], correct: 2 },
  { id: 13, text: "What is the most effective approach to estimating how long a task will take?", dimension: "Planning", options: ["Halve your gut estimate — most people significantly overestimate task duration", "Base your estimate on how long comparable tasks have taken previously and add a buffer for unexpected complications", "Commit to whatever deadline your stakeholder suggests without question", "Say 'it will take as long as it takes' to avoid committing prematurely"], correct: 1 },
  { id: 14, text: "You have planned your week in detail but an unexpected high-priority request arrives on Tuesday. What is the most effective response?", dimension: "Planning", options: ["Add it to your existing list and attempt to fit it in around current commitments", "Assess what the new request displaces, update your plan, and communicate any impacted deadlines to stakeholders", "Ignore it until your originally planned work is complete", "Work additional hours each evening to absorb the new work without any rescheduling"], correct: 1 },
  { id: 15, text: "Which approach best supports managing multiple complex deadlines simultaneously?", dimension: "Planning", options: ["Mental notes and a good memory", "A single running to-do list updated daily", "A visual task plan showing tasks, owners, deadlines, and dependencies across the full timeline", "Daily stand-up meetings with the team to keep everyone aligned"], correct: 2 },
  { id: 16, text: "A task you are planning requires input from another team before you can proceed. What is the best approach?", dimension: "Planning", options: ["Start your own work and hope they deliver before you need it", "Make assumptions about their input and fill it in yourself", "Agree a delivery date with them explicitly, build it into your plan, and follow up proactively as that date approaches", "Wait for them to contact you when they are ready"], correct: 2 },
  // Focus (7)
  { id: 17, text: "You are working on a task that requires deep concentration, but notifications keep interrupting you. What is the most effective action?", dimension: "Focus", options: ["Continue managing both — you are good at handling interruptions", "Turn off notifications for a defined period and set a specific time to check messages", "Respond to each notification as it arrives so it does not distract you later", "Move to a different location each time a notification distracts you"], correct: 1 },
  { id: 18, text: "You are halfway through an important task and keep being pulled away by lower-priority interruptions. What is the best long-term solution?", dimension: "Focus", options: ["Shift to working only in the evenings when there are fewer people around", "Block focused time on your calendar and communicate your availability windows to colleagues", "Work faster to reduce the window in which interruptions can occur", "Accept that interruptions are unavoidable and manage around them indefinitely"], correct: 1 },
  { id: 19, text: "You sit down to work but feel overwhelmed and cannot decide where to start. What is the most effective approach?", dimension: "Focus", options: ["Browse the internet briefly to reset your mental state", "Write down the single most important task and commit to focusing on only that for the next 25–30 minutes", "Write a full list of everything you need to do before starting anything", "Call a colleague to talk through your workload before beginning"], correct: 1 },
  { id: 20, text: "Research consistently shows that frequent task-switching typically:", dimension: "Focus", options: ["Improves overall output by maintaining energy levels and variety", "Reduces quality and efficiency due to the cognitive cost of each context switch", "Is effective provided the tasks draw on different cognitive skills", "Is recommended practice for high-performing individuals"], correct: 1 },
  { id: 21, text: "You are in the middle of focused work when a colleague stops by for a chat. What is the best response?", dimension: "Focus", options: ["Stop your work immediately and engage — relationships are important", "Ignore them and continue working without acknowledging them", "Acknowledge them, let them know you are in a focused period, and agree a specific time to connect shortly", "Ask them to send you an email instead"], correct: 2 },
  { id: 22, text: "Which habit best supports sustained focus and mental performance throughout the working day?", dimension: "Focus", options: ["Consuming multiple coffees to maintain alertness throughout the day", "Working without breaks until a task is fully complete", "Taking short, regular breaks between focused work sessions to restore mental energy", "Scheduling all meetings before 9am to protect the full rest of the day"], correct: 2 },
  { id: 23, text: "You need to do focused, cognitively demanding work and your open-plan office is noisy. What is the most effective approach?", dimension: "Focus", options: ["Try to focus regardless — the ability to block out noise is a skill worth building", "Wait for a quieter moment during the day, which may never arrive", "Book a quiet room, use noise-cancelling headphones, or discuss with your manager the need for protected focus time", "Do the task quickly and accept lower quality to get out of the noisy environment"], correct: 2 },
  // Deadline Management (7)
  { id: 24, text: "You realise three days before a deadline that you will not be able to deliver on time. What do you do?", dimension: "Deadline Management", options: ["Deliver whatever you have completed on the deadline without flagging the shortfall", "Communicate immediately with your manager or stakeholder, explain the situation, and propose a revised timeline or reduced scope", "Work through the night and hope you can make the original deadline", "Deliver late without any prior warning and explain the situation afterwards"], correct: 1 },
  { id: 25, text: "A stakeholder requests an earlier delivery date than originally agreed. What is the best response?", dimension: "Deadline Management", options: ["Agree immediately to demonstrate flexibility and a willingness to help", "Assess realistically what is required to hit the new date, then respond either with confirmation or a transparent explanation of what is and is not achievable", "Decline — the original date was agreed and should not be changed", "Say you will try your best without committing to anything specific"], correct: 1 },
  { id: 26, text: "You have several deadlines falling on the same day. What is the best approach?", dimension: "Deadline Management", options: ["Work on all deliverables simultaneously to make parallel progress", "Identify which deadline carries the highest consequence if missed, complete that first, and communicate proactively if others are at risk", "Request deadline extensions for all items to reduce the pressure", "Work through the night the day before all deadlines fall"], correct: 1 },
  { id: 27, text: "A colleague's delayed delivery is preventing you from completing your own deliverable on time. What is the most effective response?", dimension: "Deadline Management", options: ["Wait and hope they deliver something soon", "Miss your deadline and attribute it to your colleague's delay", "Contact your colleague to set a firm revised delivery expectation, and inform your stakeholder that your deadline is at risk and why", "Complete their work yourself without discussing it with them"], correct: 2 },
  { id: 28, text: "You have been given a deadline that you believe is unrealistic from the outset. What is the best action?", dimension: "Deadline Management", options: ["Accept it and do your best — complaining about deadlines looks bad", "Refuse to begin the work until a more realistic deadline is agreed", "Raise your concern immediately with a clear explanation and propose a realistic alternative timeline with justification", "Start the work and escalate the issue only when it becomes a visible problem"], correct: 2 },
  { id: 29, text: "You met a deadline, but the quality of the output is below your normal standard due to time pressure. What do you do?", dimension: "Deadline Management", options: ["Submit and say nothing — the deadline was met and that is what was asked", "Inform the recipient that time constraints affected quality and propose a follow-up to improve the output if needed", "Withdraw the submission and request more time even though the deadline has passed", "Resubmit a better version without informing anyone — they may not have noticed"], correct: 1 },
  { id: 30, text: "After consistently delivering on time for months, you miss a deadline for the first time. What is the most appropriate response?", dimension: "Deadline Management", options: ["Apologise once and move forward without dwelling on it", "Reflect on what caused the miss, address the root cause, and proactively share what you are changing to prevent it recurring", "Attribute the miss to external factors outside your control", "Offer to work unpaid to compensate for the impact of the missed deadline"], correct: 1 },
];

export const TM_DURATION_SECONDS = 20 * 60;

export const TM_DIMENSIONS: Array<{ label: TMDimension; description: string; className: string }> = [
  { label: "Prioritization",      description: "Identifying and focusing on the highest-impact work.", className: "bg-amber-500/10 text-amber-300" },
  { label: "Planning",            description: "Organising work effectively before and during execution.", className: "bg-yellow-500/10 text-yellow-300" },
  { label: "Focus",               description: "Maintaining concentration and avoiding unproductive distractions.", className: "bg-orange-500/10 text-orange-300" },
  { label: "Deadline Management", description: "Meeting commitments and managing expectations proactively.", className: "bg-red-500/10 text-red-300" },
];

export function scoreTM(answers: (number | null)[]) {
  const dimStats: Record<TMDimension, { correct: number; total: number }> = {
    Prioritization: { correct: 0, total: 0 },
    Planning: { correct: 0, total: 0 },
    Focus: { correct: 0, total: 0 },
    "Deadline Management": { correct: 0, total: 0 },
  };
  let totalCorrect = 0;
  TM_QUESTIONS.forEach((q, i) => {
    dimStats[q.dimension].total++;
    if (answers[i] !== null && answers[i] === q.correct) {
      totalCorrect++;
      dimStats[q.dimension].correct++;
    }
  });
  const percentage = Math.round((totalCorrect / TM_QUESTIONS.length) * 100);
  const dimensions = Object.fromEntries(
    (Object.keys(dimStats) as TMDimension[]).map((d) => {
      const { correct, total } = dimStats[d];
      return [d, total > 0 ? Math.round((correct / total) * 100) : 0];
    })
  ) as Record<TMDimension, number>;
  return { correct: totalCorrect, total: TM_QUESTIONS.length, percentage, dimensions };
}
